/* Parabolic 100 — the pattern taxonomy.
   The NeetCode-roadmap layer: named, reusable judgment moves. Problems train
   patterns; mastery is tracked per pattern; interviews probe patterns.
   Tiers: 1 Reads (see the situation) → 2 Mechanisms (build the machine)
        → 3 Hard Calls (judgment under pressure) → 4 Multipliers (compound everything). */

P100.TIERS = [
  { n: 1, name: "Reads", d: "See the situation correctly before touching it." },
  { n: 2, name: "Mechanisms", d: "The machines you build so judgment scales past you." },
  { n: 3, name: "Hard Calls", d: "Decisions under pressure, scarcity, and incident heat." },
  { n: 4, name: "Multipliers", d: "Moves that make every other pattern land harder." },
];

P100.PATTERNS = [
  /* ---------- Tier 1 — Reads ---------- */
  {
    id: "bottleneck-reclassification",
    name: "Bottleneck Reclassification",
    tier: 1,
    move: "The presented problem is rarely the binding constraint. Rename the real one before acting.",
    tells: ["Momentum language: 'accelerate', 'pour fuel on'", "A solution label where a problem should be", "Stable metrics next to falling satisfaction"],
    antiPattern: "Solving the stated problem harder — more agents, more velocity, a better model — while the actual constraint compounds.",
    interview: "Almost every case round opens here: the prompt describes symptom A while the graded answer names constraint B. Interviewers score whether you reclassify out loud before proposing anything.",
  },
  {
    id: "solution-shape-matching",
    name: "Solution-Shape Matching",
    tier: 1,
    move: "Match the tool's shape to the task's variance: pipeline for fixed paths, model steps only where inputs genuinely vary.",
    tells: ["A deterministic workflow wearing an agent costume", "Reliability capped near demo-quality", "Architecture derived from a conference talk, not the task"],
    antiPattern: "Blanket answers in either direction — 'agents for everything' or 'RPA for everything' — without checking input variance.",
    interview: "FDE and deployment-eng loops love 'would you even use a model here?' The credible answer maps task variance first; spending tokens only on genuine variance is the trust signal.",
  },
  {
    id: "ask-need-decomposition",
    name: "Ask → Need Decomposition",
    tier: 1,
    move: "Demands arrive as implementations. Decompose to the underlying need — it usually has a cheaper, faster satisfaction.",
    tells: ["A feature named as a renewal condition", "'We want on-prem / a mega-agent / agents for productivity'", "Procurement language where requirements should be"],
    antiPattern: "Negotiating the ask as stated — sign it or refuse it — instead of breaking the ask-equals-need equation.",
    interview: "TPM and DPM loops probe this with customer-demand scenarios. The pass is naming the need under the ask and trading a pilot for a promise; the fail is arguing yes/no on the surface demand.",
  },
  {
    id: "who-bears-the-risk",
    name: "Who Bears the Risk",
    tier: 1,
    move: "Separate whose bet it is. Infrastructure capital cycles and application value move independently — locate the risk before reacting to the headline.",
    tells: ["'Is this a bubble? Should we pause?'", "Capex headlines driving application decisions", "Risk framing that ignores who captures overbuild surplus"],
    antiPattern: "Punditry in either direction — 'AI is the future' or 'be careful, frothy' — that changes no actual decision.",
    interview: "Market-calibration questions in exec-facing roles: the graded skill is separating risk-bearer from surplus-capturer, then attaching dated falsifiers. Also the Gnomon muscle itself.",
  },

  /* ---------- Tier 2 — Mechanisms ---------- */
  {
    id: "gate-design",
    name: "Gate Design",
    tier: 2,
    move: "Convert vibes-based go/no-go into published criteria with owners, dates, visible overrides — and an accelerate clause, so the gate can say yes fast.",
    tells: ["'Ready' existing as an opinion two teams argue about", "Re-run-until-green culture", "A gate everyone quietly routes around"],
    antiPattern: "Gates that only slow things down — no acceleration clause, no owner, no priced override — which makes you 'the person who says no' until you get steamrolled.",
    interview: "'How would you decide whether to launch X?' is a gate-design question. Anthropic TPM loops in particular ask for a real gate you built, what it caught, and how it earned legitimacy.",
  },
  {
    id: "staged-exposure",
    name: "Staged Exposure",
    tier: 2,
    move: "Rings, canaries, autonomy ladders: bound the blast radius, promote on evidence, and let strong data collapse the schedule.",
    tells: ["'Everyone live in Q1'", "Write access requested as a yes/no", "One first impression per user, about to be spent all at once"],
    antiPattern: "Big-bang exposure — or its mirror, permanent pilot: a ladder with no advancement clause is just 'no' wearing process clothing.",
    interview: "Rollout-design cases: 'take this to 20,000 seats' or 'when does the agent get write access?' Scored on ring gates that cut both ways and support scaling by deflection, not headcount.",
  },
  {
    id: "failure-decomposition",
    name: "Failure Decomposition",
    tier: 2,
    move: "Split the monolithic failure into measurable classes and route each to its own fix — retrieval ≠ grounding ≠ generation ≠ permissions.",
    tells: ["Every error blamed on 'the model'", "A proposed model swap as the fix", "One aggregate quality score hiding the failures that matter"],
    antiPattern: "Model-swap thrash: changing the biggest component because it demos better, while the actual failing stage keeps failing.",
    interview: "The RAG-debugging interview is a classic FDE screen. The pass is a failure taxonomy with per-stage metrics before any fix; naming permission leaks as the program-ending class is the differentiator.",
  },
  {
    id: "instrument-first",
    name: "Instrument Before Acting",
    tier: 2,
    move: "Build the eval before the fix, and treat the instrument itself as a product that rots — coverage against live reality is the metric.",
    tells: ["Usage curves standing in for value", "A stable score next to rising complaints", "An eval set older than the workflows it grades"],
    antiPattern: "Shipping fixes validated against a stale set — overfitting the demo distribution harder — or quoting industry benchmarks to a CFO who asked about their deployment.",
    interview: "Evals questions are now standard in every lab loop: 'how would you know it works?' Scored on measurement design, golden-set lifecycle, and the offline–online gap. This is the Safeguards-TPM core.",
  },
  {
    id: "paved-road",
    name: "Paved Road",
    tier: 2,
    move: "Demand routes around friction toward capability. Sequence: contain the regulated slice now, ship the sanctioned path, then enforce — the road must win on merit.",
    tells: ["Shadow usage at personal risk", "A blanket ban drafted as the response", "Compliance gates that are slower than the workaround"],
    antiPattern: "Block-only responses that push usage somewhere less visible — or 'enable everything' answers that fail the genuinely regulated slice.",
    interview: "Governance scenarios: '200 employees are pasting data into consumer AI.' The pass reads shadow usage as demand signal and sequences containment→capability→enforcement; the fail picks a side.",
  },

  {
    id: "status-truth",
    name: "Status Truth",
    tier: 2,
    move: "Make true program state cheap to see and safe to say — instruments and rituals that surface red early, and incentives that don't punish the messenger.",
    tells: ["Green dashboards, anxious hallways", "Surprise slips near deadlines", "Status meetings that perform instead of inform"],
    antiPattern: "Adding more reporting instead of changing the incentive — ten dashboards that all lie the same way, or shooting the first messenger and wondering why the second never came.",
    interview: "A TPM-loop staple: 'a program you inherited was greener on paper than in reality — what did you do?' Scored on instrumenting truth and protecting its carriers, not on heroic detective work.",
  },
  {
    id: "commitment-design",
    name: "Commitment Design",
    tier: 2,
    move: "Structure who-promises-what-by-when across teams — explicit, dated, owned, with slip signals attached — so coordination survives without goodwill or authority.",
    tells: ["Dependencies held together by 'they said Q2'", "No alarm fires when a promise quietly slips", "Escalations with nothing written to point at"],
    antiPattern: "Escalating without a contract to reference — or padding your own schedule secretly, which trades one slip for systemic distrust.",
    interview: "The influence-without-authority question in every TPM loop: the pass is a designed commitment (owner, date, slip signal, escalation trigger), not charisma or espresso diplomacy.",
  },

  /* ---------- Tier 3 — Hard Calls ---------- */
  {
    id: "ownership-forcing",
    name: "Ownership Forcing",
    tier: 3,
    move: "Nothing scales, survives, or stays fresh without a named economic owner. Find the P&L that captures the value and manufacture the decision.",
    tells: ["A successful pilot aging in 'evaluation'", "A connector or eval set nobody operates", "Success that never created a decision"],
    antiPattern: "Relaunching enthusiasm at the same users — energy where the missing resource is an owner — or assigning ownership to IT because they answered the email.",
    interview: "Behavioral gold: 'tell me about something stuck that you unstuck.' The strong story names the ownership vacuum, the value math that forced a decision, and the genuine kill option that made it credible.",
  },
  {
    id: "precedent-pricing",
    name: "Precedent Pricing",
    tier: 3,
    move: "Every exception is a policy the moment it exists. Price it across the whole book — booked and pipeline — before granting it.",
    tells: ["'Just this one customer'", "A commitment letter waiting for a signature", "Exceptions granted by escalation volume"],
    antiPattern: "Deciding the case in front of you as if it were the only instance — the $40M question is never a $40M decision.",
    interview: "Negotiation and prioritization cases: the differentiator is asking 'how many accounts invoke this tomorrow?' and knowing your walk-away line. Labs test this on enterprise-demand scenarios constantly.",
  },
  {
    id: "scarcity-allocation",
    name: "Allocation Under Scarcity",
    tier: 3,
    move: "Under scarcity, allocation is a product with a published policy: commitment tiers, degradation order, honest dates — and stop selling what you don't have.",
    tells: ["Rate limits hitting contractual customers", "Sales still signing against missing capacity", "Exceptions flowing to the loudest voice"],
    antiPattern: "Pure demand-shaping answers that duck the political core: someone must tell sales to stop, and tell a named customer where they rank.",
    interview: "The Anthropic cloud-inference TPM interview is this pattern. CAPE version: constrained seat/preview allocation. Scored on published policy versus exception queue, and on protecting internal workloads explicitly.",
  },
  {
    id: "contain-remediate-reexpand",
    name: "Contain, Remediate, Re-expand",
    tier: 3,
    move: "Run AI failures as real incidents: contain by scope (not shutdown), make the harmed party whole, root-cause into a regression eval, size the pattern via audit, and gate re-entry.",
    tells: ["An executive holding a kill switch", "'Do we shut it off?'", "A binary fight between full stop and push on"],
    antiPattern: "Panic shutdown (teaches the org any error kills AI) or minimize-and-continue (the next incident arrives with a negligence paper trail).",
    interview: "Incident scenarios are rising fast in lab loops: 'the model told an employee something wrong and they acted on it.' Scored on running four tracks at once and on auditing past answers to size the problem.",
  },
  {
    id: "trust-recovery",
    name: "Trust Recovery",
    tier: 3,
    move: "Trust decays faster than data and never recovers by silent repair. Put provenance in the product, then run a deliberate win-back with the burned users.",
    tells: ["Usage quietly down 30% — the eval nobody read", "Users cross-checking every answer", "A fixed system nobody came back to"],
    antiPattern: "Fixing the pipeline and declaring victory — the field is already back on PDFs, and no sync job un-teaches that habit.",
    interview: "Adoption-recovery stories are behavioral-round differentiators: the strong answer treats usage decay as continuous evaluation by users and names the product change that re-earned the shortcut.",
  },

  /* ---------- Tier 4 — Multipliers ---------- */
  {
    id: "evidence-shaping",
    name: "Evidence Shaping",
    tier: 4,
    move: "Organizations move on the shape of evidence, not its volume: anecdote→pattern (breadth × severity), usage→value (baseline × delta), applause→conversion.",
    tells: ["Three 'edge cases' that are one pattern", "A CFO asking if usage means ROI", "Feature requests filed loudly instead of quantified"],
    antiPattern: "Louder advocacy with the same evidence shape — or amplifying a pattern you never verified, which destroys the channel permanently.",
    interview: "The product-feedback interview at every lab: 'how do you decide what the field signal means?' Scored on the arithmetic — accounts × severity × pipeline — and on the discipline to verify before amplifying.",
  },
  {
    id: "altitude-switching",
    name: "Altitude Switching",
    tier: 4,
    move: "Same judgment, three rooms: the exec gets the decision and the stakes, the engineer gets the constraints, the interviewer gets the transferable principle.",
    tells: ["A technically right answer landing wrong", "The same brief sent to a CVP and an eng lead", "20 seconds of attention and 200 words of answer"],
    antiPattern: "One altitude for all audiences — usually the engineer's — or altitude as spin, where the rooms get different facts instead of different framings.",
    interview: "This is the interview itself. Panels deliberately switch altitude mid-loop; the candidates who get offers re-frame the same call for each interviewer without being asked.",
  },
  {
    id: "prototype-for-belief",
    name: "Prototype for Belief",
    tier: 4,
    move: "Working software on their data creates a category of belief no deck can. Build disposable prototypes as discovery instruments — each carrying its productionization truth.",
    tells: ["An 'art of the possible' request answered with slideware", "A room that needs to imagine itself using it", "Demo enthusiasm about to become an unpayable commitment"],
    antiPattern: "Discovery-first stalling when the room asked for possibility — or demos without the 'what production takes' slide, which mint commitments engineering never agreed to.",
    interview: "FDE loops directly test prototyper judgment: when to build fast and throw away, and how to keep a hot demo from becoming a promise. The disposability framing is the senior signal.",
  },
  {
    id: "portfolio-triage",
    name: "Portfolio Triage",
    tier: 4,
    move: "Explicit selection functions — value × workflow specificity × data readiness × owner willingness — and lighthouses over spread. Parked must mean sequenced, not dead.",
    tells: ["43 use cases ranked by applause", "Capacity for three, plans for ten", "An exec vote standing in for a scoring cut"],
    antiPattern: "Building the top of the enthusiasm ranking — exec votes overweight visibility and underweight data readiness, so you pick demos again, politely.",
    interview: "Prioritization cases everywhere: the pass is a legible selection function that corrects a named bias, plus graduation criteria that keep the 'no' pile from poisoning the relationship.",
  },
];

/* Problem → patterns (primary first). Kept separate from problems-*.js so the
   bank files stay pure content. */
P100.PATTERN_TAGS = {
  "001": ["bottleneck-reclassification", "gate-design", "portfolio-triage"],
  "002": ["ask-need-decomposition", "prototype-for-belief"],
  "003": ["failure-decomposition", "instrument-first"],
  "004": ["gate-design", "staged-exposure"],
  "005": ["instrument-first", "evidence-shaping"],
  "006": ["portfolio-triage", "evidence-shaping"],
  "007": ["prototype-for-belief", "altitude-switching"],
  "008": ["solution-shape-matching", "ask-need-decomposition"],
  "009": ["solution-shape-matching"],
  "010": ["staged-exposure", "gate-design", "precedent-pricing"],
  "011": ["solution-shape-matching", "evidence-shaping"],
  "012": ["contain-remediate-reexpand", "staged-exposure", "trust-recovery"],
  "013": ["instrument-first", "trust-recovery", "ownership-forcing"],
  "014": ["paved-road", "contain-remediate-reexpand"],
  "015": ["contain-remediate-reexpand", "failure-decomposition"],
  "016": ["failure-decomposition", "instrument-first", "trust-recovery"],
  "017": ["instrument-first", "ownership-forcing", "bottleneck-reclassification"],
  "018": ["ownership-forcing", "evidence-shaping"],
  "019": ["staged-exposure", "gate-design", "portfolio-triage"],
  "020": ["evidence-shaping", "ownership-forcing"],
  "021": ["ask-need-decomposition", "precedent-pricing", "altitude-switching"],
  "022": ["bottleneck-reclassification", "ask-need-decomposition"],
  "023": ["scarcity-allocation", "precedent-pricing", "who-bears-the-risk"],
  "024": ["gate-design", "paved-road", "bottleneck-reclassification"],
  "025": ["who-bears-the-risk", "altitude-switching"],
  "026": ["commitment-design", "ownership-forcing", "evidence-shaping"],
  "027": ["status-truth", "instrument-first"],
  "028": ["instrument-first", "evidence-shaping", "bottleneck-reclassification"],
  "029": ["ownership-forcing", "evidence-shaping", "trust-recovery"],
  "030": ["trust-recovery", "precedent-pricing", "altitude-switching"],
  "031": ["commitment-design", "gate-design"],
  "032": ["status-truth", "altitude-switching"],
  "033": ["commitment-design", "precedent-pricing"],
  "034": ["instrument-first", "status-truth"],
  "035": ["ask-need-decomposition", "portfolio-triage"],
  "036": ["ask-need-decomposition", "solution-shape-matching"],
  "037": ["solution-shape-matching", "instrument-first"],
  "038": ["bottleneck-reclassification", "instrument-first"],
  "039": ["solution-shape-matching", "portfolio-triage"],
  "040": ["staged-exposure", "gate-design"],
  "041": ["instrument-first", "failure-decomposition"],
  "042": ["instrument-first", "status-truth"],
  "043": ["instrument-first", "evidence-shaping"],
  "044": ["failure-decomposition", "gate-design"],
  "045": ["gate-design", "instrument-first"],
};
