/* Parabolic 100 — problem bank, part 16 (086–090: Evals complete + DCM complete) */

P100.PROBLEMS.push(

/* ============================================================ 086 */
{
  id: "086",
  title: "The Eval That Trained the Model",
  difficulty: "Medium",
  category: "Evals & Measurement",
  primaryLens: "Eval",
  secondaryLens: "Architecture",
  archetype: "Sweeper",
  secondaryArchetype: "Maintainer",
  targetRoles: ["MSFT MAI Evals Eng", "Anthropic TPM Safeguards & Evals", "CAPE SCPM"],
  tags: ["contamination", "golden-sets", "fine-tuning", "data-hygiene"],
  prompt:
    "A customer's fine-tuned support model (037's bake-off winner, tuned on taxonomy and form) posts a startling result: 97% on the golden set, up from 84% pre-tuning — the biggest jump the eval program has ever recorded. The team is celebrating. Then a data engineer, cleaning up the training pipeline, notices something: the fine-tuning corpus was built from 'historical resolved tickets' — and 016's golden set was built by sampling and labeling… historical resolved tickets. Same source, same period. Nobody checked the overlap. The 97 might be memorization wearing a medal. Handle the number, the process, and the celebration.",
  arc: {
    start: "A record-breaking score, a shared data source, and an overlap nobody thought to check.",
    mid: "Quantify the contamination, re-measure on provably held-out data, and re-plumb the pipelines so sets can't touch.",
    end: "An honest number (probably good, smaller), lineage that makes recurrence impossible — and a team that celebrates twice as carefully.",
  },
  expected: {
    bottleneck: "Train/test separation was never engineered — the eval set and the training corpus were drawn from the same pool by different teams at different times, with no shared registry of what's held out; the 97 is unfalsifiable until the overlap is quantified, and every decision downstream of it (the tuning program's expansion, the vendor bake-off verdicts) inherits the doubt.",
    failureMode: "The celebration compounds: the 97 headlines the QBR, the fine-tuning program expands on its evidence, competitors' models get benchmarked against a contaminated bar — and when the overlap surfaces later (data lineage questions always surface), every eval number the program ever produced gets discounted together (042's moved-goalposts crisis, but self-inflicted and with receipts), which is catastrophically more expensive than one awkward correction today.",
    nextMove: "Treat it as a measurement incident with 015's discipline: (1) quantify before confessing — compute the actual overlap (exact-match and near-duplicate detection between the golden set and the tuning corpus; expect fuzzy matches: same ticket, different formatting); (2) re-measure honestly — score the model on the uncontaminated subset AND on a fresh sample from post-tuning-period tickets (016's production sampling, re-run); the honest number is probably still good — 037's bake-off said tuning helped taxonomy — just not 97; (3) correct the record with 034's migration craft — 'the instrument improved, here's the honest series' to everyone who saw the 97, before it anchors; (4) fix the class with lineage — a held-out registry (eval items tagged at birth, excluded from every training pipeline by ID, enforced in the data plumbing, not by memo — 057's identity indexing built exactly this rail), and a contamination check as a standing gate before any eval result on any tuned model publishes (045's checklist grows a row); (5) audit the blast radius — anything decided on contaminated comparisons (the bake-off itself: did the tuned model's eval wins include leaked items?) gets re-checked.",
    metric: "The overlap rate (exact + near-duplicate) and the re-measured score on provably held-out data — the delta between 97 and honest IS the contamination's size; going forward: registry coverage (every eval item lineage-tagged) and the contamination gate's presence in every eval publication.",
    owner: "The data engineer who caught it gets public credit (027's law: the first honest red gets thanked, loudly); the eval owner runs the re-measurement and owns the registry; the tuning team owns corpus exclusion plumbing; you own the correction's altitude and timing.",
    falsifier: "If the overlap check comes back clean — the sampling windows didn't actually intersect, or dedup catches near-zero matches — then the 97 is real, the celebration resumes with better evidence than it had, and the only deliverable is the registry and gate that make this check automatic instead of accidental (the scare was free; the infrastructure it motivates isn't optional).",
  },
  modelAnswer:
    "Freeze the number first: the 97 is currently unfalsifiable, which for a measurement is the same as wrong. A model tuned on a corpus that may contain the exam will score brilliantly on the exam — memorization presents as mastery, and the tell is exactly what happened: the biggest jump the program ever recorded. Extraordinary scores demand extraordinary hygiene, and 'same source, same period, different teams, no registry' is how contamination happens everywhere it happens — nobody cheats; the pipelines just never met.\n\nRun it as a measurement incident. Quantify: exact and near-duplicate matching between golden set and tuning corpus — expect fuzzy overlap (the same resolved ticket reformatted three ways), which is why the check needs similarity detection, not just ID joins. Re-measure: the uncontaminated subset gives you a defensible interim number; a fresh sample from post-tuning tickets (016's discipline, re-run) gives you the real one. The honest result is probably still good — 037's bake-off showed genuine taxonomy gains — just not record-breaking; the correction is from 'miracle' to 'solid,' which is survivable today and reputation-ending later. Correct with 034's craft: everyone who saw the 97 gets the honest series before it anchors in a QBR deck, framed as the instrument improving.\n\nThen make recurrence impossible rather than discouraged: a held-out registry — eval items lineage-tagged at creation, excluded from every training pipeline by ID at the plumbing layer (057's identity indexing built this rail for privacy; contamination control rides it for free), and a standing contamination check gating any eval publication on any tuned model (045's row). Audit the blast radius honestly — the bake-off's verdict itself may have been flattered. And celebrate the data engineer publicly and specifically: 027 taught this org that the first person to say red determines whether there's ever a second — a culture where the pipeline-cleaner who un-discovered a miracle gets thanked is the only durable contamination control there is.",
  rubric: {
    diagnosis: "Reads the record jump as the contamination tell and names the structural cause — shared pools, separate teams, no registry — without assigning cheating.",
    move: "Quantify with near-dup detection, re-measure on provably held-out data, correct via 034's migration, build lineage-enforced separation and a standing gate.",
    measurement: "Overlap rate and the honest re-measured score; falsifier lets the 97 survive and keeps the registry as the non-optional deliverable.",
    synthesis: "Rides 057's lineage rail for contamination control and applies 027's messenger law to the data engineer — infrastructure and culture as one fix.",
    altitude: "The QBR hears 'solid, verified gain' instead of a miracle that would have to be retracted — the correction priced today at its cheapest.",
    transfer: "Train/test contamination is the lab-core data-hygiene problem — held-out registries, lineage enforcement, and publication gates are exactly how serious eval organizations survive their own fine-tuning programs.",
  },
  adversarial:
    "The celebration-momentum failure: 'flag it quietly, verify later, don't ruin the QBR' — the 97 anchors, the program expands on it, and the eventual correction costs the whole eval franchise instead of one slide (042's crisis, chosen deliberately). The purity-panic failure: torching the fine-tuning program because contamination was possible — the bake-off's underlying finding (tuning helps taxonomy) likely survives re-measurement; killing the program on an unquantified scare replaces one measurement error with a bigger judgment one. The memo miss: fixing separation by policy ('teams should check overlap') instead of plumbing — 060's law applies: an exclusion that isn't enforced in the pipeline is a hope, and hopes don't survive the next reorg's data engineers.",
  recursiveFollowup:
    "The check returns: 31% overlap, and the honest score is 88 — a real four-point gain, not thirteen. But the audit's uncomfortable finding is elsewhere: the vendor bake-off (035's proof) also used golden-set-adjacent data, and the LOSING vendor's protest — dismissed at the time as sour grapes — specifically alleged this. The verdict that shaped the eval-tooling contract was contaminated. Legal asks if the procurement decision needs revisiting; the vendor relationship is now load-bearing (their platform runs everything). Decide what honesty owes the losing vendor, the contract, and the record.",
  altitude: {
    exec:
      "The 97 needs a footnote before it needs applause: the training data and the test may share source tickets, which would make part of that jump memorization. We're measuring the overlap and re-scoring on provably unseen cases this week — expect a good number, not a miracle. And we're making this structurally impossible going forward: every eval item tagged at birth, excluded from training by the pipeline itself. The engineer who caught it did the program a favor worth more than the thirteen points.",
    engineer:
      "Overlap detection: exact ID joins plus near-duplicate similarity (same ticket, reformatted) between golden set and tuning corpus. Re-measurement: uncontaminated-subset score + fresh post-period sample. Infrastructure: held-out registry with lineage tags at item creation, training-pipeline exclusion by ID at ingestion (rides the 057 indexing), contamination check as a publication gate on tuned-model evals.",
    frontier:
      "Contamination is the eval discipline's original sin and it never announces itself — shared pools, honest teams, missing registries. The transferable machinery: lineage-tagged held-out sets enforced in plumbing, near-dup detection before any tuned-model score publishes, and a culture that celebrates whoever un-discovers the miracle. Benchmark integrity is infrastructure plus messenger-safety, in that order — and both.",
  },
},

/* ============================================================ 087 */
{
  id: "087",
  title: "The Eval Bill Exceeds the Serving Bill",
  difficulty: "Medium",
  category: "Evals & Measurement",
  primaryLens: "Eval",
  secondaryLens: "Market",
  archetype: "Sweeper",
  secondaryArchetype: "Builder",
  targetRoles: ["MSFT MAI Evals Eng", "Anthropic TPM Safeguards & Evals", "OpenAI Deployment Eng"],
  tags: ["eval-cost", "sampling", "tiering", "budgets"],
  prompt:
    "The eval program built across 016–045 worked — too well, in one dimension: the customer's monthly eval spend (judge-model calls, regression suites on every behavior PR, weekly production sampling, red-team automation, depth-indexed long-session traces) just crossed $210k — exceeding the $180k serving bill that triggered 038's crisis. Finance flags it with the obvious question: 'You spend more checking the AI than running it?' The eval team's answer — 'quality has a price' — is true and about to lose the budget fight. The suites also have real waste: full regression on typo-level prompt changes, judge calls re-scoring unchanged behaviors, nightly red-team runs that haven't found a new attack class in a month. Right-size it without gutting it.",
  arc: {
    start: "An eval program that won on rigor and is about to lose on cost — defended with a slogan.",
    mid: "Apply 038's own discipline to the measurement stack: where do eval tokens go, and which ones buy risk reduction?",
    end: "A tiered eval portfolio priced by the risk it retires — defensible to finance because it speaks their language.",
  },
  expected: {
    bottleneck: "The eval program grew by accretion, never by portfolio design: every incident added a permanent suite (044's conversion rule, 045's gates, 041's meta-evals — all individually correct), nothing was ever tiered, sampled, or retired, and the program now runs everything at maximum frequency regardless of what each run could possibly catch — measurement without cost-consciousness, which is 038's disease relocated into the instrument (and 'quality has a price' is 028's unfalsifiable metric defense, budget edition).",
    failureMode: "Finance wins crudely: a flat 50% eval budget cut, applied by whoever's loudest rather than by risk (023's allocation-by-escalation, in reverse), gutting the cheap-but-critical (contamination gates, boundary audits) alongside the expensive-but-idle — and the next 015-class incident lands on a hollowed program, which then gets blamed for missing what it was defunded from watching.",
    nextMove: "Portfolio-manage the measurement like 038 managed serving: (1) instrument the eval spend itself — cost per suite per run, and each suite's catch rate (regressions caught, attacks found, drift detected — per dollar); the suites that haven't caught anything in months aren't necessarily waste (044's deterrence value), but they're candidates for frequency tiering; (2) tier by change-risk — full regression for model/behavior-class changes, smoke suites for typo-tier PRs (045's gate keeps its teeth, sized to the diff: a risk-classified trigger, not one-size-runs-all); (3) sample where volume is the cost — production monitoring drops from full-coverage judge calls to stratified sampling with drift-triggered escalation to full (016's weekly audit was always a sample; the automation quietly inflated it); (4) cache and dedup judge calls — unchanged behavior + unchanged judge version = replayable verdict (038's caching, for measurement); (5) retire and archive with 064's honors — suites whose failure class is now architecturally impossible (040's identity work made some 044 attacks structurally dead) go read-only; (6) present it to finance as risk-priced insurance — each tier's cost against the incident class it retires, which converts 'you spend more checking than running' into 'here's the premium schedule and what each layer insures.'",
    metric: "Catch-rate per dollar by suite (the portfolio's yield curve) and eval-spend as a ratio of serving spend with a governed target band; the proof of right-sizing: total spend down 40–50% with zero reduction in gate coverage on the risk classes that have ever fired.",
    owner: "The eval owner runs the portfolio review quarterly (017's refresh discipline, now pointed at cost); finance co-signs the tier structure (their veto converts to authorship — 054's move); each suite's original sponsor defends its tier or accepts its sampling; you own the insurance framing that survives the budget meeting.",
    falsifier: "If the spend instrumentation shows the costs are NOT in frequency waste — the big line items are irreducible (long-session depth traces and red-team generation genuinely dominate, each run catching real findings) — then the program is honestly expensive, the right-sizing yields 10% not 50%, and the true conversation is 038's CFO one: cost-per-incident-avoided against the customer's actual risk tolerance, which finance may legitimately set lower than the eval team wishes.",
  },
  modelAnswer:
    "The eval team is about to lose a fight it should win, because 'quality has a price' is a slogan and finance brought a spreadsheet. The honest embarrassment: the program preaching measurement discipline (016 through 045) never measured itself. It grew by accretion — every incident minted a permanent suite at maximum frequency, nothing was ever tiered or retired — and accretion without portfolio review is how insurance becomes hoarding. 038's diagnosis applies verbatim, one level up: an undifferentiated bill, blamed on 'the model' then, defended with 'quality' now, and in both cases the fix is the same — instrument where the money goes, then cut by evidence.\n\nBuild the yield curve: cost per suite per run, catch-rate per dollar. Then tier ruthlessly and honestly. Change-risk tiering for the gates: 045's suite keeps full teeth for behavior-class changes and drops to smoke for typo-tier diffs — the gate's legitimacy (024) depends on it being fast and proportionate, and running everything on everything is how gates get bypassed anyway. Sampling for volume: production monitoring returns to its 016 roots — stratified samples with drift-triggered escalation, not the full-coverage judge-call habit the automation quietly grew into. Caching for redundancy: unchanged behavior plus unchanged judge version is a replayable verdict, not a new bill. And retirement with 064's honors for suites whose failure class is architecturally dead — the 044 attacks that 040's identity intersection made structurally impossible deserve an archive, not a nightly run.\n\nThen the finance meeting, in their language: measurement is insurance, and insurance gets priced by the risk it retires. Present the tier structure as a premium schedule — this layer insures against 015-class incidents (annual cost X, incident cost 30X), this one against silent regressions (045's history of catches attached). Make finance co-author of the tiers (054's mechanism: their veto becomes their signature). The number that wins: spend down 40%, gate coverage on every risk class that has EVER fired — unchanged. And hold the falsifier without flinching: if the instrumentation shows the big lines are irreducible and productive, then the program is honestly expensive, and the real conversation is what risk tolerance the customer is buying — which is finance's call to make with open eyes, not the eval team's to make by slogan.",
  rubric: {
    diagnosis: "Names accretion-without-portfolio-review as the disease and 'quality has a price' as 028's unfalsifiable defense — the program failed its own discipline.",
    move: "Instrument eval spend, tier gates by change-risk, sample volume with drift escalation, cache verdicts, retire dead suites with honors, frame as risk-priced insurance.",
    measurement: "Catch-rate per dollar and spend-ratio band, with the proof being cost down and fired-risk coverage flat; falsifier concedes the honestly-expensive case to finance's risk tolerance.",
    synthesis: "Applies 038 to the instrument itself and 024's legitimacy law to gate sizing — the measurement stack governed by its own rules.",
    altitude: "Finance hears a premium schedule with authorship instead of a slogan with a deficit — the budget fight dissolves into tier design.",
    transfer: "Eval-cost engineering is the maturing lab discipline — tiered gating, sampled monitoring, verdict caching, and suite retirement are how measurement scales without eating the thing it measures.",
  },
  adversarial:
    "The slogan defense: 'you can't put a price on quality' — finance just did, it's $210k, and refusing the portfolio conversation guarantees the crude cut; rigor that won't account for itself loses to a spreadsheet every time. The pendulum failure: cutting by idleness alone — the red-team suite that hasn't found a new attack in a month may be deterring, and the contamination gate (086) fires rarely BECAUSE it exists; catch-rate needs a deterrence adjustment or you'll retire the locks for never being picked. The stealth-restore miss: right-sizing publicly then letting suites re-inflate by accretion again — without the quarterly portfolio review institutionalized, this exact meeting recurs in 18 months with worse credibility (017's rot, in budget form).",
  recursiveFollowup:
    "The tiering ships; spend drops 44%; finance signs the premium schedule. Four months later a regression slips through — a behavior change mis-classified as typo-tier by the diff heuristic, so only the smoke suite ran, and it missed what the full suite would have caught (the exact class 045's gate existed for). The incident is minor but the argument writes itself: 'the cost cut caused this.' Defend the tiering with its own math — expected-loss framing against four months of savings — and fix the classifier without refunding the whole portfolio design (024's override discipline, applied to your own risk model).",
  altitude: {
    exec:
      "Finance is right that the bill grew unexamined — we built each safeguard after an incident and never priced the portfolio. Here's the fix in your language: measurement as insurance, tiered by risk. Full checks where changes can hurt, samples where volume is the cost, retirement for risks we've engineered away. Spend drops forty percent; coverage on every risk that's ever actually fired stays at one hundred. And you co-own the premium schedule from now on.",
    engineer:
      "Eval-spend telemetry per suite per trigger; catch-rate ledger with deterrence annotations. Change-risk classifier on PRs driving gate tier (full/smoke); production judging to stratified sampling with drift-triggered full-coverage escalation; verdict cache keyed on behavior-hash × judge-version; suite lifecycle states (active/sampled/archived) with quarterly portfolio review.",
    frontier:
      "Measurement stacks obey the same economics as serving stacks: undifferentiated bills get defended with slogans and lose. The transferable craft — yield curves per suite, risk-tiered triggering, sampled volume, cached verdicts, honored retirement — is how eval programs survive their own success, and the insurance framing is how they survive their CFOs.",
  },
},

/* ============================================================ 088 */
{
  id: "088",
  title: "Grading Work That Takes All Day",
  difficulty: "Hard",
  category: "Evals & Measurement",
  primaryLens: "Eval",
  secondaryLens: "Architecture",
  archetype: "Builder",
  secondaryArchetype: "Maintainer",
  targetRoles: ["MSFT MAI Evals Eng", "Anthropic TPM Safeguards & Evals", "OpenAI FDE"],
  tags: ["long-horizon", "process-evals", "checkpoints", "agent-tasks"],
  prompt:
    "The claims-investigation agent (081's curated sessions, now working) processes cases that take 4–6 hours: dozens of retrievals, cross-referenced documents, tool calls into three systems, and a final determination with a written rationale. The eval program that graded 10-second support answers (016's golden sets, 041's judges) has nothing for this: end-to-end golden cases take a domain expert a full day to construct and verify, outcome-only grading ('was the determination correct?') passes investigations that got lucky and fails sound ones that hit ambiguous evidence, and by the time a bad pattern shows up in outcomes, the agent has run hundreds of cases. Sampling one case per week tells you almost nothing. Design evaluation for work measured in hours.",
  arc: {
    start: "An eval program built for answers, facing work — where outcomes lag, luck confounds, and golden cases cost a day each.",
    mid: "Grade the process, not just the verdict: checkpoint assertions, milestone rubrics, and outcome reconciliation at the end.",
    end: "Hours-long work evaluated in layers — cheap process checks at scale, expensive outcome truth where it earns its cost.",
  },
  expected: {
    bottleneck: "Outcome-only evaluation breaks on long-horizon work three ways at once: outcomes are slow (feedback arrives after hundreds of cases), confounded (a wrong determination can follow a sound process through genuinely ambiguous evidence — and a right one can follow a broken process by luck), and expensive to ground-truth (a day of expert time per golden case caps the set at useless sizes) — the program needs process-level evaluation, and nobody has defined what 'good investigating' looks like separably from 'right answer.'",
    failureMode: "Outcome-only grading ships anyway: the agent learns whatever survives determination-checking — including confident shortcuts through investigations (skipping the coverage-verification step that ambiguous cases need, because skipping is invisible in outcomes until the wrong case arrives 015-style); meanwhile the golden-case backlog grows at one expert-day each, the set stays tiny and stale (017 at construction prices), and quality problems surface as incidents with a hundred-case blast radius instead of as eval findings with none.",
    nextMove: "Layer the evaluation by cost and signal: (1) decompose the investigation into its process obligations — evidence coverage (did it retrieve and consider the required document classes for this case type?), constraint survival (081's metric: exclusions honored end-to-end), cross-referencing actually performed, rationale grounded in retrieved evidence (041's verification-augmented judging applies per-claim) — each checkable per-case, automatically, from 077's traces; (2) checkpoint rubrics at milestones — the natural stage boundaries (intake complete, evidence assembled, analysis drafted, determination) each get assertions cheap enough to run on EVERY case (076's boundary discipline, applied to time); (3) spend expert time where it compounds — instead of full golden cases, experts adjudicate DISAGREEMENTS: cases where process checks pass but outcomes look odd, or process flags fire on outcome-correct cases — each adjudication also becomes a labeled precedent (042's anchor set, grown from the interesting cases instead of constructed from scratch); (4) reconcile process against outcomes continuously — the process checks' validity is itself measurable: do process-flagged cases show worse eventual outcomes? (041's meta-eval, one level up — grade your process graders); (5) accept the honest limits — some determinations are only gradeable by time (appeals, audits), so wire those terminal signals back as the slow ground-truth layer (Gnomon's resolution discipline, applied to case outcomes).",
    metric: "Process-check coverage per case (every case graded on obligations, not one per week) and the process-outcome correlation (flagged cases must predict worse outcomes, or the process rubric is measuring compliance theater); expert time per labeled precedent — down from a day per golden case to minutes per adjudication.",
    owner: "The eval owner designs the obligation rubric WITH the senior claims experts (their tacit 'what sound investigation looks like' is the spec — 042's lesson: the standard lives in heads until anchored); the agent team exposes checkpoint events from 077's traces; the experts' new job is adjudicating disagreements, not constructing cases; the terminal outcome feed (appeals/audits) closes the slow loop.",
    falsifier: "If the process-outcome reconciliation shows near-zero correlation — cases failing process checks determine just as accurately as clean ones — then the obligations rubric encoded ritual rather than rigor (the checks measure what experts SAY matters, not what does), and the honest response is rebuilding the rubric from outcome-differentiated case pairs (what did sound-and-right investigations do that lucky-and-right ones didn't?) rather than defending checkpoint theater at scale.",
  },
  modelAnswer:
    "Name why the old program can't stretch: it grades answers, and this is work. Three breakages compound. Outcomes lag — by the time determinations prove wrong, hundreds of cases have run (the blast radius IS the argument for process evaluation). Outcomes confound — ambiguous evidence means sound investigations sometimes conclude wrong and sloppy ones sometimes luck into right; grade only verdicts and you TRAIN the shortcuts, because skipped verification is invisible until the case where it isn't (015's incident, incubating in the reward signal). And ground truth is priced in expert-days, which caps golden sets at sizes that measure nothing (017's coverage math, at construction cost).\n\nSo layer it. Bottom layer, every case, nearly free: process obligations checked from 077's traces — evidence coverage by case type (the required document classes were retrieved and considered), constraint survival end-to-end (081's metric graduating into the eval), cross-references actually executed, and rationale grounding verified claim-by-claim (041's judge, given retrieval access, grades 'is this rationale supported' far more validly than 'is this determination right'). Middle layer: checkpoint rubrics at the natural milestones — intake, evidence assembly, analysis, determination — cheap assertions at each boundary (076's discipline applied to time instead of agents). Top layer, expensive and precious: expert adjudication, spent ONLY on disagreements — process-clean cases with odd outcomes, process-flagged cases that concluded correctly. Each adjudication doubles as a labeled precedent, so the anchor set (042) grows from the genuinely interesting cases at minutes each instead of constructed goldens at a day each.\n\nThen grade the graders: process-outcome reconciliation, continuously. Flagged cases must predict worse terminal outcomes (appeals, audit reversals — the slow ground truth, wired back Gnomon-style) or the rubric has encoded ritual instead of rigor — experts' stated obligations aren't automatically the load-bearing ones, and the falsifier's rebuild path (mine outcome-differentiated case pairs for what sound-and-right did that lucky-and-right didn't) is the honest answer to that finding. The layered result: every case graded on process today, disagreements adjudicated this week, outcomes reconciled this quarter — evaluation operating at three speeds because the work does.",
  rubric: {
    diagnosis: "Names the three compounding breakages — lag, luck-confounding, and golden-case economics — and why outcome-only grading trains shortcuts.",
    move: "Three-layer design: automated process obligations from traces on every case, milestone checkpoints, expert time re-aimed at disagreement adjudication that mints precedents.",
    measurement: "Full process coverage with process-outcome correlation as the rubric's own validity check; expert-minutes per precedent as the economics proof.",
    synthesis: "Graduates 081/077/076's machinery into evaluation and grades the graders — 041's meta-eval discipline applied recursively.",
    altitude: "The program's story: every case evaluated today instead of one per week, with expert judgment spent where it compounds.",
    transfer: "Long-horizon evaluation is the frontier eval problem — process rubrics, checkpoint assertions, and adjudication-grown anchor sets are exactly where agent evals are heading at every lab.",
  },
  adversarial:
    "The outcome-purist failure: 'only determinations matter' — true for accountability, false for learning; by the time outcomes teach, the blast radius is a hundred cases, and the shortcuts outcomes can't see are compounding (the reward signal is training the agent you'll regret). The process-worship failure: grading obligations without ever reconciling against outcomes — you'll perfect compliance theater at scale, and the falsifier exists because expert-stated process is a hypothesis, not a truth. The golden-case grind: responding to the day-per-case economics by demanding budget for more expert days — adjudication-grown precedents beat constructed cases on cost AND realism (016's lesson: real cases over curated ones), and the construction habit is the old program's shape imposed on work it doesn't fit.",
  recursiveFollowup:
    "The layers ship. Reconciliation delivers an awkward finding: one process obligation — 'cross-reference the claimant's prior-claims history' — correlates NEGATIVELY with outcome quality on a case subclass: for first-time claimants with thin files, the cross-referencing step is where the agent picks up spurious pattern-matches ('similar name, similar claim') that bias determinations. The experts insist the step is non-negotiable ('basic diligence'); your data says it's hurting a measurable slice. The rubric is fighting its own reconciliation (042's precedent, meeting 041's validity). Resolve what 'sound process' means when the process measurably harms — and who gets to redefine diligence.",
  altitude: {
    exec:
      "Six-hour investigations can't be graded like ten-second answers: verdicts arrive too late, luck pollutes them, and expert-built test cases cost a day each. So we grade the work while it happens — did every case consider the required evidence, honor its constraints, ground its rationale — automatically, on all of them. Experts stop building test cases and start ruling on the interesting disagreements. And we continuously check that our process checks actually predict outcome quality — grading our own graders.",
    engineer:
      "Obligation rubric per case type compiled to trace assertions (077): evidence-class coverage, constraint survival (081's metric), executed cross-refs, per-claim rationale grounding via retrieval-backed judging (041). Milestone checkpoint assertions at stage boundaries. Disagreement queue for expert adjudication → labeled precedents into the anchor set. Terminal-outcome feed (appeals/audits) reconciled quarterly; process-outcome correlation as the rubric's validity SLO.",
    frontier:
      "Evaluating long-horizon agent work is the field's open problem, and the shape is settling: process obligations checked from traces at full coverage, expert judgment spent on adjudication rather than construction, and the meta-discipline of reconciling process rubrics against terminal outcomes so the checks themselves stay honest. The transferable law: when outcomes are slow, confounded, and expensive — grade the work, then grade your grading.",
  },
},

/* ============================================================ 089 */
{
  id: "089",
  title: "The Rubber-Stamp Reviewers",
  difficulty: "Medium",
  category: "Evals & Measurement",
  primaryLens: "Eval",
  secondaryLens: "Deployment",
  archetype: "Maintainer",
  secondaryArchetype: "Sweeper",
  targetRoles: ["MSFT MAI Evals Eng", "CAPE SCPM", "Anthropic TPM Safeguards & Evals"],
  tags: ["human-oversight", "review-quality", "automation-bias", "approval-gates"],
  prompt:
    "The human approval gates this bank keeps installing (010's draft rung, 060's send gates, 070's mandated review) have quietly rotted at a customer: telemetry on the procurement approval queue shows reviewers now approve 99.2% of agent drafts with a median review time of 4 seconds — down from 91% and 90 seconds at launch. One approver cleared 200 items in 19 minutes on a Friday. The agent's draft quality did improve (that's why the gate exists at rung two), but 4 seconds isn't review — it's a click with a conscience. The audit committee, reading 056's report, asks the question that unravels everything: 'If humans approve everything instantly, what exactly does human oversight mean here?' Answer it — with a design, not a policy memo.",
  arc: {
    start: "Oversight that has decayed into throughput — approval as a reflex, with the paper trail of diligence.",
    mid: "Accept automation bias as physics, then redesign review so attention lands where it matters and its quality is measured.",
    end: "Fewer, deeper reviews with teeth — calibrated sampling, seeded tests, and reviewer performance as a first-class metric.",
  },
  expected: {
    bottleneck: "The review system fights human nature and loses on schedule: when 99% of items are fine, sustained vigilance is psychologically impossible (automation bias isn't a character flaw — it's the documented response to reliable automation), and the gate's design — review everything, uniformly, forever — guarantees the decay while its telemetry (approval rate, review time) was never watched as the health metric it is; the oversight exists on paper exactly as 027's program existed on dashboards.",
    failureMode: "The gate stays as-is with a 'reviewer training refresh': vigilance recovers for three weeks and re-decays (the design is the problem, not the people), the audit committee's question gets a policy answer — and the first bad draft the rubber stamp waves through (010's $50k PO to 056's suspended vendor) lands with a paper trail proving a human 'reviewed' it in 4 seconds, which converts an agent error into an oversight scandal: the gate's existence becomes the liability.",
    nextMove: "Redesign for attention as the scarce resource it is: (1) triage what humans see — risk-scored routing (amount, vendor novelty, deviation from precedent, agent confidence) sends the routine 80% to sampled review and concentrates human attention on the genuinely reviewable 20% (010's ladder logic applied WITHIN the rung: earned autonomy for the boring classes); (2) measure review quality, not review throughput — seed the queue with known-bad drafts (canaries: synthetic errors of the classes that matter — wrong vendor, policy violation, 044's adversarial cases repurposed) and track catch rates per reviewer; a reviewer who misses canaries isn't reviewing, whatever their click count says; (3) make deep review structurally different from approval — the items routed to humans get a friction-appropriate interface (the diff against precedent highlighted, the risk factors named, an attestation that requires engaging with the specific flags — not a bare approve button); (4) close the loop on reviewer performance — catch rates and calibration feed back to reviewers (their own Gnomon), and chronic rubber-stamping routes to their manager as a capability gap, not a discipline case; (5) report the redesign to the audit committee in their language — 'oversight' redefined from 'a human clicked' to 'measured human catch-rate on seeded risks, concentrated where risk lives' — which is an answer that survives their follow-up.",
    metric: "Canary catch rate (the review system's true positive rate — the number that answers the committee) and attention concentration (median review time on the routed-to-human class, which should RISE as volume falls); approval rate on routine classes becomes irrelevant by design — that's what sampling is for.",
    owner: "The platform team owns risk routing and canary seeding; reviewers own their measured catch rates (with the framing that the redesign is FOR them — 200 items in 19 minutes was a system failing a person); the audit committee gets the seeded-test results as the standing oversight evidence; you own the redefinition of oversight before the incident defines it for everyone.",
    falsifier: "If canary seeding reveals catch rates are actually high — reviewers genuinely detect the seeded bad drafts in 4 seconds because the agent's errors, when they occur, are glaring — then the 4-second review is legitimately efficient pattern-matching, not rubber-stamping, the gate is healthier than its telemetry suggested, and the redesign narrows to keeping the canary system as permanent proof (the committee's question still deserved a measured answer; it just turns out to be a good one).",
  },
  modelAnswer:
    "Concede the physics first: the reviewers didn't fail the gate — the gate's design failed them, on schedule. When automation is right 99% of the time, sustained human vigilance is not a discipline problem, it's a documented impossibility (automation bias is what reliable systems DO to their overseers), and 'review everything uniformly forever' is a design that guarantees 4-second clicks while manufacturing a paper trail that says diligence. The audit committee's question is exactly right, and the answer must be a redesign, because the honest current answer is: oversight here means legal cover that won't survive its first test.\n\nRedesign around attention as the scarce input. Triage: risk-score the queue — amount, vendor novelty, deviation-from-precedent, agent confidence — and let the routine 80% flow to SAMPLED review while human attention concentrates on the reviewable 20% (this is 010's earn-autonomy logic applied inside the rung: the boring classes have earned it; the novel ones haven't). Fewer items, reviewed deeply, beats everything, reviewed nominally. Measure the review itself: seed known-bad drafts — canaries built from the error classes that matter (wrong-vendor, policy-violating, 044's adversarial repurposes) — and track catch rates per reviewer. This is the move that answers the committee: 'human oversight' stops meaning 'a click occurred' and starts meaning 'measured 94% catch rate on seeded risks.' Make the deep-review interface structurally un-stampable: diffs against precedent highlighted, risk flags named, attestation that engages the specific flags — friction proportional to stakes (the approve button's frictionlessness was a design choice too; it chose throughput).\n\nClose the loop humanely: catch rates feed back to reviewers as their own calibration (a personal Gnomon), and chronic misses route as capability gaps, not discipline cases — the person who cleared 200 items in 19 minutes was set up by a queue that made that possible and a metric that made it look like productivity. And run the falsifier honestly: seed the canaries BEFORE redesigning everything — if 4-second reviews catch the seeded errors (glaring failures, efficient pattern-matching), the gate was healthier than its telemetry looked, and what the committee needs is the canary system as permanent proof rather than a rebuilt queue. Either way, the standing answer to 'what does oversight mean' becomes measurable: catch rate on seeded risk, attention where risk lives — which is the only definition that survives both the audit and the incident.",
  rubric: {
    diagnosis: "Names automation bias as design physics rather than reviewer failure, and the uniform-review gate as manufacturing decayed oversight with a diligence paper trail.",
    move: "Risk-triaged routing with sampled routine flow, canary seeding with per-reviewer catch rates, un-stampable deep-review interfaces, humane performance loops.",
    measurement: "Canary catch rate as oversight's true metric and rising review-depth on routed items; falsifier lets efficient pattern-matching vindicate the 4-second review.",
    synthesis: "Applies 010's earned-autonomy logic within the rung and converts the committee's philosophical question into a measured, standing answer.",
    altitude: "The audit committee hears oversight redefined as evidence — seeded-test catch rates — which survives follow-ups the policy memo wouldn't.",
    transfer: "Human oversight quality is the safeguards question behind every approval gate — EU AI Act's 'functioning oversight' (058) and every lab's HITL claims need exactly this machinery to mean anything.",
  },
  adversarial:
    "The training-refresh failure: re-briefing reviewers on diligence — vigilance recovers for weeks and re-decays because the design didn't change; you've treated physics as morale (and 027's lesson applies: the system produced the behavior). The friction-everywhere failure: making ALL approvals slow and effortful — the routine 80% doesn't deserve it, throughput legitimately matters, and universal friction teaches workarounds (024's bypass culture at the approval layer). The surveillance miss: deploying canaries and catch rates as gotcha discipline — reviewers who feel policed will game the canaries (they'll pattern-match the synthetic style — 041's judge-gaming, by humans), and the honest framing is the system's health check, not the person's trap; measurement that punishes gets gamed, in humans exactly as in models.",
  recursiveFollowup:
    "The redesign ships; catch rates run 91% on canaries. Then a real bad draft — a policy-violating contract clause the agent generated for a routed-to-SAMPLED routine vendor — slips through unsampled and executes (083's ledger catches it downstream, three days later). The blast radius is small but the audit committee's follow-up is sharp: 'Your risk scoring decided this one didn't need human eyes. Who reviews the router?' The oversight question has moved one level up — the triage model is now the overseer (041's judge-validity, aimed at your risk scorer). Design ITS oversight, and decide whether it ever ends.",
  altitude: {
    exec:
      "Four-second approvals aren't oversight — they're what any human becomes when a queue is right ninety-nine percent of the time. The redesign: routine items get sampled, human attention concentrates on the genuinely risky twenty percent, and we SEED the queue with known-bad drafts so oversight has a measured catch rate instead of a click count. Your question gets a number: reviewers catch 9 in 10 seeded risks — and we watch that number the way we watch the agent's.",
    engineer:
      "Risk router on the approval queue: amount, vendor novelty, precedent deviation, agent confidence → deep-review vs sampled lanes. Canary pipeline: synthetic bad drafts from the taxonomy's error classes (044's cases reused), injection-blind, per-reviewer catch tracking. Deep-review UI: precedent diff, named flags, flag-engaged attestation. Reviewer calibration feedback loop; router performance itself audited quarterly.",
    frontier:
      "Human-in-the-loop decays on contact with reliable automation — that's physics, and gates designed against it are theater with a paper trail. The transferable machinery: attention triage, seeded ground truth for catch-rate measurement, friction proportional to stakes, and oversight of the triage itself. 'A human reviewed it' means nothing; 'humans catch 91% of seeded risks where risk actually lives' is an answer — and every serious oversight regime is converging on having one.",
  },
},

/* ============================================================ 090 */
{
  id: "090",
  title: "The Re-Org Mid-Rollout",
  difficulty: "Medium",
  category: "Deployment & Change Management",
  primaryLens: "Deployment",
  secondaryLens: "Customer",
  archetype: "Maintainer",
  secondaryArchetype: "Grower",
  targetRoles: ["CAPE SCPM", "OpenAI Deployment Eng", "MSFT MAI Strategy & Ops"],
  tags: ["reorg", "continuity", "sponsorship", "re-planning"],
  prompt:
    "Ring 2 of the insurer rollout (019's plan, working: 3,000 seats live, gates passing) collides with a corporate earthquake: the customer announces a full restructure — the sponsoring CIO moves to a board role, three of five divisions merge into two, the champion network's careful per-50-seat coverage (061) now maps to teams that won't exist in eight weeks, and the works-council agreements (019's longest pole) were negotiated per-division for divisions that are dissolving. The new COO's transformation office emails: 'All in-flight programs pause pending strategic review. Submit a one-page justification.' You have one page, eight weeks of organizational chaos, and 3,000 users who didn't stop needing the tools. Navigate it.",
  arc: {
    start: "A working rollout whose entire scaffolding — sponsor, rings, champions, legal agreements — just lost its org chart.",
    mid: "Protect the live base, re-map the scaffolding to the new structure, and convert the strategic review into the program's re-founding.",
    end: "The rollout re-anchored to the new organization — smaller promises, surviving value, and a transformation office that owns it.",
  },
  expected: {
    bottleneck: "The rollout's every dependency was expressed in the old org's coordinates — sponsor authority, ring boundaries, champion coverage, and works-council agreements all reference dissolving structures — and the program's continuity now depends on rapid re-mapping plus surviving a strategic review run by people who inherited it without context (018's ownership vacuum, about to be created at program scale by structural change rather than neglect).",
    failureMode: "The pause becomes the program: the one-pager reads as a defense of the old plan (rings and dates that reference dead divisions — instantly stale, easily cut), the champion network dissolves with its teams while nobody re-recruits, works-council coverage silently lapses as divisions merge (creating compliance exposure on the LIVE 3,000 — 019's legal pole, now unmoored), and by the time the strategic review concludes, adoption has decayed (065's physics, unmanaged), the value evidence has gone stale, and the new COO cuts a program that looks like the old regime's pet project — 018's purgatory, entered at 3,000 seats.",
    nextMove: "Triage in dependency order: (1) protect the live base first — the 3,000 users' service, support (063's desk), and works-council compliance can't pause even if expansion does; get legal's read on agreement continuity across the merger THIS week (agreements referencing dissolved divisions may need interim letters — silent lapse is the one unrecoverable failure); (2) write the one-pager for the NEW org, not the old program — lead with measured value from live rings (the 019 gate evidence, 043's honest attribution), map what the program does for the transformation's own goals (mergers need exactly what agents do: knowledge continuity across combined teams, workflow harmonization — the restructure is a USE CASE, not just a threat), and offer the review a decision with options (033's escalation craft: expand/hold/descope — never 'please don't cut us'); (3) re-map the scaffolding — champions re-inventoried against the new structure (061's coverage metric re-run; the merged divisions need re-recruitment, and champions from dissolved teams are flight risks AND the new teams' seed crystals), rings redrawn along the two new divisions (019's gates keep their thresholds; only the boundaries move); (4) hunt the new sponsor now — the departing CIO's board seat is a resource (a warm intro to whoever inherits, plus board-level air cover — 029's succession play, compressed), and the transformation office itself is the highest-leverage sponsor candidate: programs that report INTO the strategic review's owner don't get cut by it; (5) re-baseline the promises — the old dates died with the old org chart; new commitments sized to eight weeks of chaos (034's honest-number discipline applied to your own roadmap).",
    metric: "Live-base health through the transition (usage, support SLA, works-council compliance — the numbers that must not dip while everything else re-plans) and time-to-new-sponsor; the one-pager's success measure is binary and immediate: does the program exit the review with an owner in the new structure?",
    owner: "You own the triage and the one-pager's altitude; legal owns the works-council continuity read; the surviving champions own keeping their (new) teams warm; the transformation office is the target owner — the pitch's whole design is making them WANT it (054's authorship move, at program-survival stakes).",
    falsifier: "If the strategic review's real agenda surfaces as cost-cutting with predetermined conclusions — the one-pager is theater and the program is on a list — then re-founding effort is misallocated: the play becomes 018's kill-option honesty (protect the live base as an operational service too boring to cut, bank the value evidence and champion relationships for the restart, and let the expansion die cleanly rather than expensively), because programs that fight predetermined cuts spend their credibility losing.",
  },
  modelAnswer:
    "Sequence by what can't wait, because the eight weeks will spend themselves on whatever screams loudest. The silent scream is legal: works-council agreements negotiated per-division, for divisions dissolving, covering 3,000 LIVE users — if coverage lapses in the merger, the program has a compliance incident while paused, which is the one failure no review survives. Legal's continuity read happens this week; interim letters if needed. The live base's service, support, and adoption also don't pause — 065 taught you decay physics; eight unmanaged weeks is a plateau with a cliff.\n\nThen the one-pager — and write it for the new organization, not in defense of the old plan. The instinct under review pressure is to justify what was (rings, dates, the old CIO's vision — all coordinates of a dead map, instantly stale). Instead: measured value from live rings (019's gate evidence, attributed with 043's honesty), then the reframe that changes the meeting — the restructure is a use case. Mergers need knowledge continuity across combined teams, workflow harmonization between merging divisions, and onboarding at scale: that's the agent fleet's literal job description. 'This program is transformation infrastructure' is a sentence the transformation office can own; 'please don't cut our rollout' is a sentence they can only judge. Offer options, not pleas (033's craft): expand into the merger, hold at live rings, or descope — each priced.\n\nRe-map the scaffolding in parallel: champions re-inventoried against the new structure — 061's coverage math re-runs, dissolved-team champions are simultaneously flight risks and the merged teams' seed crystals, so re-recruit THIS month; rings redraw along the two new divisions with 019's gate thresholds intact (the discipline survives; only boundaries move). And hunt the sponsor like it's the whole game, because it is (018): the departing CIO's board seat is an asset — a warm handoff plus air cover — but the structural answer is making the transformation office itself the owner: programs reporting into the strategic review's author don't get cut by it (054's mechanism at survival stakes). Re-baseline every promise to the new reality — old dates died with the org chart, and 034 taught you: the honest smaller number, migrated deliberately, beats the inherited fiction. And hold the falsifier coldly: if the review is predetermined cost theater, stop investing in persuasion — make the live base a boring operational service, bank the evidence and the champions, and let expansion die cheap for the restart that follows every restructure.",
  rubric: {
    diagnosis: "Triages dependencies by irreversibility — works-council continuity and live-base health before persuasion — and names the coordinates problem: every plan artifact references a dissolving structure.",
    move: "One-pager reframed as transformation infrastructure with priced options, scaffolding re-mapped (champions, rings, sponsor), transformation office targeted as owner.",
    measurement: "Live-base health through transition and binary review-exit-with-owner; falsifier redirects effort to graceful descope when the review is predetermined.",
    synthesis: "Converts the threat into the use case — mergers need exactly what agents do — and reuses the whole playbook (018, 029, 033, 054, 061, 065) under time pressure.",
    altitude: "The transformation office reads ownership, not pleading; legal reads urgency where it's real; the champions read that someone is steering.",
    transfer: "Org-change resilience is deployment craft at every scale — programs anchored to structures die with them; programs anchored to measured value and re-mappable scaffolding survive the earthquake.",
  },
  adversarial:
    "The defense-brief failure: a one-pager justifying the OLD plan — rings and dates referencing dead divisions read as the old regime's homework, and reviews cut homework; the new org owes your past plan nothing. The everything-pauses failure: honoring the pause literally, including support and champion care — the live base decays on schedule (065), the works-council lapse ripens silently, and the program you're defending stops existing before the review concludes. The sponsor-nostalgia miss: spending the eight weeks trying to keep the departing CIO engaged — a board seat is air cover, not ownership (029's lesson: sponsorship is a role in the current structure, and the current structure is the transformation office, like it or not).",
  recursiveFollowup:
    "The play works: the transformation office adopts the program as merger infrastructure, expansion re-scopes to the two new divisions. Then the price of the new sponsor surfaces — the COO's office wants the agent telemetry (adoption, usage patterns, per-team activity) as INPUT to the restructure's next phase: identifying 'consolidation opportunities' — which the workforce will read, correctly, as layoff analytics. The champion network hears about it first (061's sensors work both ways). The program's survival tool is becoming a surveillance tool (082's landmine, at existential stakes). Draw the line — what the deployment's data serves, what it refuses, and what you tell the transformation office that adopted you.",
  altitude: {
    exec:
      "One page, for the new organization: the live rings return measured value today — here's the number — and the merger you're running is this program's strongest use case: knowledge continuity across combined teams, harmonized workflows, onboarding at scale. Three options, priced: expand into the merger, hold at current rings, or descope. What it needs from the review is an owner in the new structure — and it's built to be yours.",
    engineer:
      "Continuity triage: works-council agreement mapping to successor entities (legal, this week), support and SLA unbroken for the live base, champion re-inventory against the new org with re-recruitment for merged teams, ring boundaries redrawn to the two divisions with existing gate thresholds. Freeze expansion dependencies; keep 065's segment telemetry running through the chaos — it's the evidence for the other side.",
    frontier:
      "Re-orgs are the deployment stress test: every program dependency expressed in org-chart coordinates fails when the chart does. The transferable design — anchor to measured value not structures, keep scaffolding re-mappable (champions, rings, agreements), and make the disrupting force the new owner — is how programs survive their sponsors, their divisions, and eventually their companies.",
  },
},

);
