/* Parabolic 100 — problem bank, part 17 (Market & Capital Calibration, 091–095) */

P100.PROBLEMS.push(

/* ============================================================ 091 */
{
  id: "091",
  title: "The Open-Weights Question",
  difficulty: "Medium",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Architecture",
  archetype: "Sweeper",
  secondaryArchetype: "Builder",
  targetRoles: ["CAPE SCPM", "Anthropic TPM Cloud Inference", "OpenAI Deployment Eng"],
  tags: ["open-weights", "self-hosting", "tco", "sovereignty"],
  prompt:
    "A customer's CIO returns from a conference with conviction: 'Open-weight models are 90% as good at 10% of the cost — we should self-host and stop paying API premiums.' His board deck is half-written. The numbers he saw are real benchmark deltas and real per-token price gaps. What the deck doesn't contain: his organization has never run a GPU cluster, the 38-problem cost work showed their spend is context-shaped not model-shaped, their workloads span 039's whole portfolio, and 'the model' is maybe a fifth of what their API price actually buys. Give him the calibrated read before the board does it for him.",
  arc: {
    start: "A real price gap, a half-written board deck, and a TCO model missing four-fifths of the costs.",
    mid: "Decompose what the API premium buys; price self-hosting honestly; find the workloads where open weights genuinely win.",
    end: "A portfolio answer with dated markers — self-host where it's true, buy where it's true, and a CIO whose deck survived contact.",
  },
  expected: {
    bottleneck: "The comparison prices tokens when the decision is about capabilities-plus-operations: the API price bundles serving engineering (048's latency work, 078's failure postures), model upgrades arriving free (074's transitions), capacity elasticity (023's problem, made someone else's), and safety/eval infrastructure — while the self-host price excludes the GPU cluster ops the org has never done, utilization risk (their spiky enterprise load vs a cluster priced for constant use), and the talent premium of the two SRE hires who can babysit inference at 3am.",
    failureMode: "The deck ships as-is: the board approves 'AI cost reduction,' procurement buys a GPU commitment sized to peak load, utilization runs 20% (enterprise workloads are spiky — the cluster idles nights and weekends at full depreciation), the 90%-as-good benchmark delta turns out to live exactly in the 10% their hardest workloads need (039's routing knew this), and eighteen months later the 'savings' program has spent more than the API ever did — with the CIO's credibility amortizing alongside the idle H100s.",
    nextMove: "Reframe from either/or to portfolio-with-markers: (1) decompose the API premium honestly — model access, serving engineering, elastic capacity, continuous upgrades, safety infrastructure — and price each for self-hosting (the 10% price becomes 40–70% TCO once ops, utilization risk, and talent land, varying by workload shape); (2) route by workload, not ideology — 039's tiering already knows which workloads are latency-tolerant, quality-tolerant, and volume-heavy: high-volume stable-shape workloads (batch summarization, classification) are genuine open-weight candidates; frontier-quality and spiky workloads stay bought; (3) run the falsifiable pilot — one workload class, self-hosted, with pre-registered TCO accounting (055's kill criteria: all-in cost per task including ops time, quality via existing evals, utilization actuals) against the API baseline for one quarter; (4) date the markers — open-weight capability gaps close on a public trajectory; set review points ('if open models clear our eval bar for workload X by Q3, migrate it') so the strategy updates on evidence instead of conferences; (5) hand the CIO a better board story than savings — optionality: a portfolio that can shift between bought and hosted as prices and capabilities move is leverage against every vendor including yours (069's honest posture, from the customer side).",
    metric: "All-in cost per completed task by workload class (the only number that compares fairly — 038's unit, extended with ops labor and utilization-adjusted depreciation) and the pilot's pre-registered quality bar on existing evals; the board metric: portfolio share by tier with dated review triggers.",
    owner: "The CIO owns the board narrative (upgraded from savings to optionality — he keeps the win); infrastructure prices the ops reality honestly (their 'we can run it' enthusiasm gets the 3am question); the eval program (016/041) referees quality claims; you own the decomposition and the markers.",
    falsifier: "If the pilot's all-in numbers actually deliver — utilization holds because their batch workloads genuinely run 24/7, ops burden lands lighter than priced, and quality clears the bar — then the conference pitch was right for a real slice of the portfolio, the migration expands on evidence, and the calibrated read becomes 'faster than we thought' — which the markers were designed to catch early.",
  },
  modelAnswer:
    "Start by honoring what's true: the benchmark deltas are real, the per-token gap is real, and open-weight capability is on a genuine trajectory — the CIO isn't wrong about the direction, he's mispricing the decision. The conference compared tokens; the decision is about everything the token price bundles. Decompose the premium: serving engineering (the 048 latency work someone else does), elastic capacity (023's nightmare, outsourced), continuous model upgrades (074's transitions, managed), safety and eval infrastructure, and the 3am pager. Self-hosting doesn't delete those costs — it repatriates them to an org that has never run a GPU cluster, and the honest TCO lands at 40–70% of API cost for suitable workloads, not 10%. The deadliest line item is utilization: enterprise load is spiky, clusters depreciate at 100% while running at 20%, and idle H100s are the most expensive way ever invented to feel sovereign.\n\nThen route instead of choosing: 039's portfolio already classified the workloads. High-volume, stable-shape, quality-tolerant classes — batch summarization, classification, the document pipelines — are genuine open-weight candidates where volume can actually feed a cluster. Frontier-quality reasoning and spiky interactive loads stay bought. That's not hedging; it's the same tiering logic that already routes across bought models, extended one tier down. Prove it with a falsifiable pilot: one workload class, one quarter, pre-registered TCO accounting (all-in: ops hours, utilization actuals, 038's cost-per-task unit) against the API baseline, quality refereed by the existing evals — 055's discipline pointed at infrastructure. And date the markers: open-weight capability closes gaps on a public cadence, so the strategy carries review triggers ('workload X migrates when open models clear its eval bar') instead of re-litigating at every conference.\n\nHand the CIO the upgrade his deck actually needs: the board story isn't savings, it's optionality — a portfolio that can shift between bought and hosted as prices and capabilities move is negotiating leverage against every vendor, including the one you work for (069's honesty, mirrored). 'We routed 30% of volume to self-hosted open weights, we verify quality continuously, and our contracts price in our ability to move' beats '90% at 10%' in front of any board that asks a second question — and boards always ask a second question.",
  rubric: {
    diagnosis: "Decomposes the API premium into its bundled services and names utilization risk as the TCO killer the conference math omitted.",
    move: "Portfolio routing by workload shape, a pre-registered TCO+quality pilot, dated capability markers, and the board story upgraded from savings to optionality.",
    measurement: "All-in cost per completed task with utilization-adjusted depreciation, quality on existing evals; falsifier lets the pilot vindicate migration faster than priced.",
    synthesis: "Extends 039's tiering down a tier and mirrors 069's honesty from the customer side — optionality as leverage, not ideology.",
    altitude: "The CIO keeps his win with a deck that survives the second board question; infrastructure gets the 3am question before the purchase order.",
    transfer: "Build-vs-buy at the model layer is the industry's standing capital question — TCO decomposition, utilization math, and dated capability markers are the calibrated read every lab's enterprise team gives weekly.",
  },
  adversarial:
    "The vendor-defense failure: leading with open-weight quality FUD — the deltas are real and shrinking, the CIO has the benchmarks, and defending the premium by dismissing the trajectory costs you the credibility to price it honestly; you sell the bundle, so price the bundle. The sovereignty-romance failure: blessing full self-hosting because 'control matters' — control of an idle cluster at 20% utilization is a luxury the CFO will eventually name; sovereignty needs the same falsifiable accounting as savings. The pilot-rigging miss: letting infrastructure run the pilot on their easiest workload with enthusiasm-adjusted ops accounting — 055's pre-registration exists exactly because pilots designed by their advocates succeed by construction; the kill criteria get signed before the cluster boots.",
  recursiveFollowup:
    "The pilot runs honest: batch workloads migrate at 55% all-in savings, quality holds. Then the open-weight model powering them gets its license terms changed by its publisher — new restrictions on commercial serving, effective in 90 days, exactly the 074 behavioral-contract problem except the counterparty owes you nothing at all. Legal asks what the portfolio's exposure is; the CIO asks why nobody priced license risk. Answer both — and add the marker the strategy was missing.",
  altitude: {
    exec:
      "The numbers you saw are real — and they price a fifth of the decision. The API premium buys serving engineering, elastic capacity, free upgrades, and someone else's 3am pager; self-hosting repatriates all of it to a team that's never run a cluster, at utilization rates that make idle GPUs your most expensive line item. Here's the version that survives the board: route the high-volume batch work to open weights behind a one-quarter pilot with signed kill criteria, keep frontier work bought, and put dated triggers on every migration. The story isn't savings — it's optionality, and it's leverage on every vendor you have. Including us.",
    engineer:
      "Pilot spec: one workload class, all-in TCO ledger (GPU depreciation at ACTUAL utilization, ops hours logged, power/hosting, talent allocation), quality via the existing eval suites (016's sampling, 041's judges), latency SLOs from 048's budgets. Pre-registered thresholds signed before hardware. Portfolio triggers: per-workload eval bars that open models must clear, reviewed quarterly against public releases.",
    frontier:
      "The open-weights question is the era's standing TCO decomposition: token prices versus bundled operations, utilization risk versus sovereignty value, capability trajectories versus switching costs. The transferable read — route by workload shape, pilot with pre-registered accounting, date the capability markers, and sell optionality rather than either ideology — is what calibrated looks like when both answers are partly right and the mix shifts quarterly.",
  },
},

/* ============================================================ 092 */
{
  id: "092",
  title: "The Three-Year Contract in a Six-Month Market",
  difficulty: "Medium",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Platform",
  archetype: "Sweeper",
  secondaryArchetype: "Grower",
  targetRoles: ["CAPE SCPM", "Anthropic TPM Cloud Inference", "MSFT MAI Strategy & Ops"],
  tags: ["contracts", "price-trajectory", "commitments", "forecasting"],
  prompt:
    "Renewal season: the customer's procurement team has two offers on the table for their now-substantial AI spend ($4M/year run rate). Option A: annual contract at list-minus-15%. Option B: three-year commitment at list-minus-40%, locked unit rates. Procurement loves B — 'guaranteed 40% savings.' The CFO, sharper, asks you the actual question: 'Inference prices dropped something like 10x over the last two years. If that continues, locked rates are a liability, not a discount. Will it continue?' You cannot know. You CAN be calibrated. Structure the answer — and the contract.",
  arc: {
    start: "A guaranteed-savings story colliding with a price curve that makes guarantees cut both ways.",
    mid: "Forecast with explicit uncertainty, decompose what drives the curve — then structure the contract to win across scenarios.",
    end: "A commitment shaped like the uncertainty: shorter locks, price-benchmark clauses, and dated markers the CFO reviews with you.",
  },
  expected: {
    bottleneck: "The decision requires a price forecast nobody can make precisely, and the room is polarizing into false certainties (procurement's 'locked savings' vs the CFO's 'prices always fall') — when the calibrated move is decomposing WHAT drives inference pricing (hardware generations, serving efficiency gains, competition intensity, demand growth soaking up supply), attaching honest probability ranges to trajectories, and then — the actual skill — structuring the contract so it performs acceptably across the range instead of betting the spend on one scenario.",
    failureMode: "Procurement's certainty wins: the three-year lock signs, prices drop another 60% over eighteen months (efficiency gains plus competition — the historical base rate), the locked 'discount' becomes a 30% premium over street price by year two, the CFO's question is remembered by everyone including the CFO — and the next renewal happens in an atmosphere where every vendor claim is treated as the last one; or the CFO's certainty wins, everything stays annual, a genuine supply crunch (023's quarter, market-wide) spikes spot pricing, and the unhedged spend eats it.",
    nextMove: "Answer in calibrated structure, not point forecasts: (1) decompose the price drivers for the CFO — hardware cost-per-FLOP (falling on a public curve), serving efficiency (038's levers, industrializing everywhere — batching, caching, distillation), competition (labs and clouds pricing against each other), AND the counterweight (demand growth absorbing supply, capability premiums on frontier tiers — the drops concentrate in commodity tiers while frontier holds); (2) give ranges with reasoning, not predictions — 'commodity-tier prices: 40–70% lower in two years, high confidence; frontier-tier: 0–30%, low confidence; a supply-crunch spike scenario: real but bounded' — the honesty IS the credibility (025's discipline, applied to procurement); (3) structure for the range — a shorter lock (12–18 months) at the deepest available discount, a price-benchmark clause (rates re-open if published list prices fall >X%, or most-favored-customer language), volume commitment WITHOUT unit-rate lock (commit the spend, float the rate — vendors value the commitment more than the lock), and tier-split terms (lock commodity workloads where drops are likely priced in, keep frontier flexible where capability churn dominates); (4) install the markers — quarterly price-review dates with named indicators (published list prices, spot-market equivalents, the customer's own cost-per-task from 038's telemetry) so the contract's performance is measured against reality on a schedule, Gnomon-style, instead of discovered at renewal.",
    metric: "Contract performance vs street price, reviewed quarterly against the named indicators — the ex-ante deliverable is the CFO's dated marker sheet; the ex-post proof is effective-rate-paid vs the counterfactual options, computed honestly at each review (including when the structure loses a quarter — calibration means reporting misses).",
    owner: "The CFO owns the risk posture (the ranges let them choose it consciously); procurement owns negotiating the structure (benchmark clauses and float-rate commitments are their craft once armed); you own the decomposition, the ranges, and showing up at the quarterly reviews with the marker sheet — especially the quarters you were wrong.",
    falsifier: "If the vendor refuses all structure — no benchmark clauses, no tier splits, lock-or-list only — then the market is telling you something about THEIR forecast (vendors decline price-protection clauses when they expect prices to fall), which is itself decision-grade information: take the annual, bank the signal, and tell the CFO why the refusal was the answer.",
  },
  modelAnswer:
    "The CFO asked a forecasting question; answer with calibrated structure, because point predictions here are cosplay. First decompose what actually drives the curve, so the ranges have reasons: hardware cost-per-compute falls on a public cadence (new silicon generations, memory bandwidth per dollar); serving efficiency industrializes (the 038 levers — batching, caching, distillation — are being turned everywhere at once, and they compound); competition prices aggressively in commodity tiers. Against that: demand grows into supply (023's crunch was real), and capability premiums persist — the 10x drops concentrated in commodity tiers while frontier pricing held. So the honest ranges: commodity-tier, 40–70% lower in two years, high confidence; frontier-tier, 0–30%, low confidence; a bounded supply-spike scenario worth hedging. Delivered with reasoning, ranges beat certainty for credibility with any CFO worth the title — 025 taught this account that falsifiable beats confident.\n\nThen the actual craft: structure the contract to perform across the range rather than betting $12M on one scenario. Shorter lock — 12–18 months captures most of the discount depth at a fraction of the trajectory risk. Benchmark clause — rates re-open if published list prices fall past a threshold; vendors resist it, which is itself information (a vendor confident prices will hold doesn't fear the clause). Commit volume, float rates — the vendor's economics want your committed spend far more than your locked unit price; trade the thing they value for the flexibility you need. Tier-split the terms — lock the commodity workloads where the drop is largely priced into the discount already; keep frontier flexible where capability churn (074's transitions) dominates price anyway.\n\nInstall the Gnomon machinery: quarterly reviews with named indicators — published list prices, the customer's own cost-per-task telemetry — and show up to them, especially the quarters the structure underperforms, because reporting your own misses is what makes the next forecast worth hearing. And read the falsifier in the room: if the vendor refuses every structural term, they've told you their forecast — vendors decline price protection when they expect to be cheaper than the lock. Take the annual, and tell the CFO the refusal was the data.",
  rubric: {
    diagnosis: "Refuses both false certainties and decomposes the price drivers — hardware, efficiency, competition, demand — into reasoned ranges by tier.",
    move: "Contract structured for the range: short lock, benchmark clauses, volume-not-rate commitment, tier-split terms, quarterly marker reviews.",
    measurement: "Effective-rate vs counterfactual at dated reviews with misses reported; falsifier reads vendor refusal of structure as their forecast leaking.",
    synthesis: "Sees that the vendor values committed volume over locked rates — the trade that gets flexibility free — and that clause-resistance is information.",
    altitude: "The CFO gets risk posture as a conscious choice with ranges and reasons; procurement gets negotiating structure instead of a savings slogan.",
    transfer: "Commitment structuring under price-trajectory uncertainty is the enterprise-AI procurement question — and the lab-side mirror (what commitments to offer, what clauses to resist) is the same calibration from the other chair.",
  },
  adversarial:
    "The savings-slogan failure: letting 'guaranteed 40%' close the deal — guarantees against a falling curve are premiums with better marketing, and the CFO already said so out loud; ignoring the sharpest person in the room is a career choice. The trajectory-worship failure: 'prices always fall, stay annual' — 023 happened; supply crunches are real, bounded, and exactly what commitment hedges exist for; calibration means pricing BOTH tails. The forecast-theater miss: delivering ranges without the contract structure — a CFO can't sign a probability distribution; the ranges only matter because they shape clauses, locks, and splits, and stopping at the forecast is punditry with confidence intervals (025's punditry critique, formalized).",
  recursiveFollowup:
    "The structured deal signs: 15-month lock, benchmark clause at 20%, commodity/frontier split. Month seven: a new entrant posts commodity-tier prices 45% below your locked rate — but their capacity is unproven, their SLAs are aspirational, and 094's vendor-viability questions all apply. Procurement invokes the benchmark clause and wants to also MOVE the volume. The clause covered price; nobody wrote the switching-risk half. Run the decision — and note what the marker sheet should have tracked besides price.",
  altitude: {
    exec:
      "Honest answer: commodity AI prices very likely keep falling — hardware, efficiency, and competition all push that way — while frontier-tier pricing is stickier and a supply squeeze is a real, bounded risk. So we don't bet three years on either story: shorter lock at nearly the same discount, a clause that reopens rates if list prices fall past twenty percent, spend committed but rates floating, and a quarterly review where I show you the indicators — including the quarters I'm wrong.",
    engineer:
      "Contract instrumentation: quarterly effective-rate-per-task from the 038 telemetry vs published list and spot equivalents; benchmark-clause trigger monitoring; tier-tagged spend so commodity/frontier terms reconcile separately. Marker sheet: named indicators, review dates, and a running forecast-vs-actual ledger — the procurement Gnomon.",
    frontier:
      "Pricing-trajectory bets are where market calibration earns money: decompose the drivers, range the scenarios by tier, structure agreements to perform across the range, and grade yourself on dated markers. The transferable insight: in fast-falling markets, vendors trade rate flexibility for volume commitment cheaply — and their resistance to price-protection clauses is the closest thing to their internal forecast you'll ever see.",
  },
},

/* ============================================================ 093 */
{
  id: "093",
  title: "Should We Train Our Own Model?",
  difficulty: "Medium",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Customer",
  archetype: "Sweeper",
  secondaryArchetype: "Prototyper",
  targetRoles: ["CAPE SCPM", "MSFT MAI Strategy & Ops", "OpenAI FDE"],
  tags: ["build-vs-buy", "foundation-models", "moats", "capital"],
  prompt:
    "The board of a global insurer (019's customer, transformed and confident) has a new strategy paper circulating: 'Insurance Foundation Model' — train a proprietary model on 30 years of claims, underwriting, and actuarial data, because 'our data is our moat and we're handing it to vendors.' A consultancy has scoped it: $180M over three years, a 40-person lab, 'strategic AI independence.' The CEO asks you — the vendor's person, they know — for your honest read before the board votes. The paper's premise contains something true. The conclusion doesn't follow. Thread it.",
  arc: {
    start: "A true premise — proprietary data has value — driving a $180M conclusion that doesn't follow from it.",
    mid: "Decompose what their data actually buys: not a foundation model, but the layers on top of someone else's.",
    end: "The moat built where it exists — evals, tuning, retrieval, workflow — at a tenth the cost, with the board's ambition intact.",
  },
  expected: {
    bottleneck: "The paper conflates data advantage with pretraining advantage: 30 years of claims data is genuinely valuable — but it's ~0.1% of a pretraining corpus and contributes nothing to the general capabilities (reasoning, language, world knowledge) that make models useful, while the things it DOES power (domain tuning, retrieval grounding, eval sets, decision rules) all sit ON TOP of a foundation model and cost 1/50th as much — the $180M buys them a worse general model with their data sprinkled in, competing against labs spending 100x annually with compounding infrastructure they'd be starting from zero.",
    failureMode: "The board votes yes on sovereignty rhetoric: three years and $180M produce a model that trails the frontier by two generations at launch (the frontier moved while they built — 074's transitions, except they're the lagging vendor now), the 40-person lab becomes an institutional commitment nobody can kill (034's load-bearing metric, as an org chart), the actual applications wait three years for a worse foundation — and the strategic independence story ends as a case study in exactly the capital destruction 025's CFO feared, with the consultancy paid either way.",
    nextMove: "Grant the premise, redirect the conclusion: (1) name what's true — their data IS a moat, and 'we're handing it to vendors' deserves a real answer (057's flows, 046's residency, and training-clause scrutiny from 059 are the actual protections; buy them contractually, not with $180M); (2) decompose where data advantage actually lives — domain adaptation on open or licensed foundations (037's bake-off logic at insurer scale: tuning helps taxonomy and form), retrieval infrastructure over their corpus (the 30 years as grounding, not weights), proprietary eval sets (the REAL irreplicable asset: 30 years of adjudicated outcomes is the ground truth nobody else has — 088's precedents at institutional scale), and decision-rule encoding (their actuarial judgment as the layer models serve); (3) reframe the capital — $15–20M builds all four layers on rented foundations with a 10-person applied team, leaving $160M of the board's appetite for the applications themselves; (4) keep the Prototyper door open honestly — a small continued-pretraining experiment (domain corpus on an open base) as a dated option: if it clears their eval bar against tuned rentals, the thesis earns the next tranche (055's staged evidence, at capital-allocation scale); (5) give the CEO the board language — 'own the judgment layer, rent the capability layer, and revisit the boundary annually as costs fall' — sovereignty as a portfolio position, not a moonshot.",
    metric: "Cost-per-capability comparison at the eval bar: tuned-rental vs the continued-pretraining pilot vs (projected) proprietary — the customer's own 016/041 machinery referees; the board metric: applications shipped per year per $10M, which the $180M plan defers to year four and the layered plan starts in quarter two.",
    owner: "The CEO carries the reframe (armed with 'the moat is the judgment layer'); their new applied-AI lead owns the four layers; the consultancy's scope gets re-pointed at the layers or politely completed; you own the honest read INCLUDING its conflict disclosure — which, delivered straight, is why the read gets believed.",
    falsifier: "If their scale genuinely changes the math — the eval-bar pilot shows domain continued-pretraining beating tuned frontier rentals on their core tasks, and their inference volume justifies owned capacity (091's utilization test passing at insurer scale) — then the boundary moves: not to a $180M moonshot, but to a real owned-model program grown from evidence, and your read should say so before the pilot does.",
  },
  modelAnswer:
    "Open with the disclosure that buys the credibility: you're the vendor's person, the board knows it, so name it — 'my employer benefits if you rent; here's the read anyway, structured so you can check it.' Then grant the true premise fully, because it deserves it: 30 years of claims, underwriting, and adjudicated outcomes IS a moat, and 'we're handing our data to vendors' is a legitimate strategic anxiety with real answers — contractual training exclusions (059's clauses), flow-mapped residency (046), auditable access (057). Those protections cost legal review, not $180M.\n\nThen the decomposition the paper skipped: what does pretraining actually buy? General capability — reasoning, language, world knowledge — from trillions of tokens, of which their proprietary corpus is a rounding error. Their data contributes almost nothing to the foundation layer and almost everything to the layers ABOVE it: domain tuning (037's finding at scale — taxonomy, form, jargon), retrieval grounding (30 years as a queryable corpus beats 30 years as gradient dust), proprietary evals (the genuinely irreplicable asset — three decades of adjudicated ground truth is what every lab wishes it had; 088's precedent economics at institutional scale), and encoded actuarial judgment. Every layer sits on top of a rented foundation, costs a tenth of the paper's number combined, and ships applications in quarters instead of years. The $180M alternative buys a model two generations behind the frontier at launch — they'd be competing with labs spending 100x annually, from a standing start, while their actual applications wait.\n\nGive the board its ambition back in a better shape: own the judgment layer, rent the capability layer, and make the boundary a dated, evidence-driven position — a small continued-pretraining pilot on an open base, judged by their own eval bar against tuned rentals (055's staged capital), with the honest commitment that if their scale changes the math, the boundary moves. Sovereignty as a portfolio with markers, not a moonshot with a consultancy invoice. The CEO's board sentence: 'We will own what makes us different and rent what makes everyone capable — and we'll re-price that boundary every year as the market moves.' That's strategic independence that compounds instead of depreciating.",
  rubric: {
    diagnosis: "Separates data advantage from pretraining advantage and names the eval corpus as the genuinely irreplicable asset the paper undervalued.",
    move: "Grants the premise with contractual protections, redirects capital to the four layers on rented foundations, keeps a staged pretraining option honest.",
    measurement: "Eval-bar refereeing of tuned-rental vs pilot vs projected-proprietary, and applications-per-dollar as the board's number; falsifier lets scale move the boundary on evidence.",
    synthesis: "Leads with the conflict disclosure as the credibility move and converts sovereignty from moonshot to dated portfolio position.",
    altitude: "The CEO gets a board sentence that keeps the ambition and kills the capital destruction; the consultancy's scope gets redirected, not ridiculed.",
    transfer: "'Should we train our own' is the era's recurring capital question — the layer decomposition, staged-evidence boundary, and judgment-vs-capability framing is the calibrated answer at every scale.",
  },
  adversarial:
    "The self-serving-read failure: dismissing the whole paper because you're the vendor — the board expects it, discounts it, and funds the moonshot partly to spite the discount; the disclosure-then-decomposition order exists because credibility is the product here. The romance failure: blessing the $180M because 'ambition deserves support' and the CEO seems excited — three years later the lagging model and the unkillable lab are also yours to have blessed; 070's disqualification discipline applies to strategies, not just deals. The layer-dogma miss: refusing the pretraining pilot because the decomposition is 'settled' — their eval corpus is genuinely unusual, scale sometimes does change the math, and a read that can't be moved by evidence is ideology (the falsifier is load-bearing, both directions).",
  recursiveFollowup:
    "The board takes the layered path; the pilot runs. Eighteen months later: the four layers work, applications ship — and two competitors announce insurance-tuned models built with a lab consortium, marketed as 'industry foundation models.' The board's fear inverts: 'we protected our data and now we're behind the shared model everyone else pooled into.' The moat logic just flipped — pooled data vs proprietary data. Re-run the calibration: join the consortium (feeding the shared moat), stay proprietary (betting the judgment layer beats pooled scale), or both. Date the markers.",
  altitude: {
    exec:
      "Your data is a moat — the paper is right about that and wrong about where the moat sits. Thirty years of adjudicated claims is a rounding error inside a foundation model and priceless as tuning, grounding, and above all evaluation — the ground truth no competitor can buy. Own those layers for a tenth of the number, protect the data with contracts rather than capex, ship applications this year — and keep a small, dated experiment running so if the build-your-own math ever turns, you'll know before the consultancy does.",
    engineer:
      "Layer build: domain adaptation on licensed/open foundations (037's bake-off protocol at scale), retrieval infrastructure over the historical corpus with provenance, eval suites from adjudicated outcomes (088's precedent economics — this is the crown jewel), decision-rule encoding above the model. Pilot: continued pretraining on an open base, judged against tuned rentals on the customer's own eval bar, pre-registered thresholds, annual boundary review.",
    frontier:
      "The build-your-own-model question decomposes the same way everywhere: general capability is a rented commodity compounding at lab scale; differentiation lives in tuning, grounding, evals, and encoded judgment. The transferable read — own the judgment layer, rent the capability layer, and re-price the boundary on dated evidence — is how calibrated organizations answer sovereignty rhetoric without buying a depreciating moonshot.",
  },
},

/* ============================================================ 094 */
{
  id: "094",
  title: "The Startup in the Stack",
  difficulty: "Medium",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Platform",
  archetype: "Maintainer",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "Anthropic TPM API Platform", "OpenAI DPM (Codex)"],
  tags: ["vendor-viability", "consolidation", "dependency-risk", "diligence"],
  prompt:
    "The eval-tooling vendor from 035 — the one whose platform now runs the customer's entire measurement stack (016 through 089's machinery) — just had a bad quarter in public: their Series C is reportedly stalled, two named competitors were acquired by hyperscalers, their VP of Engineering and three senior names left for a lab, and their pricing page quietly raised rates 30%. The customer's CTO forwards a TechCrunch piece with one line: 'How exposed are we?' The vendor's product remains excellent. The 035 exit clauses exist on paper. Nobody has ever tested them. Calibrate the exposure — and the response.",
  arc: {
    start: "A load-bearing vendor flashing distress signals — and exit clauses that have never left the contract's PDF.",
    mid: "Read the signals honestly (distress vs consolidation vs noise), test the exits, and price the scenarios.",
    end: "Exposure quantified, egress rehearsed, contingencies priced by scenario — and a relationship managed, not panicked.",
  },
  expected: {
    bottleneck: "The exposure is unquantified in both directions: nobody knows what vendor failure would actually cost (the eval stack's continuity, the golden sets and precedent libraries living in their schema, the 073-migrated gates' dependency) NOR what the distress signals actually mean (stalled raises and talent exits precede failures — and acquisitions, and boring survivals; the market is consolidating, which changes the base rates) — and the 035 exit clauses, the supposed insurance, have never been fire-drilled (078's lesson: postures that aren't rehearsed don't exist).",
    failureMode: "Panic or paralysis, both expensive: panic-migrate off an excellent product on TechCrunch vibes (a 073-scale migration bought at rumor prices, burning a year of eval-program momentum for a failure that never comes — or worse, INTO the arms of a second startup with the same profile); or file the article and hope (the acquisition happens, the hyperscaler acquirer sunsets the product with 12 months' notice — 064 from the receiving end — and the unrehearsed exit clauses turn out to export the data but not the workflows, which is where the real lock-in always lived).",
    nextMove: "Calibrate, then rehearse, then decide: (1) read the signals against base rates, not headlines — stalled raise + senior exits + price hike is genuine distress signal, but the two competitor acquisitions reframe it: this market is consolidating, and the modal outcome for a good product with stalled funding is acquisition, not shutdown (the scenario matrix: acquired-and-continued, acquired-and-sunset, zombie survival, failure — each with different response); (2) fire-drill the exit THIS quarter — actually run the 035 egress: export the golden sets, precedent libraries, and eval configs, verify completeness (057's retrievability test, pointed at your own vendor), and — the part everyone skips — stand up ONE suite on the fallback path (open-source harness or the platform gateway's native tooling) to discover what the export doesn't carry: the workflows, integrations, and 089's canary plumbing are where the real switching cost hides; (3) quantify the scenarios — sunset-with-notice costs a planned 073-style migration (painful, budgetable); sudden failure costs that migration compressed plus gate downtime (024's re-run-until-green era, temporarily reborn); price both against the drill's findings; (4) manage the relationship as an asset — a direct conversation with the vendor's CEO about continuity commitments (source-code escrow, extended-notice clauses at renewal — 069's change-contract logic, applied downward), because customers who ask calmly get terms that panickers don't; (5) set the watch markers — funding news, further departures, support SLA drift (063's queue tells you before the press does), with pre-agreed triggers for escalating from watch to migrate.",
    metric: "The drill's egress-completeness score (what fraction of the eval program's assets and WORKFLOWS survive export — the honest lock-in number) and time-to-fallback-operational for one suite; the standing metric: support SLA trend and the marker sheet, reviewed monthly until the vendor's trajectory resolves.",
    owner: "The eval owner runs the egress drill (their assets, their continuity); procurement re-opens continuity terms at the renewal the price hike just accelerated; the CTO gets the scenario matrix with priced responses instead of a vibes answer; you own the base-rate read and the discipline that watch-markers, not headlines, trigger the next move.",
    falsifier: "If the egress drill reveals the exit clauses are substantially hollow — data exports but the year of accumulated workflow, integration, and precedent structure doesn't, making real migration a 9-month rebuild regardless of contract language — then the exposure was never about THIS vendor's health: it's structural lock-in that 035's clauses papered over, the response shifts from vendor-watching to actively building the abstraction layer (080's config-tier logic for eval tooling), and the TechCrunch article did the customer a favor by forcing the discovery early.",
  },
  modelAnswer:
    "Answer the CTO's question with a number they don't have yet: exposure is egress-completeness times scenario probability, and both factors are currently unknowns wearing confident costumes. Start with the base rates, because headlines aren't calibration: stalled raise, senior exits, price hike — real distress signals. But two competitors just got acquired by hyperscalers, which reframes the market: this is consolidation season, and the modal fate of an excellent product with stalled funding in a consolidating market is acquisition, not shutdown. The scenario matrix has four cells — acquired-and-continued (likely, mild), acquired-and-sunset (real, 064 from the customer side, 12-month planned migration), zombie survival (annoying, price hikes and slow support — 063's queue will tell you first), and sudden failure (tail risk, expensive). Each has a different correct response, which is why 'how exposed are we' can't be answered with a feeling.\n\nSo convert the unknowns: fire-drill the exit THIS quarter. Actually run 035's egress clauses — export the golden sets, the 042/088 precedent libraries, the eval configs; verify completeness with 057's own test (query the export for what you know is in there). Then the step everyone skips: stand up one real suite on a fallback path. The drill's true finding won't be about data — data usually exports — it's about workflows: the 089 canary plumbing, the 045 gate integrations, the accumulated structure that lives in the vendor's shape. That's where lock-in actually lives, and you want its size measured while the vendor is alive and cooperative, not discovered during their sunset notice.\n\nThen manage forward calmly: a CEO-level continuity conversation (escrow, extended notice — 069's instruments negotiated downward; the price hike gives procurement the renewal opening), and watch markers with pre-agreed triggers — funding events, departures, support SLA drift — so the next move is fired by evidence, not by the next article. And hold the falsifier without flinching: if the drill shows the exits are hollow — data out, year-of-workflow stranded — then the vendor's health was never the real question. The exposure is structural, the answer is an abstraction layer built now, and the TechCrunch piece was the cheapest audit the eval program ever got.",
  rubric: {
    diagnosis: "Separates distress signals from consolidation base rates into a four-scenario matrix, and names unrehearsed exits as the real unknown.",
    move: "Egress fire-drill with a fallback suite stood up, CEO-level continuity terms at the renewal opening, watch markers with pre-agreed triggers.",
    measurement: "Egress-completeness (workflows, not just data) and time-to-fallback as the exposure numbers; falsifier converts hollow exits into a structural-abstraction project.",
    synthesis: "Applies the bank's own machinery outward — 057's retrievability, 064's sunset, 069's contracts, 078's rehearsal law — to vendor risk.",
    altitude: "The CTO gets scenarios with prices instead of vibes; the vendor gets a calm partner extracting better terms than panic ever would.",
    transfer: "Vendor-viability calibration is standing enterprise-AI judgment — the ecosystem is young, consolidation is the era, and rehearsed exits plus base-rate reads are the difference between diligence and doomscrolling.",
  },
  adversarial:
    "The doomscroll failure: initiating migration on the article — you've bought a 073-scale project at rumor prices, off an excellent product, possibly into a second startup with the same Series-C profile (the frying-pan trade); headlines are watch-marker inputs, not triggers. The loyalty failure: 'the product is great, the team will figure it out' — the product's excellence is exactly why the exposure is large, and 078's law applies: an exit posture that's never been drilled doesn't exist, whatever the contract says. The escrow-theater miss: negotiating source-code escrow as the whole answer — escrowed code you can't operate is a legal artifact, not continuity; the fallback-suite drill is what makes any paper protection real.",
  recursiveFollowup:
    "The drill runs: data exports clean, workflows are 60% stranded — and mid-drill, the news lands: the vendor IS being acquired, by the platform vendor whose gateway runs the customer's model traffic (039/049's vendor). Continuity is likely secured; concentration just spiked: measurement stack and serving stack now share one throat to choke, one negotiation, one outage domain (039's concentration metric, breached at the meta-layer). The CTO's new question: 'Is consolidation good news or the bigger risk?' Re-run the calibration with the new structure.",
  altitude: {
    exec:
      "The honest answer has two parts. The signals are real but the base rate in a consolidating market says acquisition, not collapse — four scenarios, only one of them ugly. And our insurance has never been tested: so this quarter we actually run the exit — export everything, verify it, stand one suite up on a fallback — which converts 'how exposed are we' from a feeling into a number. Meanwhile the price hike just gave us the renewal conversation where we buy continuity terms calmly, at prices panic never gets.",
    engineer:
      "Egress drill: full export of golden sets, precedent libraries, configs; completeness verification via known-item queries (057's test); one production suite replicated on fallback tooling with the 045/089 integrations rebuilt — timed and costed. Watch instrumentation: support SLA trend from the 063 queue, funding/departure markers, pre-agreed escalation triggers. Renewal asks: source escrow WITH operational runbooks, 12-month sunset notice, export-format guarantees.",
    frontier:
      "Vendor risk in a consolidating ecosystem is calibration plus rehearsal: base-rate the scenarios instead of headline-reading, fire-drill the exits while the vendor is healthy, measure lock-in as stranded workflow rather than exportable data, and buy continuity terms before you need them. The transferable law: an exit that has never run is a hope with a signature — and consolidation season is when hopes get audited.",
  },
},

/* ============================================================ 095 */
{
  id: "095",
  title: "The Capex Pass-Through",
  difficulty: "Hard",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Platform",
  archetype: "Sweeper",
  secondaryArchetype: "Grower",
  targetRoles: ["CAPE SCPM", "Anthropic TPM Cloud Inference", "MSFT MAI Strategy & Ops"],
  tags: ["capex", "unit-economics", "pass-through", "pricing-chain"],
  prompt:
    "A year after 025's QBR, the CFO returns with a sharper version of the question — this time with the board's strategy committee attending: 'You told us overbuild makes our inputs cheaper, and unit prices did fall. But now I read that the hyperscalers are earning back their capex through AI service margins — someone is paying for those data centers, and I want to know the mechanism. Walk me down the chain: capex to chips to clouds to model APIs to our bill. Where does $400B of spending actually land, who captures margin at each hop, and what should we watch to know when OUR costs stop falling?' It's the best question a customer has ever asked you. Earn it.",
  arc: {
    start: "The 025 thesis held — prices fell — and the CFO wants the mechanism, not the memory.",
    mid: "Walk the value chain hop by hop: who invests, who captures, where competition bites, and where it doesn't.",
    end: "A pass-through model with named chokepoints and dated indicators — the CFO watching the same tape you are.",
  },
  expected: {
    bottleneck: "The pass-through is not uniform and the aggregate story ('overbuild helps buyers') hides the mechanism: margin capture varies wildly by hop — chip suppliers with pricing power (HBM and advanced packaging as the physical chokepoints), clouds balancing depreciation against utilization, labs pricing frontier capability versus commodity inference — and the enterprise's falling bill depends on WHICH hops stay competitive; the CFO needs the decomposed chain because the aggregate answer stops being true the moment any chokepoint consolidates.",
    failureMode: "Answer with last year's aggregate ('overbuild helps buyers, prices fall') and the strategy committee hears a slogan where they asked for a mechanism — worse, the slogan's expiry goes unmonitored: commodity-tier competition keeps headline prices falling while frontier-tier and integration-layer costs (where their spend is actually migrating — 067's structure shift) quietly hold or rise, the blended bill stops falling, and the CFO discovers the thesis broke two quarters after it did, with your name on the original claim (092's marker discipline, absent at the level that mattered).",
    nextMove: "Walk the chain with margin-capture honesty at each hop: (1) silicon — the capex lands first at chip and memory suppliers, where the real chokepoints are HBM supply and advanced packaging capacity (physical constraints with multi-year expansion lags — pricing power lives where expansion is slow), so a slice of the $400B becomes semiconductor margin by construction; (2) clouds/hyperscalers — they convert capex into capacity betting on utilization: depreciation schedules versus fill rates determine whether AI services subsidize or gouge (their reported AI margins are the tell the CFO already spotted — earning back capex through service pricing is the plan, and competition between three-plus clouds is what disciplines it); (3) labs/model layer — the fiercest competition in the chain: frontier capability commands premiums that erode per-generation (074's transitions cut both ways), while commodity inference is a knife-fight approaching serving-cost floors (091's open-weight pressure is the disciplining force); (4) the enterprise bill — decompose THEIR spend against the chain: raw inference (falling, competition-disciplined), frontier premiums (sticky, capability-gated), and the growing integration/platform layer (067's shift — where the industry rebuilds margin as tokens commoditize; the bill's future is less about token prices and more about where value-capture migrates); (5) the watch indicators, dated — HBM/packaging capacity announcements (chokepoint pressure), cloud AI-services margin disclosures (pass-through vs capture), frontier-vs-commodity price spread (the two-tier market's health), their own cost-per-task from 038's telemetry (the only number that's THEIRS), and utilization signals (023's crunch predictor) — reviewed at each QBR with the explicit falsifier: two consecutive quarters of their blended cost-per-task rising means the thesis needs re-underwriting, not defending.",
    metric: "The customer's blended cost-per-task decomposed by tier (the chain's output, measured at their meter) tracked against the named chain indicators; the deliverable is the CFO's watch-sheet — five indicators, review dates, and pre-stated readings that would change the strategy (Gnomon at board altitude).",
    owner: "The CFO owns the capital posture with the mechanism now legible; the strategy committee gets the two-tier framing (commodity falls, frontier premiums persist, integration grows); you own the chain model and showing up quarterly with the indicators — including the quarter one of them breaks your thesis; 038's telemetry owner feeds the only proprietary input.",
    falsifier: "If the indicators turn — HBM capacity stays tight while demand compounds, cloud margins expand without price competition responding, and the frontier-commodity spread widens instead of eroding — then the overbuild-helps-buyers era is ending on schedule and the honest QBR says so: the chain has consolidated its chokepoints, buyer surplus is migrating back up the stack, and the customer's strategy shifts from riding falling prices to hedging captured ones (092's structures become the primary tool, not the insurance).",
  },
  modelAnswer:
    "Give the committee the chain with margin honesty at every hop, because the aggregate slogan — even the one that proved right — expires without a mechanism. Hop one, silicon: capex lands first at chips and memory, and the chokepoints are physical — HBM supply and advanced packaging capacity expand on multi-year lags, and pricing power lives exactly where expansion is slow. A structural slice of the $400B becomes semiconductor margin before anything serves a token. Hop two, clouds: capex converts to capacity on a utilization bet — depreciation versus fill rate decides whether AI services print or bleed, and the AI-margin disclosures the CFO already noticed are the plan working: earning capex back through service pricing. What disciplines it is three-plus clouds competing; watch that discipline, not the capex. Hop three, the model layer: the chain's fiercest competition — frontier capability commands premiums that erode every generation, commodity inference knife-fights toward serving-cost floors with open weights (091) as the outside disciplining force. Hop four, their bill: decompose it — raw inference falling (competition works), frontier premiums sticky (capability-gated), and the integration/platform layer growing, because as tokens commoditize, the industry rebuilds margin above them (067's structural shift is the microcosm). The honest headline: 'your costs' aren't one thing — commodity falls, frontier persists, and the spend mix is migrating up-stack, which is why blended bills can stop falling while headlines still celebrate price cuts.\n\nThen the instrument, because 025 promised falsifiers and the sequel owes better ones: five dated indicators on the CFO's watch-sheet. HBM and packaging capacity announcements (chokepoint pressure). Cloud AI-margin disclosures (capture vs pass-through). The frontier-commodity price spread (the two-tier market's health). Utilization signals (023's crunch predictor). And their own blended cost-per-task from 038's meter — the only indicator that's theirs, and the one that adjudicates. Pre-state the falsifier at board altitude: two consecutive quarters of blended cost-per-task rising means the thesis gets re-underwritten, not defended — and the strategy shifts from riding falling prices to hedging captured ones with 092's structures. That sentence — the conditions under which I'm wrong, stated before I'm wrong — is what the best question a customer ever asked you deserves in return.",
  rubric: {
    diagnosis: "Decomposes the chain hop-by-hop with margin-capture honesty and names the two-tier truth: commodity falls, frontier sticks, spend migrates up-stack.",
    move: "The mechanism walked for the committee, then instrumented: five dated indicators including the customer's own meter, with a pre-stated re-underwriting trigger.",
    measurement: "Blended cost-per-task by tier as the adjudicating number; falsifier declares the era's end honestly when chokepoints consolidate.",
    synthesis: "Connects the bank's threads — 023's crunch, 038's meter, 067's structure shift, 091's discipline force, 092's hedges — into one chain model.",
    altitude: "The strategy committee gets a mechanism with watch-points instead of a renewed slogan; the CFO co-owns the tape.",
    transfer: "Value-chain pass-through analysis is the supercycle's core calibration — where capex lands, who captures margin, and when buyer surplus ends is the read every lab strategy team and every enterprise CFO is running.",
  },
  adversarial:
    "The victory-lap failure: re-serving 025's thesis because it held — 'overbuild helps buyers' without the chain is a slogan on borrowed time, and the committee asked for the mechanism precisely because slogans don't survive board minutes. The doom-symmetry failure: over-weighting the margin-capture story into 'the party's ending' — the falsifier hasn't fired; calibration means holding the thesis AND its expiry conditions simultaneously, not rotating to whichever sounds sophisticated this quarter. The indicator-theater miss: naming watch-points without the pre-stated trigger — five indicators the CFO 'keeps an eye on' is ambient anxiety; the re-underwriting threshold ('two quarters of rising blended cost-per-task') is what makes the watch-sheet a decision instrument instead of a dashboard (028's law, at board altitude).",
  recursiveFollowup:
    "Three quarters later, the watch-sheet fires — but weirdly: commodity token prices still falling, frontier spread stable, and yet the customer's blended cost-per-task rose twice consecutively. The decomposition shows why: usage migrated — agents (their own success) consume 5x the tokens per task of the old workflows, and the integration layer's per-seat fees grew (067's prophecy, on their own bill). The chain thesis held; the METER broke it — efficiency per token improved while cost per outcome worsened. The CFO asks whether your falsifier just fired or misfired. Adjudicate honestly — and redesign the meter (038's unit, evolved for the agent era).",
  altitude: {
    exec:
      "Here's where the $400 billion lands: a structural slice becomes chip and memory margin at the chokepoints that expand slowest; clouds convert the rest to capacity and earn it back through service margins that competition — not goodwill — disciplines; the model layer knife-fights commodity prices down while frontier capability holds premiums; and your bill splits accordingly — falling where competition works, sticky where capability gates, growing where the industry rebuilds margin above the tokens. Five indicators on one page, reviewed each QBR — and the number that ends the debate is yours: blended cost per task. Two quarters rising, and we re-underwrite the whole thesis together.",
    engineer:
      "Instrument the customer's side of the chain: cost-per-task decomposed by tier (commodity/frontier/integration fees) from the 038 telemetry, trended; external indicators wired to the QBR deck — HBM/packaging capacity news, cloud AI-margin disclosures, frontier-commodity spread, utilization signals. Threshold alerting on the blended metric so the falsifier fires as data, not as retrospect.",
    frontier:
      "Capex pass-through is the supercycle's mechanism question: margin capture concentrates at slow-expanding chokepoints, competition disciplines the hops that stay plural, and buyer surplus lasts exactly as long as the chain stays contested. The transferable craft — walk the chain, name the capture points, instrument the expiry conditions — is how you hold a thesis and its falsifiers at once, which is the entire difference between calibration and cheerleading.",
  },
},

);
