/* Parabolic 100 — problem bank, part 13 (Frontier-Lab Transfer depth, 071–075) */

P100.PROBLEMS.push(

/* ============================================================ 071 */
{
  id: "071",
  title: "Launch Week, Half the Fleet Down",
  difficulty: "Hard",
  category: "Frontier-Lab Transfer",
  primaryLens: "Deployment",
  secondaryLens: "Platform",
  archetype: "Maintainer",
  secondaryArchetype: "Sweeper",
  targetRoles: ["Anthropic TPM Cloud Inference", "MSFT MAI Strategy & Ops", "OpenAI Deployment Eng"],
  tags: ["incident-command", "capacity", "comms", "sev1"],
  prompt:
    "Four days after a flagship model launch (traffic still 3x projections — 023's crunch, live), a bad kernel rollout takes out serving capacity in your largest region. Latency p99 goes vertical, error rates hit 15% for enterprise customers with SLAs, the status page still says green, three account teams are pinging you directly, the serving team is deep in mitigation and answering nobody, and two VPs have joined a hastily-made channel asking 'what's the impact?' You're the launch TPM. Nobody has declared an incident. Command it.",
  arc: {
    start: "A capacity fire with no commander: engineers mitigating, execs asking, customers discovering, status page lying.",
    mid: "Declare, structure, and separate the streams: mitigation, truth, and communication each get an owner.",
    end: "Service restored in stages, customers informed before they discovered, and a postmortem that fixes the class.",
  },
  expected: {
    bottleneck: "No incident structure: mitigation, impact assessment, and communication are competing for the same few brains — the serving team is being interrupted by the very people who'd stop interrupting if someone owned communication, and the green status page is converting an outage into a trust incident (027's watermelon at 15% error rate).",
    failureMode: "Uncommanded incidents run long and lie by omission: engineers mitigate while nobody sizes impact, VPs get answers by interrupting the mitigators (making it slower), enterprise customers discover the outage from their own dashboards while yours says green — and the postmortem's hardest finding is that the outage was survivable but the silence wasn't (SLA credits are budgeted; discovered dishonesty isn't).",
    nextMove: "Declare and structure in the first ten minutes: (1) name yourself incident commander (or name someone — the declaration matters more than the person), open the incident channel, and post the operating structure: serving lead owns mitigation and is interrupt-protected, a deputy owns impact assessment (which customers, which SLAs, what error rates — 032's one-fact-set under fire), you own communications; (2) fix the status page NOW — degraded, scoped, honest; every minute of green-during-red converts outage into deceit; (3) structure the comms cadence — customers with SLAs get proactive notice with what-we-know/what-we're-doing/when-next-update (account teams deliver it, armed with your canonical update, not their improvisations); VPs get the same rhythm in the channel (predictable updates are what stop the interrupting — 026's slip-signal logic applied to executives); (4) stage the recovery — capacity returns by tier (023's published degradation order runs in reverse: contractual SLAs first), and 'restored' is verified by error-rate telemetry, not by the serving team's exhausted optimism; (5) close the loop — postmortem within the week, blameless on the kernel rollout, ruthless on the structural findings: why no auto-declared incident at these thresholds, why the status page needed a human.",
    metric: "During: time-to-declaration, time-to-honest-status-page, and interrupt count on the serving lead (the protection metric); after: customer-informed-before-discovered rate — the trust number that outlives the outage — and SLA impact by tier.",
    owner: "You command; serving lead mitigates untouched; deputy owns the impact ledger; account teams deliver canonical comms; the postmortem assigns the structural fixes (auto-declaration thresholds, status-page automation) with dates.",
    falsifier: "If, on declaring, you discover the serving org already has a functioning incident structure running in a channel you weren't in — commander named, comms owned, status page update queued — then the failure was YOUR visibility, not their command: plug the launch-TPM role into their structure as the customer/exec comms arm, and don't build a rival incident hierarchy mid-fire.",
  },
  modelAnswer:
    "The fire is real but the killing failure is structural: nobody declared. An undeclared incident means mitigation, truth-finding, and communication all compete for the same six engineers — and communication always loses, which is why the status page lies and the VPs are extracting updates by interruption, which taxes the only people who can fix the thing. Incident command exists to separate those streams, and in minute one it matters more than the kernel fix.\n\nDeclare it — sev1, named commander (you; the role is coordination, and you're the one who can afford to not be debugging), incident channel with the structure posted: serving lead owns mitigation and is now interrupt-protected (all questions route through you); a deputy owns the impact ledger — which customers, which regions, which SLAs, real error rates — one fact-set, 032-style, because in an hour there will be three competing impact narratives unless someone owns the canonical one. You own comms, on a cadence.\n\nThe status page is the moral center of the incident: 15% enterprise error rate under a green banner is not a delay, it's a lie your customers are currently catching you in. Degraded, scoped, honest — now. Then proactive SLA-customer notice through the account teams, armed with your canonical update (what we know / what we're doing / when you'll hear next). Customers metabolize outages; they don't metabolize discovering them. The VPs get the same rhythm: predictable updates every 30 minutes are what convert executives from interrupters into recipients.\n\nRecovery is staged, not celebrated: capacity returns by the published tier order (023's degradation ladder, reversed — contractual first), and 'restored' is an error-rate reading, not a feeling. Then the postmortem, split cleanly: blameless on the kernel (rollouts fail; that's why staging exists — and why 045's canary logic applies to infra too), ruthless on structure: why did declaration need a person, why did the status page need a hand, what auto-triggers at these thresholds next time. Launch week means there IS a next time; buy the structure while the pain is fresh.",
  rubric: {
    diagnosis: "Names the absence of command structure — not the kernel — as the operative failure, and the green status page as the trust wound.",
    move: "Declare, protect mitigation, canonicalize impact, cadence the comms, stage recovery by tier, split the postmortem blameless/structural.",
    measurement: "Time-to-declaration, interrupt protection, informed-before-discovered rate; falsifier prevents building a rival hierarchy over an existing one.",
    synthesis: "Sees predictable cadence as the exec-management tool and the status page as where outage becomes deceit — comms engineering, not PR.",
    altitude: "VPs get rhythm instead of extraction; customers get notice instead of discovery; the serving team gets silence to work in.",
    transfer: "Incident command during capacity events is the cloud-inference TPM's defining hour — and the CAPE translation (customer-facing sev management) is verbatim.",
  },
  adversarial:
    "The helpful failure: diving into mitigation yourself because you know the serving stack — now the incident has zero commanders and seven engineers; your leverage was never the kernel. The message-control failure: delaying customer notice 'until we know more' — customers with dashboards already know more; the delay only determines whether they hear it from you or catch you. The cadence miss: answering each VP individually as they ping — you've become the interrupt you were supposed to absorb; the whole point of the rhythm is that nobody needs to ask. And the recovery trap: declaring victory on the serving team's 'should be good now' — 15 minutes of green telemetry is the only 'restored' that survives a second dip.",
  recursiveFollowup:
    "Postmortem week: the kernel rollout traces to a fix that was itself rushed to handle launch traffic — the 023 crunch pressured the very change that broke the fleet. Serving leadership wants the postmortem to say 'process failure'; you know it was a capacity-pressure failure that process can't absorb. The VP who owns launch velocity is in the review. Write the finding that's true, survivable, and changes the next launch.",
  altitude: {
    exec:
      "Declared sev1, I'm commanding. Serving is on mitigation and protected from questions — everything routes through me. Status page goes honest in the next five minutes; SLA customers hear from us before their dashboards tell them. Updates every thirty minutes in this channel whether or not anything changed. Recovery restores contractual tiers first, and 'fixed' means fifteen clean minutes of telemetry, not optimism.",
    engineer:
      "Structure: mitigation (serving lead, interrupt-protected), impact ledger (deputy: customers × SLAs × error rates, one canonical doc), comms (me, 30-min cadence). Status page to degraded-scoped now. Recovery by tier order with error-rate verification gates. Postmortem captures auto-declaration thresholds and status-page automation as structural actions.",
    frontier:
      "Capacity incident command is stream separation: mitigation, truth, and communication each owned, so engineers work in silence while customers and executives get rhythm instead of discovery. The transferable laws — declare early, never let the status page lie, stage recovery by commitment tier, split postmortems blameless/structural — run every serving fleet and every enterprise sev bridge alike.",
  },
},

/* ============================================================ 072 */
{
  id: "072",
  title: "The Researchers Built Their Own Queue",
  difficulty: "Medium",
  category: "Frontier-Lab Transfer",
  primaryLens: "Platform",
  secondaryLens: "Customer",
  archetype: "Grower",
  secondaryArchetype: "Builder",
  targetRoles: ["MSFT MAI Strategy & Ops", "Anthropic TPM Cloud Inference", "MSFT MAI Evals Eng"],
  tags: ["research-infra", "internal-platform", "shadow-tooling", "developer-experience"],
  prompt:
    "You run program for a lab's training-infrastructure platform. An audit of cluster usage finds that the top three research teams have quietly built their own job schedulers on raw allocations — bypassing the official queue system entirely. Their reasons, when you ask: 'the queue's priority logic buries exploratory runs for days,' 'the submission API requires configs nobody understands,' and 'we can't preempt our own jobs.' The platform team wants enforcement: 'unmanaged schedulers are why utilization reporting is garbage and why the fairness model doesn't work.' The researchers ship the lab's actual product. Resolve it.",
  arc: {
    start: "Your most important users have seceded from your platform — and both sides have a point.",
    mid: "Read the shadow schedulers as the requirements document; make the paved road faster than the workaround.",
    end: "Researchers back on a queue that serves exploration, platform telemetry restored — adoption by merit, not mandate.",
  },
  expected: {
    bottleneck: "The platform optimized for the wrong customer: the queue's priority logic, config surface, and preemption model were designed for fairness-and-utilization accounting (the platform team's needs), not for the research workflow's actual shape — fast exploratory iteration, self-preemption, low-ceremony submission — so the lab's highest-leverage users rationally routed around it (014's shadow dynamic, except the 'shadow' users are the entire point of the company).",
    failureMode: "Enforcement wins the battle: raw allocations get locked down, shadow schedulers die, researchers submit through the hated queue — and exploratory iteration slows lab-wide, which is invisible in platform metrics and catastrophic in research velocity; the platform hits its utilization targets while quietly taxing the only work that matters (028's metric trap: the dashboard says the platform succeeded).",
    nextMove: "Treat the three shadow schedulers as the requirements spec they are: (1) sit with each team and extract what their scheduler does that yours doesn't — expect: exploration lanes (short speculative runs that shouldn't queue behind week-long training jobs), self-preemption (teams reshuffling their own priorities without tickets), and low-ceremony submission (sane defaults over config essays); (2) build those as first-class queue features WITH the shadow-scheduler authors as design partners — they've already prototyped your roadmap (014's deputize move, at a lab); (3) migrate by merit with a bridge — shadow schedulers keep working during the transition, and teams move when the official path is measurably better (paved-road law: win on speed, not policy); (4) give the platform team their telemetry a different way — a thin reporting shim shadow schedulers can emit to during the bridge, so utilization accounting recovers before full migration; (5) reserve enforcement for the endgame — after the paved road demonstrably serves the workflow, raw-allocation bypass becomes a governance question with a defensible answer.",
    metric: "Exploratory-run queue latency (the number the researchers actually seceded over) versus shadow-scheduler equivalent — parity or better is the migration gate; plus voluntary migration rate by team, the merit test enforcement can't fake.",
    owner: "The platform team owns building the exploration features (reframed from 'losing to shadow IT' to 'our users prototyped our roadmap for free'); the three research teams own design partnership and honest bridging telemetry; you own sequencing merit-before-mandate and protecting both sides' faces.",
    falsifier: "If workflow analysis shows the shadow schedulers exist mostly to grab unfair capacity share — the 'exploration lanes' are actually priority-jumping, and the teams' iteration metrics don't differ from queue-users' — then this is 023's allocation politics wearing developer-experience clothes, the fairness model is the real casualty, and enforcement plus an honest allocation conversation is the right call after all.",
  },
  modelAnswer:
    "Read the org chart before the audit: the researchers are not your policy violators — they're your customers, and they've churned. Three of them built competing products. In any external market this would be read instantly: the platform lost on product, and the shadow schedulers are the most detailed requirements document you'll ever receive, written in working code by your most sophisticated users. 014's paved-road law applies with double force when the routing-around is done by the people who ship the lab's actual product.\n\nExtract the spec: each shadow scheduler encodes a workflow truth the queue ignored. Exploration lanes — research iterates in short speculative runs that die of queue latency behind week-long training jobs; the priority logic that maximizes 'fairness' is minimizing learning rate. Self-preemption — teams need to reshuffle their own jobs without filing tickets against their own allocation; the queue treats their capacity as yours. Low ceremony — a submission API that requires config archaeology loses to a shell script every time, correctly. Build these as first-class features with the shadow authors as design partners: they've prototyped your roadmap; deputize them (the same move that converts 014's rule-breakers and 061's enthusiasts).\n\nSequence merit before mandate: the bridge period keeps shadow schedulers alive while the official queue earns migration — with a thin telemetry shim so the platform team's utilization accounting (a legitimate need — 023's allocation math runs on it) recovers immediately rather than at the end. Teams migrate when exploratory-run latency hits parity; that number, not policy, is the gate. Enforcement is the endgame's cleanup, not the opening move — after the paved road wins, remaining bypass is a fairness question with a defensible answer.\n\nAnd hold the falsifier honestly: if the 'workflow needs' decompose into capacity-grabbing — exploration lanes as priority-jumping costumes — then this was 023 all along, and the answer is allocation governance, said plainly. The audit can't distinguish those two stories; sitting with the teams can.",
  rubric: {
    diagnosis: "Reads shadow schedulers as customer churn and a requirements spec — platform optimized for accounting, not the research workflow.",
    move: "Extract the spec, build with shadow authors as partners, bridge with telemetry shim, migrate on measured merit, enforce only at endgame.",
    measurement: "Exploratory-run latency parity as the migration gate and voluntary migration as the merit test; falsifier separates workflow needs from capacity grabs.",
    synthesis: "Balances the platform team's legitimate telemetry/fairness needs against research velocity — both get served, in the right order.",
    altitude: "The platform team hears 'your roadmap arrived free' instead of 'you lost'; researchers hear partnership instead of policy.",
    transfer: "Researcher-facing infrastructure is the canonical internal-platform problem at every lab — and MAI's training-infra program lives exactly here.",
  },
  adversarial:
    "The governance failure: enforcement first — you can win it (platform controls the allocations), and the cost is invisible: exploratory iteration slows lab-wide while your utilization dashboard improves (028's can't-say-no metric, celebrating the damage). The capitulation failure: blessing the shadow schedulers permanently — fairness accounting and capacity planning (023) genuinely need unified telemetry, and three schedulers become nine by year-end. The consultation theater miss: 'gathering requirements' from the researchers instead of adopting their working code and its authors — they didn't write you a wishlist, they wrote you an implementation; treating design partners as survey respondents is how the second secession starts.",
  recursiveFollowup:
    "The exploration lanes ship; two teams migrate voluntarily. The third — the lab's most senior research group — refuses: 'ours is better and we don't have time to validate yours.' They're right that theirs is better for them (it should be; it's bespoke), and their seniority means enforcement needs a VP's spine. The paved road won 2 of 3 on merit. Decide what to do with the holdout — and what precedent either answer sets for the next team that wants an exception (021's math, internal edition).",
  altitude: {
    exec:
      "Our top research teams built their own schedulers because ours buries exploratory runs for days — they're not violators, they're churned customers who prototyped our roadmap. We're building what their schedulers prove they need, with them as design partners, bridging telemetry so capacity accounting recovers now, and migrating on measured merit. Enforcement comes last, when the official path has earned it.",
    engineer:
      "Extract per shadow scheduler: lane semantics, preemption model, submission ergonomics. Ship exploration lanes (short-run SLO separate from training-job fairness), self-preemption within team allocations, and defaults-first submission. Bridge shim: shadow schedulers emit usage events to the central ledger during migration. Gate: exploratory p90 queue latency ≤ shadow baseline.",
    frontier:
      "Internal platforms at labs live or die on this: researchers route around friction toward iteration speed, and their workarounds are requirements documents in working code. The transferable sequence — extract the spec, deputize the authors, bridge the telemetry, migrate on merit, enforce last — is the paved-road law applied to the platform's most leveraged users.",
  },
},

/* ============================================================ 073 */
{
  id: "073",
  title: "Migrating the Eval Stack Without Dropping the Gate",
  difficulty: "Hard",
  category: "Frontier-Lab Transfer",
  primaryLens: "Eval",
  secondaryLens: "Deployment",
  archetype: "Builder",
  secondaryArchetype: "Maintainer",
  targetRoles: ["Anthropic TPM Safeguards & Evals", "MSFT MAI Evals Eng", "OpenAI Deployment Eng"],
  tags: ["migration", "eval-infra", "gates", "parity"],
  prompt:
    "The eval platform you made trustworthy in 024 (90-minute runs, 1% flakes, signed overrides) has hit its ceiling: the homegrown stack can't handle the new model family's context lengths, agentic multi-turn evals, or the 10x suite growth safeguards wants. The org has approved migrating to a new evaluation platform — but the old stack IS the release gate: every model ship for two years has cleared through it, its quirks are load-bearing (teams have tuned prompts against its exact sampling settings), and a migration bug that inflates scores would wave a bad model through while one that deflates them blocks the org. Nine model releases are scheduled during the migration window. Design it.",
  arc: {
    start: "Replacing the instrument the org trusts, while nine releases must keep clearing it.",
    mid: "Parallel-run with divergence triage: the gate never has fewer than one trusted reading.",
    end: "The new stack holds the gate, the old one retires with honors — and the diffs taught you what your evals actually measured.",
  },
  expected: {
    bottleneck: "The migration must preserve gate continuity through nine releases while the measurement instrument itself changes — and 'parity' is treacherous: score differences between stacks may be migration bugs, or may be the old stack's quirks (sampling settings, prompt truncation, judge versions) that teams unknowingly tuned against — meaning some divergence is the new stack being MORE correct, and naive parity-chasing would faithfully port two years of accumulated measurement error.",
    failureMode: "Cutover between releases with spot-check parity: release six clears the new stack with a subtly inflated safety score (a harness difference in multi-turn handling), the regression 024's gate exists to catch ships to production — and the postmortem's finding is that the org replaced its most trusted instrument with an unvalidated one mid-stream, converting every historical baseline into an unanswerable question (042's moved goalposts, at release-gate stakes).",
    nextMove: "Parallel-run as the spine, divergence as the product: (1) both stacks run every gated eval for a defined overlap period covering at least three releases — the old stack remains the gate of record while the new one shadows; (2) triage every divergence into a taxonomy — migration bug (fix new stack), legacy quirk (old stack was wrong: document, keep the new behavior, and re-baseline that eval consciously), or ambiguous (escalate to eval owners with 041's meta-eval discipline: which reading agrees with ground truth?); (3) gate-flip criteria pre-published (024's own medicine): N consecutive releases with all divergences dispositioned, ambiguous count at zero for blocking evals, and safeguards' explicit signoff per suite; (4) baseline continuity handled honestly — where legacy quirks die, historical comparisons get a documented discontinuity marker (042's changeover annotation) rather than silent re-anchoring; (5) the old stack retires 064-style: read-only for one quarter (auditors and baseline questions), then archived with its exact configs preserved — reproducibility of past gate decisions is a compliance asset.",
    metric: "Divergence burn-down by class (bugs fixed, quirks documented, ambiguous resolved) — the migration's real progress bar; gate-flip only when blocking-eval divergence is fully dispositioned; post-flip: gate decision stability (would the old stack have agreed on each release verdict during overlap — tracked and reported).",
    owner: "The eval platform team owns the parallel harness and divergence taxonomy; suite owners (safeguards for theirs) own dispositioning ambiguous diffs and signing their suite's flip; you own the pre-published flip criteria and the discipline that nine release deadlines don't compress the overlap; release owners keep clearing through the gate of record, undisturbed.",
    falsifier: "If the overlap reveals pervasive large divergence — most evals disagree materially and dispositioning can't keep up — then the two stacks are measuring different things at a depth no migration should paper over, and the honest move is halting the migration to first specify what each eval MEANS (input handling, sampling, judging — 041's validity work), because a platform swap was never the real project; a measurement re-specification was.",
  },
  modelAnswer:
    "Name the stakes precisely: you're not migrating infrastructure, you're transplanting the org's definition of 'safe to ship' while it's in use. The old stack's authority took two years to earn (024 was the down payment), and authority doesn't port with the data — it re-earns through demonstrated agreement. The design principle: the gate never has fewer than one trusted reading, which means parallel-run isn't a validation phase, it's the load-bearing architecture.\n\nBoth stacks run everything for an overlap spanning at least three real releases — the old stack remains gate of record; the new one shadows and diffs. And here's where the migration gets intellectually honest: divergence isn't noise to eliminate, it's the most informative dataset this platform will ever produce. Every diff is one of three things. A migration bug — fix it. A legacy quirk — the old stack truncated prompts at some boundary, pinned an old judge version, sampled at settings teams unknowingly tuned against; here the NEW stack is right, and 'parity' would mean faithfully porting two years of measurement error. Document the quirk, keep the correct behavior, and consciously re-baseline that eval with 042's changeover annotation — silent re-anchoring is how historical comparisons become fiction. Or ambiguous — neither obviously right — which routes to 041's meta-eval question: which reading agrees with ground truth? Blocking evals flip only when their ambiguous count is zero.\n\nPre-publish the flip criteria before the first diff exists (the gate's own 024 medicine: legitimacy through visible rules): N clean releases, full disposition, per-suite signoff from the owners whose evals gate — safeguards signs safeguards. Nine scheduled releases will pressure the overlap; the pre-published criteria are what let you hold it, because 'we flip when the criteria say' survives deadline pressure in a way 'we're being careful' doesn't. Retire the old stack with 064's discipline — read-only quarter, configs archived — because 'can you reproduce the gate decision for release 47' is a question auditors ask. And keep the falsifier live: if divergence is pervasive, stop calling it a migration; you've discovered the evals were never specified, and that project precedes any platform.",
  rubric: {
    diagnosis: "Frames the migration as transplanting trusted measurement under load, and divergence as tri-class signal — bug, legacy quirk, or ambiguity — not noise.",
    move: "Parallel-run architecture with gate-of-record continuity, divergence taxonomy and disposition, pre-published per-suite flip criteria, honored retirement.",
    measurement: "Divergence burn-down by class as the progress bar and post-flip gate-agreement tracking; falsifier halts for re-specification when diffs are pervasive.",
    synthesis: "Sees that naive parity ports two years of measurement error — the migration is also an audit of what the evals actually measured.",
    altitude: "Release owners feel nothing (the gate of record never wavers); safeguards signs its own suites; deadlines meet pre-published criteria instead of judgment calls.",
    transfer: "Eval-infra migration under live gates is safeguards-platform work at its hardest — parity taxonomies, baseline discontinuities, and reproducibility archives are the craft.",
  },
  adversarial:
    "The parity-worship failure: making the new stack match the old exactly — congratulations, you've re-implemented the truncation bug teams tuned against, at 10x scale; some divergence is the new stack being right, and refusing that possibility ports the error with the authority. The deadline failure: compressing the overlap because release seven 'can't slip' — an unvalidated gate waving through release seven is the exact catastrophe the gate exists for; this is why the flip criteria publish BEFORE the pressure. The archaeology miss: retiring the old stack immediately post-flip — the first 'why did release 44 pass?' question arrives within a quarter, and 'we deleted the instrument' is an answer regulators and researchers both hate.",
  recursiveFollowup:
    "Mid-overlap, the divergence triage surfaces something worse than a bug: a blocking safety eval has been scoring ~4 points high on the OLD stack for over a year (a judge-version pin nobody noticed) — meaning two shipped releases cleared a gate they might not have. The migration is now an incident with historical scope (015's audit question at release scale). The new stack is right; the past is the problem. Run the disclosure decision: who needs to know, what gets re-evaluated, and does anything shipped get re-gated?",
  altitude: {
    exec:
      "The release gate stays trustworthy every day of this migration: the old stack keeps deciding while the new one shadows every eval, and we flip only when pre-published criteria are met — every difference explained, suite owners signed, nine releases undisturbed. One honest cost: where we find the old stack was subtly wrong, historical baselines get a documented break rather than a silent one.",
    engineer:
      "Dual-run harness with per-eval diff capture: score deltas, transcript-level comparison, config fingerprints (sampling, judge versions, truncation). Divergence taxonomy with disposition workflow; blocking evals require zero ambiguous before flip. Baseline discontinuity markers in the results store. Old stack: read-only quarter, then config-complete archive for gate-decision reproducibility.",
    frontier:
      "Migrating measurement infrastructure under live gates is the evals-platform discipline compressed: parallel-run as architecture, divergence as tri-class signal, pre-published flip criteria as deadline armor, and the humility that parity with a flawed instrument is just error with continuity. The transferable law: authority doesn't port — it re-earns through demonstrated agreement.",
  },
},

/* ============================================================ 074 */
{
  id: "074",
  title: "The Model Changed Under Their Product",
  difficulty: "Medium",
  category: "Frontier-Lab Transfer",
  primaryLens: "Platform",
  secondaryLens: "Customer",
  archetype: "Maintainer",
  secondaryArchetype: "Grower",
  targetRoles: ["Anthropic TPM API Platform", "OpenAI DPM (Codex)", "CAPE SCPM"],
  tags: ["model-versions", "deprecation", "enterprise", "behavior-change"],
  prompt:
    "You're on the lab's API platform team. A top-20 enterprise customer escalates to their account exec, who escalates to you: last month's model version update changed refusal behavior on their compliance-screening product — queries that used to process now return safety refusals at ~3% rate, their downstream automation treats refusals as errors, and their ops team has been hand-working the queue for three weeks before anyone connected it to the model update. They're contractually within the migration window for the old version, but it sunsets in 60 days. Their ask: 'freeze the old model for us indefinitely, or make the new one behave identically.' Neither is happening. Find the real resolution.",
  arc: {
    start: "A behavior change nobody flagged, three weeks of silent damage, and two impossible asks on the table.",
    mid: "Decompose the 3%: what changed, what their workload actually needs, and what the platform owes at version boundaries.",
    end: "Their pipeline handles refusals as a designed state, the worst gaps get addressed in-model or in-workflow — and version changes stop being ambushes.",
  },
  expected: {
    bottleneck: "Model version transitions are being treated as infrastructure upgrades when they're behavior changes: the customer built production automation against implicit behavioral contracts (refusal patterns) that no SLA covers, the lab shipped a safety improvement without workload-level impact visibility, and neither side has machinery for the seam — 069's roadmap problem, except the change already shipped and the notice never fired.",
    failureMode: "Fight about the two impossible asks: indefinite version freezes fragment the serving fleet (023's capacity math forbids it at scale) and behavioral identity contradicts why models get updated at all — meanwhile the customer's real problem (a pipeline that can't handle refusals, hitting cases the new model now refuses) goes unsolved, they architect their exit to a competitor who'll ambush them identically in a year, and the account's story becomes 'the lab broke us and argued.'",
    nextMove: "Triage the actual 3% before negotiating the impossible: (1) get the refused-query sample and decompose it (075's discipline) — expect a mix: genuinely borderline content the new model correctly flags (their compliance workload lives near policy boundaries by definition), false positives worth filing as model feedback, and prompt patterns that re-phrase cleanly; (2) fix by class — false positives route to the safety team with workload evidence (this is exactly the feedback loop the lab wants from enterprise usage), re-phrasable patterns get engineering support from your side, and the genuinely-refused class gets the honest conversation: those cases NEED human review in their workflow, and their automation treating refusals-as-errors was the design gap (070's review-as-workflow, arriving late); (3) buy time honestly — a bounded extension on the old version tied to a migration plan with dates (not a freeze: a ramp), which capacity can absorb because it's bounded; (4) fix the class for everyone — this escalation is free product feedback (020): version transitions need behavior-diff previews (a test window where enterprises replay their traffic against the new version), refusal-rate-delta telemetry per customer, and proactive notice when a customer's workload profile will feel a change; the customer's three silent weeks are the strongest evidence that artifact should exist.",
    metric: "The decomposed 3% (false-positive rate → safety team; re-phrasable → resolved; legitimate-refusal → workflow redesign) and their queue's hand-work burn-down; for the class fix: behavior-diff preview adoption and time-to-detection of workload-impacting changes across the book (three weeks → hours).",
    owner: "You own the triage and the bounded-ramp negotiation; the safety team owns false-positive dispositions (with this workload as a labeled eval set — 044's conversion rule); the customer owns making refusals a designed state in their pipeline; product owns the version-transition machinery this escalation just specified.",
    falsifier: "If the decomposition shows the 3% is nearly all false positives — the new model genuinely regressed on their legitimate compliance content — then this isn't a workflow-design conversation, it's a model regression their escalation caught before your evals did (075's exact scenario), the safety team owns a fix or a documented exception path, and the customer deserves the extension for free plus thanks.",
  },
  modelAnswer:
    "Start by refusing the framing contest: both asks are impossible (indefinite freezes fragment the fleet; behavioral identity contradicts updating models at all), but arguing impossibility solves nothing they have. Their real problem is a 3% refusal rate hitting automation that treats refusals as errors — and that decomposes, which means it triages.\n\nGet the refused sample and split it three ways (this is 075's method applied to safety behavior). Some fraction is genuinely borderline — they run compliance screening; their workload lives at the policy boundary by construction, and the new model flagging more of it may be the safety improvement working. Those cases need human review in their pipeline — not as failure handling, as designed workflow (the 070 conversation their original architects skipped: refusals-as-errors was the latent bug; the model update just exercised it). Some fraction is false positives — legitimate screening content wrongly refused — and that routes to the safety team as labeled, high-quality enterprise feedback (the kind labs beg for; 044's conversion rule says it becomes eval content). Some fraction re-phrases cleanly with engineering help from your side this week — immediate relief, cheap.\n\nOn the timeline: not a freeze — a bounded ramp. Sixty days becomes a migration plan with dates and an extension tied to milestones, which capacity can absorb precisely because it's bounded (023's math tolerates ramps; it dies on precedents of indefinite pins — and 021 says price that precedent before granting anything). In exchange, they build refusal-handling as a state, not an error.\n\nThen extract the platform lesson, because this escalation is a free spec: version transitions need behavior-diff previews (enterprises replay their traffic against the candidate version in a test window), per-customer refusal-delta telemetry, and proactive notice keyed to workload impact — the three silent weeks are the indictment; hand-working a queue because nobody connected the dots is the experience that architects exits. The account's story should end 'they found what changed, fixed what was wrong, helped us handle what was right, and built the thing that makes next time visible' — which is also, precisely, the platform's competitive moat at version boundaries.",
  rubric: {
    diagnosis: "Refuses both impossible asks without fighting them, and decomposes the 3% into borderline / false-positive / re-phrasable classes.",
    move: "Fix-by-class triage, bounded ramp instead of freeze, refusals redesigned as workflow state, and the escalation converted into version-transition machinery.",
    measurement: "Class-level disposition of the sample and hand-work burn-down now; time-to-detection across the book as the platform fix; falsifier flips it to a caught regression owed thanks.",
    synthesis: "Sees the customer's compliance workload as boundary-dwelling by nature and their escalation as the spec for behavior-diff previews — 020's pattern pipeline fed by pain.",
    altitude: "The customer hears triage and dates instead of impossibility; the safety team hears labeled enterprise evidence; product hears the artifact this class of escalation keeps specifying.",
    transfer: "Model-version change management is the API-platform TPM's core seam — behavioral contracts, migration ramps, and diff previews are the emerging standard, and CAPE sees the same seam from the customer side.",
  },
  adversarial:
    "The policy failure: holding the 60-day line because 'the migration window was contractual' — legally sound, and it converts a top-20 account's incident into their competitor evaluation; contracts define the floor, not the relationship. The capitulation failure: granting the indefinite freeze — 021's precedent math is brutal here (forty accounts will invoke it by year-end) and 023's fleet fragmentation is the quiet cost that compounds. The empathy miss: solving the 3% brilliantly and skipping the class fix — the next version update ambushes a different customer identically, and the platform learns it has a recurring incident instead of a missing feature.",
  recursiveFollowup:
    "The triage lands: 40% false positives (safety team confirms and commits a fix in the next version), 35% re-phrasable, 25% genuinely borderline. The customer accepts refusal-handling for the 25% — then asks the sharp question: 'Your next version will change behavior again. What contractually binds you to the diff-preview and notice process you just invented, or is it goodwill until it's inconvenient?' Draft the answer — what the platform will sign versus what it will only promise (069's instruments, from the lab's side of the table).",
  altitude: {
    exec:
      "Neither ask is possible — but your actual problem is solvable this month. We're decomposing the refused queries: what's wrongly refused goes to our safety team as evidence with a fix path, what can re-phrase gets our engineers this week, and what's genuinely borderline needs review in your workflow — treating refusals as errors was the latent gap. You get a bounded extension tied to migration dates, and we're building the traffic-replay preview so no version change ambushes you again.",
    engineer:
      "Refused-query sample with classification: false-positive candidates (packaged as labeled eval cases for safety), re-phrasable patterns (prompt engineering support), legitimate boundary cases (refusal-state handling in their pipeline — retry/route/review, not error). Ramp plan with milestone gates. Platform spec from this incident: per-customer refusal-delta telemetry, candidate-version replay endpoint, impact-keyed notices.",
    frontier:
      "Model versions are behavioral contracts nobody wrote down: enterprises build against implicit behavior, updates move it, and the seam needs machinery — diff previews, delta telemetry, bounded ramps, and refusals as designed states. The transferable read: every version escalation is a spec for the transition product, and the lab that builds it first owns enterprise trust at the boundary everyone else calls an ambush.",
  },
},

/* ============================================================ 075 */
{
  id: "075",
  title: "The Regression Your Evals Can't See",
  difficulty: "Medium",
  category: "Frontier-Lab Transfer",
  primaryLens: "Eval",
  secondaryLens: "Platform",
  archetype: "Builder",
  secondaryArchetype: "Sweeper",
  targetRoles: ["MSFT MAI Evals Eng", "Anthropic TPM Safeguards & Evals", "OpenAI Deployment Eng"],
  tags: ["regression", "triage", "distribution-gap", "customer-evals"],
  prompt:
    "The new model version cleared every internal eval — including the gates 073 migrated — with scores flat or better across the board. A week after release, a major coding-tools customer reports a 12% drop in their acceptance rate (users accepting the model's code suggestions), backed by a clean A/B: same traffic, old version 34% acceptance, new version 22%. Their eval is real and yours is green. The release owner's first response: 'their harness must be wrong.' The customer's first response: 'roll it back.' You own the triage. Neither response survives contact with you.",
  arc: {
    start: "Two contradicting instruments, both credible — and a reflexive dismissal racing a reflexive rollback.",
    mid: "Reproduce, then bisect the gap: their distribution, their harness, or a real capability seam your suite never sampled.",
    end: "The regression localized and dispositioned — and whatever your evals were blind to becomes a permanent suite.",
  },
  expected: {
    bottleneck: "The two instruments sample different worlds: internal evals measure curated distributions with your harness conventions; the customer measures their users' real acceptance behavior on their traffic — a green gate and a red A/B can both be right (016's offline-online gap, except this time you're the lab and their production IS the online), and until someone reproduces the delta under controlled conditions, both 'their harness is wrong' and 'roll it back' are confidence without localization.",
    failureMode: "The dismissal wins: the customer churns with a documented regression you called user error — and their eval was RIGHT, meaning a real capability seam ships unmeasured to every similar workload; or the rollback wins: fleet-wide reversion for what turns out to be one customer's harness artifact (prompt template interacting badly with the new version's formatting), punishing every other customer and teaching the org that any loud A/B can revoke a release (023's allocation-by-escalation, applied to versions).",
    nextMove: "Reproduce before adjudicating: (1) get their failing sample — actual prompts, both versions' outputs, acceptance labels — under whatever data agreement it takes (their A/B is your missing eval data); (2) bisect the delta into the three possible worlds — real capability regression on their distribution (new model genuinely worse at their code patterns: languages, framework versions, prompt structure), harness interaction (their templates/stop-tokens/parsing colliding with new-version conventions — behavior change, not capability change, 074's cousin), or acceptance-behavior shift (outputs changed style — longer, more cautious, differently formatted — and users accept less without correctness dropping; the metric moved, not the quality); (3) each world has a different owner — real regression routes to the model team with a distilled eval set (the seam becomes a permanent suite: 044's conversion rule for capability), harness interaction gets engineering support plus a platform lesson about convention stability (074's contract), acceptance-shift gets an honest conversation about what their metric measures (028's discipline, aimed at their instrument); (4) interim relief that isn't rollback — pin THIS customer to the old version, bounded (074's ramp), while the triage runs; fleet stays forward; (5) close the meta-gap regardless of outcome — a top customer's production A/B contradicted a green gate, which means your suite's coverage of real coding-workload distributions has a hole (017's coverage question, forced by external evidence): their traffic becomes a sampled eval, permanently.",
    metric: "The bisection verdict with reproduced evidence (which world, what magnitude, whose owner) — plus the standing fix: coverage delta between internal suites and top-customer workload distributions, which this incident just measured at ≥12% blind.",
    owner: "You own the triage protocol and the customer's bounded pin; the model team owns world-one fixes with the distilled suite; platform engineering owns world-two conventions; the customer owns world-three metric introspection (with your data); the eval org owns the permanent coverage fix — their distribution enters the gate.",
    falsifier: "If reproduction on their sample shows no delta under controlled conditions — old and new versions perform identically when THEIR harness variables are held fixed — then the regression lives in their measurement stack (a template change shipped the same week, an A/B bucketing bug), the finding is delivered with 042's no-villain discipline (their eval caught something real about their stack, just not about your model), and the lab's suite coverage was never the issue.",
  },
  modelAnswer:
    "Hold both instruments as credible until reproduction says otherwise — that's the whole discipline. Your gates cleared because they measure what they measure: curated distributions, your harness, your judges (073 just taught you how load-bearing those conventions are). Their A/B measures their users accepting their suggestions on their traffic. A 12-point delta between those worlds has exactly three explanations, and everything before reproduction is reflex.\n\nGet their failing sample — prompts, paired outputs, acceptance labels. This is the step both reflexes skip: 'their harness is wrong' hasn't looked, and 'roll it back' hasn't localized. Then bisect. World one: real capability regression on their distribution — their code patterns (language mix, framework versions, prompt structures) sit in a seam your suite never sampled; the new model is genuinely worse there. If so, their A/B just did your eval org a favor no internal process could: distill the seam into a permanent suite, route to the model team, and thank them in writing. World two: harness interaction — the new version's output conventions (formatting, stop behavior, preamble) collide with their templates and parsers; capability didn't drop, the integration contract shifted silently (074's behavioral-contract problem in miniature). Engineering support fixes them this week; the platform lesson about convention stability is the durable part. World three: acceptance shift — outputs got longer, more hedged, differently styled; users accept less though correctness held. Then their metric measured style preference, and the honest conversation is 028's: what does acceptance mean, and is it the number their product should optimize?\n\nInterim: pin this customer to the old version, bounded with dates — the fleet stays forward, the loudest A/B doesn't govern releases, and the pin's boundedness is what keeps 021's precedent math survivable. And bank the meta-finding regardless of which world wins: a production A/B contradicted a green gate, which measures your coverage hole at twelve points. Their traffic distribution enters the internal suite permanently — the incident's real product is the eval you were missing (017's refresh, triggered by the market instead of the calendar).",
  rubric: {
    diagnosis: "Treats both instruments as credible pending reproduction and names the three worlds — capability seam, harness interaction, metric shift.",
    move: "Sample-based bisection with per-world owners, bounded customer pin instead of fleet rollback, and the seam converted to permanent suite coverage.",
    measurement: "Reproduced bisection verdict plus the standing coverage-delta fix; falsifier locates the regression in their measurement stack with no-villain delivery.",
    synthesis: "Sees the customer's A/B as free eval infrastructure and the incident as a coverage measurement — external evidence forcing 017's refresh.",
    altitude: "The release owner hears process instead of dismissal; the customer hears triage with relief dates instead of a credibility fight.",
    transfer: "Green-gate-red-customer is the applied-evals seam at every lab — bisection protocol, bounded pins, and customer-distribution suites are the standing machinery it demands.",
  },
  adversarial:
    "The tribal failure: defending the gate because it's yours — 073 just spent a quarter proving your instruments have quirks teams tune against; the customer's instrument deserves the same skeptical respect as your own, which is to say: reproduction, not faith, in either direction. The appeasement failure: rolling back the fleet on one A/B — you've taught every large customer that escalation velocity beats evidence, and the next 'regression' report arrives before their reproduction does. The closure miss: dispositioning this incident without adding their distribution to the suite — the coverage hole stays open, the next version ships through the same blind spot, and this exact meeting recurs quarterly with compounding trust damage.",
  recursiveFollowup:
    "Bisection lands on world one: a real seam — the new version regressed on their dominant framework's idioms, which your suite never sampled. The model team's honest answer: the fix rides the NEXT version, three months out, and the seam affects an unknown number of quieter customers. Now the disclosure question (015's shape, platform-scale): do you proactively tell similar-workload customers about a regression most haven't noticed, and what does the answer do to gate credibility either way?",
  altitude: {
    exec:
      "Their eval is real and so is ours — they measure different worlds, and the 12 points live in the gap. We're reproducing on their actual sample: either the model regressed on their code patterns (we fix it and their distribution joins our gates permanently), their integration collided with new output conventions (we fix them this week), or their acceptance metric moved for style reasons (a different conversation). They get a bounded pin meanwhile — the fleet doesn't roll back on one A/B, and no one gets dismissed without reproduction.",
    engineer:
      "Acquire the paired sample under data agreement: prompts, both outputs, acceptance labels. Controlled repro: hold their harness variables fixed, diff capability; then hold model fixed, diff harness conventions (templates, stop tokens, parsing). Style-delta analysis for world three (length, hedging, formatting vs correctness). Distill whichever seam is real into a permanent suite with their distribution's fingerprint.",
    frontier:
      "The green-gate/red-customer collision is applied evals' defining moment: internal suites sample curated worlds, production samples the real one, and the delta is always one of three things — capability seam, contract shift, or metric drift. The transferable protocol: reproduce before adjudicating, pin bounded instead of rolling back, and convert every confirmed seam into permanent coverage. Customer A/Bs are eval infrastructure you didn't have to build.",
  },
},

);
