/* Parabolic 100 — problem bank, part 15 (category closers, 081–085) */

P100.PROBLEMS.push(

/* ============================================================ 081 */
{
  id: "081",
  title: "The Context Window Is Full",
  difficulty: "Medium",
  category: "Agent Architecture",
  primaryLens: "Architecture",
  secondaryLens: "Eval",
  archetype: "Builder",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "OpenAI FDE", "MSFT MAI Evals Eng"],
  tags: ["context-management", "compaction", "long-sessions", "memory"],
  prompt:
    "A customer's claims-processing agent handles long investigations — sessions spanning hours, dozens of documents, hundreds of tool calls. Deep into big cases, quality visibly degrades: the agent 'forgets' constraints established early (a policy exclusion noted in hour one, violated in hour three), re-retrieves documents it already analyzed, and contradicts its own earlier findings. The team's diagnosis: 'we need a bigger context window.' The next model tier offers one — at 4x the cost, and their own testing shows quality STILL degrades on the longest cases, just later. Solve the actual problem.",
  arc: {
    start: "Long sessions rotting from the middle — and a bigger-window fix that just moves the cliff.",
    mid: "Engineer the context as a working set: pin the load-bearing facts, compact the history, index the rest.",
    end: "Sessions that end sharper than they started — with context curated by design, not accumulated by default.",
  },
  expected: {
    bottleneck: "Context is being treated as an append-only log when it's a working set: everything ever seen accumulates until the window fills, so the load-bearing items (case constraints, established findings) drown in transcript sediment — and attention degrades over long contexts well before hard limits, which is why the bigger window just relocates the cliff (the team is buying square footage for a filing problem).",
    failureMode: "Ship the 4x window: costs quadruple (038's bill, self-inflicted), the longest cases still degrade (their own testing already said so), and the middle cases — which fit fine before — now carry 4x cost for zero quality gain; meanwhile the actual failure class (constraints established early, violated late) persists at every window size because it was never a capacity problem.",
    nextMove: "Engineer the context as a managed working set: (1) separate state from transcript — case-critical facts (policy exclusions, established findings, decisions made) get promoted to a pinned, structured case-state block that survives every compaction (036's typed memory, at session scale); (2) compact on the way, not at the cliff — completed investigation threads summarize into findings ('reviewed docs 4–9: no prior claims; full analysis retrievable') with pointers back, so re-derivation becomes lookup; (3) make re-retrieval cheap and deduped — an already-analyzed index the agent checks before re-reading (the re-retrieval symptom is the agent compensating for its own lost state); (4) verify against the failure class, not vibes — build the eval from the incident: long-case golden traces where early constraints must survive to late decisions (076's constraint-survival metric, longitudinal), and measure quality BY session depth, which their 'still degrades, just later' testing already almost built; (5) THEN price windows honestly — with curation, the standard window may carry most cases; the 4x tier becomes a routing decision for the genuinely huge ones (039's tiering by task class), not the fleet default.",
    metric: "Constraint-survival across session depth (the hour-one exclusion honored at hour three — the failure that started this) and quality-by-depth curves before/after curation; plus cost per completed case, which curation should DROP while the bigger-window plan quadrupled it.",
    owner: "The agent team owns the state/compaction design; the eval owner builds the depth-indexed suite; you own killing the bigger-window default with their own test data and re-scoping the tier upgrade to routed exceptions.",
    falsifier: "If depth-indexed evals show quality degrading even with a curated working set well under the window limit — constraints pinned, sediment compacted, and hour-three still contradicts hour-one — then the failure is model reasoning over long horizons, not context management: the bigger window was never the fix, but neither is curation, and the honest answer is task decomposition (shorter sessions with explicit state handoffs — 076's contracts between session segments).",
  },
  modelAnswer:
    "Their own test already falsified their fix: quality degrades on the longest cases at the bigger window too — 'just later.' That's the signature of the actual problem: context is an append-only transcript, and the load-bearing facts are drowning in sediment. Attention over long contexts degrades before limits do; a window is square footage, and they have a filing problem. Buying 4x the floor space moves the cliff and quadruples the bill (038 would like a word), while the failure class — hour-one constraint, hour-three violation — survives at every size.\n\nEngineer the working set. First, state versus transcript: a claims investigation has perhaps a dozen facts that must never be lost — policy exclusions, established findings, decisions taken. Promote them to a pinned, structured case-state block that survives every compaction and sits where attention actually lands. This is 036's typed-memory discipline applied inside a session: the difference between remembering everything and remembering what matters, again. Second, compact continuously, not at the cliff: a completed thread ('reviewed documents 4 through 9 for prior claims — none found') becomes a finding with a pointer, not six documents of residue; the full analysis stays retrievable, the context carries the conclusion. Third, dedupe retrieval: the agent re-reading documents it already analyzed is the tell — it's compensating for lost state by re-deriving it, at token cost and contradiction risk; an analyzed-index lookup beats re-analysis.\n\nVerify against the incident, not vibes: depth-indexed evals where early constraints must survive to late decisions — 076's constraint-survival metric run longitudinally through a session. Then, and only then, the window conversation gets honest: with curation, most cases fit the standard tier, and the 4x window becomes 039's routing decision for the genuinely enormous ones. And hold the falsifier seriously — if curated context still rots with depth, the limit is model reasoning over long horizons, and the answer is decomposition: shorter sessions with explicit state handoffs, which is 076's contract discipline applied to time instead of agents. Either way, the fix was never square footage.",
  rubric: {
    diagnosis: "Names append-only context as the failure and reads 'degrades later at 4x' as falsifying the bigger-window theory.",
    move: "Pinned case-state, continuous compaction with pointers, retrieval dedup, depth-indexed evals, windows re-scoped to routed exceptions.",
    measurement: "Constraint-survival by depth and cost-per-case; falsifier redirects to session decomposition if curated context still rots.",
    synthesis: "Connects 036's memory typing, 038's cost discipline, and 076's survival metric into one session-scale design — curation as the unifying move.",
    altitude: "The team keeps a window upgrade where routing earns it, and loses it as the fleet default their own data disproved.",
    transfer: "Context engineering for long-horizon agents is the live frontier problem — working-set curation, compaction, and depth-indexed evals are the emerging craft at every lab.",
  },
  adversarial:
    "The capacity reflex: 'bigger window' is this domain's 'add more RAM' — occasionally right, usually a way to avoid designing the working set; their own testing already showed the cliff moves rather than vanishes, and ignoring your own falsifying data is 027's watermelon pointed inward. The summarize-everything failure: compacting the case-state facts along with the sediment — a lossy summary of the policy exclusion is how 'constraint violated at hour three' becomes 'constraint garbled at hour two'; the pin exists because some facts must survive verbatim. The eval skip: shipping curation without the depth-indexed suite — you'll declare victory on medium cases while the longest ones still rot, which is the original complaint with better vibes.",
  recursiveFollowup:
    "Curation ships; constraint survival hits 96% and costs drop 40%. Then an auditor asks a question the design didn't anticipate: 'Show me everything the agent considered and discarded in this denied claim' — and the compaction pointers reveal that two summarized threads can't fully reconstruct the discarded alternatives (077's flight recorder meets the compactor: you traced decisions but compacted deliberation). Reconcile compaction economics with audit reconstructability — what must survive verbatim, for whom?",
  altitude: {
    exec:
      "Your team's own test proved the expensive fix wrong: quality still degrades at four times the cost, just later. The real problem is filing, not floor space — critical case facts drown in transcript. We're pinning what must survive, summarizing what's settled, and measuring quality by session depth. Costs drop, the hour-one exclusion holds at hour three, and the premium window becomes a routed exception for monster cases, not the default bill.",
    engineer:
      "Case-state block: structured, pinned, versioned — exclusions, findings, decisions; survives all compaction. Continuous thread-level summarization with retrieval pointers; analyzed-document index checked before re-retrieval. Eval: depth-indexed golden traces asserting early-constraint survival at late decisions; quality-by-depth curves as the regression suite. Window tiering by case size via 039's router.",
    frontier:
      "Long-horizon agents live or die on context curation: working sets over transcripts, pinned state over hopeful attention, compaction with pointers over lossy amnesia. The transferable law — capacity moves the cliff, curation removes it — plus depth-indexed constraint-survival evals is where every lab's agent stack is converging.",
  },
},

/* ============================================================ 082 */
{
  id: "082",
  title: "Discovery as an Engine, Not an Event",
  difficulty: "Medium",
  category: "Scenario Discovery",
  primaryLens: "Customer",
  secondaryLens: "Platform",
  archetype: "Grower",
  secondaryArchetype: "Builder",
  targetRoles: ["CAPE SCPM", "OpenAI FDE", "OpenAI DPM (Codex)"],
  tags: ["discovery-engine", "telemetry", "demand-signals", "pipeline"],
  prompt:
    "Eighteen months into a customer's agent program: the first wave shipped (006's lighthouses), adoption is healthy, and the scenario pipeline is empty. The envisioning workshops that launched the program have gone stale — the same executives nominate the same ideas, the 43-item backlog from year one is picked over, and the program office is planning 'Workshop Series 2' to refill the funnel. Meanwhile: the deployed agents field 2,000 queries a day (including everything they fail at), support holds six months of categorized tickets (063's taxonomy, running), and 065's segmentation just mapped exactly which roles have no fit yet. The next fifty scenarios are already written down — nobody's reading them. Build the engine.",
  arc: {
    start: "An empty pipeline, a stale workshop ritual, and three telemetry streams full of unread demand.",
    mid: "Convert exhaust into intake: failed queries, ticket clusters, and no-fit segments become the standing scenario source.",
    end: "A discovery engine that refills the pipeline monthly from evidence — with workshops demoted to validation.",
  },
  expected: {
    bottleneck: "Discovery is still event-shaped (workshops, nominations, executive brainstorms) when the program now generates continuous demand telemetry: every failed agent query is a user asking for a capability that doesn't exist, every ticket cluster is a workflow in pain, every no-fit segment is an unserved population — the richest scenario source is the deployed base's own exhaust, and the program is planning another séance instead of reading the instruments.",
    failureMode: "Workshop Series 2 runs: the same execs re-nominate visibility projects (006's bias, unchanged), the pipeline refills with applause-ranked ideas disconnected from measured demand, wave two ships into weaker pull than wave one — and the program's growth rate becomes a function of meeting charisma instead of deployment evidence, which is to say it decays (year-one workshops worked because there was no telemetry; running them now is choosing anecdote over instrumentation).",
    nextMove: "Stand up the engine with three intake streams and one triage: (1) failed-query mining — cluster the agents' unanswerable and out-of-scope queries monthly (the users are typing the roadmap into the prompt box: 'can you also do X' at volume IS the demand signal, pre-quantified); (2) ticket-cluster promotion — 063's capability-gap lane already routes 'it can't do X' to product; aggregate it quarterly into scenario candidates with frequency and role data attached; (3) no-fit conversion — 065's unserved segments each get one targeted question ('what would have to exist for this role?'), answered by observation of their top workflows, not workshops; (4) triage through the existing gate — candidates carry evidence (query volume, ticket frequency, affected population) into 006's value × readiness scoring, which now runs on measured demand instead of executive votes; (5) demote workshops to their remaining honest job — validating and shaping candidates the telemetry surfaced, and executive sponsorship theater (051's mandate maintenance), twice a year, not as the source.",
    metric: "Pipeline refill rate from telemetry (candidates/month with evidence attached) versus workshop-sourced, and — the quality proof — wave-two scenarios' time-to-adoption versus wave one's: evidence-sourced scenarios should adopt faster because the demand was measured before anything was built.",
    owner: "The program office owns the monthly mining cadence (their job upgrades from workshop logistics to demand analysis); 063's quality desk owns the ticket stream; agents' owners own failed-query exports; the executive council keeps scenario APPROVAL (their altitude) and loses scenario INVENTION (never their comparative advantage).",
    falsifier: "If the exhaust streams run dry — failed queries are mostly noise, tickets cluster on quality not gaps, and no-fit segments genuinely have no agent-shaped work — then the deployed surface has saturated its adjacent possible, the next scenarios require capabilities that don't exist yet (a platform-roadmap conversation, 020), and workshops with NEW populations (frontline, not executives) are honestly the better instrument for finding non-adjacent demand.",
  },
  modelAnswer:
    "The program is about to run a séance in a room full of instruments. Workshops were the right tool at year zero — no deployment, no telemetry, so you asked people to imagine demand (006 managed the bias). Eighteen months later, demand writes itself into your systems daily: 2,000 queries include every 'can you also…' the agents can't serve; six months of 063's taxonomy has already categorized the capability gaps; 065 literally mapped which populations have nothing. The next fifty scenarios exist as data. Planning Workshop Series 2 is choosing to re-interview executives about what users have already typed.\n\nBuild the engine as three intakes and a triage. Failed-query mining: cluster the unanswerable monthly — frequency-ranked, role-tagged; a hundred users asking for contract-renewal lookups is a scenario with its business case pre-attached (compare: an executive nominating it would need 055's pilot to learn what the query logs already prove). Ticket promotion: the capability-gap lane aggregates quarterly into candidates carrying frequency and affected-role evidence. No-fit conversion: 065's unserved segments get observed — their top workflows shadowed for a day — because the roles with no fit can't type their demand into agents they don't use. All three streams feed 006's existing gate, which quietly transforms: value × readiness scoring now runs on measured demand, and the executive council's role clarifies to what it always should have been — approving and sponsoring (051's altitude), not inventing (never their edge).\n\nWorkshops survive with honest, smaller jobs: validating telemetry-surfaced candidates with the humans behind the data, and semi-annual sponsorship renewal. The proof metric is wave-two's time-to-adoption versus wave one's — evidence-sourced scenarios should land faster because the pull was measured before the build. And watch the falsifier: if the exhaust runs dry, the deployed surface has saturated its adjacent possible — that's not an engine failure, it's 020's signal that the next demand needs platform capabilities that don't exist yet, and a genuinely different discovery instrument (frontline populations, not executive re-runs). The discipline underneath: discovery matures from asking people what they want to reading what they already do — the program earned that telemetry; the engine is just the decision to believe it.",
  rubric: {
    diagnosis: "Names event-shaped discovery outliving its era and identifies the three exhaust streams as the pre-written pipeline.",
    move: "Monthly mining, ticket promotion, no-fit observation — all feeding the existing gate — with workshops demoted to validation and sponsorship.",
    measurement: "Telemetry-sourced refill rate and wave-two adoption velocity as the engine's proof; falsifier detects adjacent-possible saturation honestly.",
    synthesis: "Sees the council's role clarify (approve, don't invent) and discovery mature from interrogation to instrumentation — the program reading itself.",
    altitude: "The program office hears a job upgrade, executives keep sponsorship dignity, and 'Workshop Series 2' dies without a funeral.",
    transfer: "Discovery-as-engine is the deployed-product growth loop: mining usage exhaust for roadmap is exactly how mature platforms and labs source what to build next.",
  },
  adversarial:
    "The ritual failure: running Workshop Series 2 anyway 'for alignment' — it will produce candidates, they'll carry executive sponsorship, and they'll compete against telemetry-sourced scenarios with better politics and worse evidence; you've built the engine a rival instead of a funnel. The automation overreach: piping query clusters straight into the build queue — telemetry surfaces demand, it doesn't validate feasibility or stakes (a thousand users asking the HR agent for salary comparisons is a signal AND a 060 red line); the gate stays, evidence just replaces applause at its intake. The dry-well denial: forcing weak clusters into scenario candidates when the exhaust thins — engine worship is workshop worship with better dashboards; the falsifier exists because saturation is real and its answer is platform capability, not louder mining.",
  recursiveFollowup:
    "The engine runs three cycles; wave two ships faster and adopts faster. Then the mining surfaces its first political landmine: the single largest failed-query cluster — by 3x — is employees asking agents questions about reorganizations, leadership changes, and layoff rumors. The demand is real, measured, and enormous; the scenario is a minefield (015's stakes, 060's territory). The engine has no opinion; the program must. Decide what the discovery engine owes leadership when the loudest measured demand is the one nobody commissioned.",
  altitude: {
    exec:
      "Your users have already written the next roadmap — two thousand queries a day include everything the agents can't do yet, support has six months of categorized gaps, and we know exactly which roles have nothing. We're replacing brainstorm season with a monthly read of that evidence: your council still approves and sponsors every scenario, but invention comes from measured demand now. The proof will be wave two adopting faster than wave one — pull that was verified before we built.",
    engineer:
      "Intake plumbing: failed/out-of-scope query export with clustering and role tags, monthly; capability-gap ticket aggregation with frequency, quarterly; no-fit segment observation protocol. Candidates enter the 006 gate carrying volume, frequency, and population evidence. Dashboard: pipeline depth by source, evidence strength per candidate, wave-over-wave adoption velocity.",
    frontier:
      "Mature discovery is exhaust-reading: failed queries, support taxonomies, and unserved segments are demand pre-quantified, and workshops decay into validation instruments once telemetry exists. The transferable arc — from asking people what they want to instrumenting what they do — is how every deployed platform sources its roadmap, and the discipline is keeping a human gate between the signal and the build.",
  },
},

/* ============================================================ 083 */
{
  id: "083",
  title: "The Half-Finished Transaction",
  difficulty: "Hard",
  category: "Enterprise Integration",
  primaryLens: "Architecture",
  secondaryLens: "Deployment",
  archetype: "Builder",
  secondaryArchetype: "Maintainer",
  targetRoles: ["CAPE SCPM", "OpenAI Deployment Eng", "Anthropic TPM API Platform"],
  tags: ["transactions", "sagas", "compensation", "multi-system-writes"],
  prompt:
    "A customer's employee-onboarding agent (010's ladder, rung two) orchestrates writes across four systems: creates the HR record, provisions the identity, assigns licenses, and files the equipment order. Last Tuesday it failed mid-sequence on 30 new hires — HR records created, identities provisioned, then the license API returned 500s and the agent simply… stopped. No licenses, no equipment, no alert (078's silent swallow, on the write path). IT spent two days finding and hand-finishing the stragglers, and three hires showed up to no laptop. The team's fix proposal: 'wrap it in retries.' The sequence has no transactions, no compensation, no ledger of what completed. Retries won't save it. Design the write orchestration.",
  arc: {
    start: "Four systems, no transaction semantics, and thirty onboardings abandoned mid-flight in silence.",
    mid: "Design for partial failure as the normal case: a durable step ledger, idempotent retries, compensation paths, and loud stalls.",
    end: "Every multi-system write either completes, cleanly unwinds, or escalates with its exact state — nothing half-finished and quiet.",
  },
  expected: {
    bottleneck: "The orchestration assumes the happy path across four systems that can each fail independently: there's no durable record of which steps completed per hire (the ledger), no idempotency (retrying risks double-provisioning), no compensation design (what unwinds a provisioned identity when licensing fails permanently?), and no stall alarm — so partial failure, which is the NORMAL case in multi-system writes, lands as silent abandonment discovered by humans (three of them at a reception desk, without laptops).",
    failureMode: "'Wrap it in retries' ships: transient failures improve, but retries without idempotency double-create records on ambiguous timeouts (did the license call succeed before the 500?), permanent failures (a malformed cost center) retry forever into 038's bill, and the fundamental gap — no ledger, no compensation, no alarm — waits for the next partial failure, which arrives as 30 half-onboarded hires again, now with duplicate identities sprinkled in.",
    nextMove: "Build saga-style orchestration sized for enterprise reality: (1) the step ledger — durable state per hire per step (pending / succeeded / failed / compensated), written before and after every external call; the ledger IS the recovery tool (Tuesday's two-day hunt becomes a query — 077's flight recorder for writes); (2) idempotency everywhere — every write carries an idempotency key (hire ID + step), and every step handler checks-before-creates, so retries are safe and ambiguous timeouts resolve by lookup, not hope; (3) classified retries — transient (500s, timeouts: bounded retry with backoff), permanent (validation errors: no retry, route to humans with the exact failure), and ambiguous (verify via read, then decide); (4) compensation defined per step at design time — licensing failed permanently → decide explicitly: unwind identity + HR record, or hold-and-escalate with partial state visible (for onboarding, hold-and-escalate usually wins — a half-onboarded hire is recoverable; a deleted HR record on day one is a new incident); (5) stalls are loud — any hire in a non-terminal state past SLA pages the queue owner with the ledger row (078's no-silent-swallow, enforced by design); (6) the daily reconciliation sweep — ledger vs reality across all four systems, because even good orchestration drifts and the sweep catches what the happy path missed.",
    metric: "Non-terminal-state age (no hire sits partial past the SLA without a human holding it — the reception-desk number) and manual-completion rate trending to zero; plus duplicate-write incidents, the idempotency proof.",
    owner: "The agent team owns the ledger and step handlers; each system's owner signs the idempotency contract and compensation semantics for their API (some systems can't cleanly delete — that constraint shapes the compensation design, and it's theirs to state); IT ops owns the stall queue with the ledger as their console; you own making 'retries' die as the answer.",
    falsifier: "If failure analysis shows Tuesday was the first partial failure in a year and the license API's 500s were a one-off outage, the full saga build may be over-engineering for the actual rate — the honest minimum is the ledger + loud stalls + idempotency keys (cheap, and they convert any future failure from archaeology to queue-work), with compensation machinery deferred until the failure rate earns it.",
  },
  modelAnswer:
    "Name the category error first: this isn't a reliability bug, it's a missing architecture. Four independent systems means partial failure is the normal case — the design question was never 'how do we avoid failing mid-sequence' but 'what is true when we do,' and Tuesday's answer was: nothing is true; nobody knows; three people find out at a reception desk. 'Wrap it in retries' answers the transient sliver and makes the rest worse: retrying a maybe-completed license call without idempotency is how 30 half-onboardings gain duplicate identities.\n\nThe architecture is a saga with enterprise manners. The step ledger is the foundation — durable state per hire per step, written around every external call. It converts every future incident from a two-day forensic hunt into a query ('show me non-terminal hires'), and it's the console the stall queue runs on. Idempotency makes retries safe: keys on every write, check-before-create in every handler, and ambiguous timeouts resolved by reading reality instead of guessing. Retries get classified — transient backs off and retries bounded; permanent (the malformed cost center) never retries: it routes to a human with the exact failure attached; ambiguous verifies first. Compensation is a design-time decision per step, and here enterprise reality beats textbook sagas: unwinding a provisioned identity because licensing hiccuped is often worse than holding — for onboarding, hold-and-escalate-with-visible-state is usually the right compensation, because a half-onboarded hire is a queue item while a deleted day-one HR record is an incident. What matters is that the decision was MADE, per step, before the failure.\n\nLoudness is non-negotiable (078's law on the write path): any hire in a non-terminal state past SLA pages with its ledger row. And the daily reconciliation sweep — ledger versus the four systems' reality — catches the drift that even good orchestration accumulates. Run the falsifier honestly: if Tuesday was a once-a-year event, ship the cheap 80% (ledger, keys, loud stalls) and let the failure rate earn the compensation machinery. But the ledger is never optional — the difference between 'the agent stopped' and 'these six hires are at step three, held, humans notified' is the difference between an incident and a Tuesday.",
  rubric: {
    diagnosis: "Reframes partial failure as the normal case and names the four missing pieces — ledger, idempotency, compensation, alarms — that retries can't supply.",
    move: "Saga orchestration with durable step state, classified retries, per-step compensation decided at design time (hold-vs-unwind reasoned), loud stalls, reconciliation sweep.",
    measurement: "Non-terminal-state age and duplicate-write incidents as the proofs; falsifier ships the cheap core and defers compensation machinery until the rate earns it.",
    synthesis: "Sees that enterprise compensation often means hold-and-escalate, not unwind — textbook sagas adjusted for systems where delete is worse than partial.",
    altitude: "IT hears their two-day hunt become a query; the team hears why retries alone would have added duplicates to the next Tuesday.",
    transfer: "Multi-system write orchestration is where enterprise agents earn production trust — ledgers, idempotency contracts, and compensation semantics are the API-platform conversation behind every 'agent that acts.'",
  },
  adversarial:
    "The retry seduction: it demos well (transient failures vanish in testing) and it's the half-fix that blocks the whole one — once 'we added retries' closes the incident, the ledger and compensation work loses its sponsor until the next 30-hire Tuesday. The distributed-systems cosplay failure: proposing two-phase commit across HR, identity, licensing, and procurement SaaS APIs — none of them speak it; sagas exist precisely because enterprise systems don't do distributed transactions, and demanding textbook atomicity is how the design meeting dies. The unwind absolutism: compensating every failure with full rollback — deleting an HR record because a license API had a bad hour creates day-one incidents out of recoverable stalls; compensation is a per-step judgment about which direction of wrongness is cheaper.",
  recursiveFollowup:
    "The saga ships. Six weeks in, the reconciliation sweep surfaces a new class: eleven hires show ledger-complete but reality-divergent — the equipment system accepted the order (200 OK, ledger: succeeded) then silently dropped it downstream in THEIR queue. Your orchestration was honest; the fourth system lied. The ledger can't see past a dishonest 200. Design the verification layer — and decide how far downstream your agent's responsibility for reality extends (076's contract question, aimed at systems you don't own).",
  altitude: {
    exec:
      "Tuesday wasn't bad luck — the design assumed four systems never fail mid-sequence, so when one did, thirty onboardings just stopped, silently. The fix isn't retries: it's a ledger of exactly what completed for whom, safe re-runs that can't double-create, a decided answer for every failure type, and alarms before a hire reaches a desk without a laptop. Partial failure becomes a queue with an owner instead of a surprise with a victim.",
    engineer:
      "Durable step ledger (hire × step × state) written around every call; idempotency keys with check-before-create handlers; retry classes — transient/backoff-bounded, permanent/route-to-human, ambiguous/verify-then-decide; per-step compensation semantics signed by each system owner (hold-and-escalate default for onboarding); stall SLA paging on non-terminal age; daily ledger-vs-reality reconciliation across all four systems.",
    frontier:
      "Agents that write across systems inherit distributed systems' oldest truth: partial failure is the steady state. The transferable architecture — durable ledgers, idempotent steps, classified retries, compensation as design-time judgment, loud stalls — is what separates agents that act in production from agents that act in demos. Every 'agentic workflow' pitch is this problem, waiting.",
  },
},

/* ============================================================ 084 */
{
  id: "084",
  title: "The Agent Is DDoSing the CRM",
  difficulty: "Easy",
  category: "Enterprise Integration",
  primaryLens: "Architecture",
  secondaryLens: "Deployment",
  archetype: "Maintainer",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "OpenAI Deployment Eng", "Anthropic TPM API Platform"],
  tags: ["rate-limits", "backpressure", "citizenship", "load"],
  prompt:
    "Monday morning, the CRM team's dashboard lights up: API calls are 8x baseline and their instance is throttling for everyone — including the sales floor. The source: Friday's deal-desk agent update (079's job runner) added portfolio pre-analysis, and each seller's morning briefing now fans out 200+ CRM calls; 400 sellers at 8am equals a self-inflicted stampede. The CRM team's response is a firewall rule blocking the agent's service account entirely. Sales now has neither briefings nor a responsive CRM, two teams are in a blame thread, and the pattern generalizes: your agents are becoming the biggest API consumers in the enterprise, and nobody designed for it. Fix Monday, then fix the class.",
  arc: {
    start: "One feature ship turned the agent fleet into the enterprise's noisiest neighbor — and got it firewalled.",
    mid: "Restore service with manners: quotas, backpressure, caching, and off-peak shaping — citizenship as architecture.",
    end: "Agents that consume like tenants, not stampedes — with a load contract every new capability signs before it ships.",
  },
  expected: {
    bottleneck: "The agent fleet has no consumption discipline: no client-side rate limiting, no backpressure response (throttle signals were retried into — making it worse), no caching (400 briefings re-fetched the same account objects hundreds of times), and no load review before the feature shipped — agents multiply human request patterns by orders of magnitude, and the integration was designed as if the agent were one polite user instead of four hundred simultaneous ones.",
    failureMode: "The blame thread wins: the firewall stays, briefings die, and the precedent sets — every system owner learns that blocking agents is the only defense they have, so each new integration meets pre-emptive hostility (014's wall-building, justified this time); or the block lifts with apologies and no architecture, and next month a different agent capability stampedes a different system, because the class was never fixed.",
    nextMove: "Fix Monday with shaping, not apologies: (1) immediate — client-side rate limiting on the agent's CRM client (respect their published limits with headroom), exponential backoff that actually backs off on 429s, and the briefing fan-out batched and staggered (the 8am thundering herd becomes a 5–8am rolling window; briefings are 079's async jobs — nobody needs theirs at 8:00:00); (2) cheap wins — cache the shared reads (the same account hierarchies fetched 400 times), and batch the per-seller queries the CRM API supports natively (200 calls collapses to ~20); (3) the class fix — a consumption contract per integrated system: published quota the agent fleet stays under, backpressure semantics honored, identified traffic (040's per-agent identities double as load attribution — the CRM team fire walled ONE service account because that's all they could see), and off-peak scheduling as the default for bulk work; (4) load review joins the ship gate — any capability multiplying calls to enterprise systems gets a projected-load line in its 045 checklist (calls × users × time-concentration), reviewed with the target system's owner BEFORE ship; (5) repair the relationship structurally — the CRM team gets a dashboard of agent consumption by workload and a named contact, converting them from firewall-wielders to capacity partners (049's gateway logic: visibility is what replaces walls).",
    metric: "Agent-attributed load on shared systems vs contracted quota (per system, per workload — visible to BOTH teams), and peak-concentration ratio (the 8am spike flattened into the rolling window); plus time-to-detection for the next runaway — the CRM team paged you before their users noticed, or the class fix didn't take.",
    owner: "The agent platform team owns client discipline (limits, backoff, caching) and the load-review gate; each target system's owner co-signs their consumption contract and gets the attribution dashboard; you own converting the blame thread into the contract meeting.",
    falsifier: "If load analysis shows the CRM instance was already at 90% capacity from organic growth and the agent's 8x was the straw, not the stampede — then the agent is the visible scapegoat for an under-provisioned system, the consumption contract still helps, but the honest finding routes to CRM capacity planning, and letting the agent fleet absorb the blame buys one quiet quarter before the sales floor throttles again without any agent involved.",
  },
  modelAnswer:
    "Start with the physics the feature ship ignored: agents are demand multipliers. A human seller checks a few accounts over a morning; an agent pre-analyzes the whole portfolio at 8am sharp, and 400 agents do it simultaneously — the integration was designed for one polite user and deployed as a synchronized stampede. The CRM team's firewall is crude, but read it correctly: it's the only control they had, because the fleet gave them nothing better — no quota to hold you to, no backpressure you honored, no attribution beyond one service account to block.\n\nMonday's fix is shaping: client-side rate limiting under their published ceiling, backoff that genuinely backs off on 429s (retrying into throttle signals is how 8x became a blame thread), and the fan-out redesigned — briefings are async jobs (079 built the runner); stagger them across a 5–8am rolling window and nobody notices except the CRM's load graph. Then the cheap wins that make the number collapse: cache the shared reads (400 briefings fetching the same account hierarchy is a cache with extra steps), and use the CRM's native batch endpoints (200 calls per seller becomes 20).\n\nThe class fix is citizenship as architecture. Per integrated system: a consumption contract — quota with headroom, honored backpressure, off-peak defaults for bulk work, and attributed traffic (040's per-agent identities mean the CRM team can see WHICH workload is hot instead of firewalling the whole fleet). And the gate: any capability that multiplies calls to shared systems ships with a projected-load line — calls × users × time-concentration — reviewed with the target system's owner first (045's checklist grows a row; the 8am spike was predictable arithmetic nobody ran). Give the CRM team the dashboard and a named contact: systems owners who can SEE agent load become capacity partners; the ones who can't build firewalls, correctly. And hold the falsifier: if their instance was already at 90% from organic growth, the agent was the straw wearing a stampede costume — the contract still ships, but the capacity finding goes where it belongs, or the sales floor throttles again next quarter with no agent to blame.",
  rubric: {
    diagnosis: "Names the demand-multiplier physics and reads the firewall as the rational response to an unattributable, uncontracted consumer.",
    move: "Shape (limits, real backoff, staggered async, cache, batch), then contract the class — quotas, attribution, off-peak defaults, load review at the ship gate.",
    measurement: "Contracted-quota adherence and peak-concentration flattening, visible to both teams; falsifier routes the finding to CRM capacity if the agent was the straw.",
    synthesis: "Converts the blame thread into a visibility contract — 040's identities as load attribution, 049's insight that dashboards replace walls.",
    altitude: "The CRM team hears partnership with controls; sales hears briefings back by Wednesday, spread politely across the early morning.",
    transfer: "Agent fleets are becoming every enterprise's largest API consumers — consumption contracts, backpressure citizenship, and load-reviewed ship gates are the integration discipline the next five years demand.",
  },
  adversarial:
    "The apology-only failure: getting the firewall lifted with a hotfix and goodwill — the class is untouched, the next capability stampedes a different system, and the SECOND blame thread hardens into standing hostility toward the whole fleet (014's wall, now with receipts). The infrastructure reflex: 'the CRM should scale up' — sometimes true (see the falsifier), always the wrong opening move; demanding capacity from the system you just stampeded is how integration partners become enemies. The gate-skip: fixing this integration beautifully and leaving the ship process unchanged — the load review line is the whole class fix; without it you've patched one stampede and scheduled the rest.",
  recursiveFollowup:
    "The contracts work — until procurement's new agent legitimately needs 5x the ERP quota for quarter-close processing, the ERP owner refuses ('the contract is the contract'), and both sides cite YOUR framework. The consumption contract that ended the blame threads is now the bottleneck for a real business need. Design the exception path — burst quotas? negotiated windows? — without teaching every team that contracts bend under pressure (024's override discipline, applied to load).",
  altitude: {
    exec:
      "Friday's feature turned four hundred sellers' briefings into a synchronized eight-a.m. stampede on the CRM — their firewall was the only defense we left them. Briefings are back this week, spread across the early morning, cached and batched to a tenth of the calls. The real fix: every system we touch gets a consumption contract — quotas, off-peak defaults, and a dashboard showing them exactly what our agents consume. New capabilities project their load before they ship, not after the blame thread.",
    engineer:
      "Client: rate limiter under published CRM ceilings, exponential backoff honoring Retry-After, shared-read cache with TTLs, native batch endpoints. Scheduling: briefing jobs staggered over a rolling window via the async runner. Class: per-system consumption contracts, per-agent traffic attribution via service identities, load-projection line (calls × users × concentration) in the ship checklist, consumption dashboards shared with system owners.",
    frontier:
      "Agents multiply demand by orders of magnitude, and integration citizenship — honored backpressure, contracted quotas, attributed traffic, load-reviewed ships — is what keeps the fleet welcome on the enterprise's systems. The transferable law: systems owners who can see and cap your consumption become partners; the ones who can't will firewall you, and they'll be right.",
  },
},

/* ============================================================ 085 */
{
  id: "085",
  title: "Six Tenants, One Company",
  difficulty: "Hard",
  category: "Enterprise Integration",
  primaryLens: "Architecture",
  secondaryLens: "Platform",
  archetype: "Builder",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "Anthropic TPM Apps Platform", "MSFT MAI Strategy & Ops"],
  tags: ["multi-tenant", "topology", "m&a", "cross-tenant"],
  prompt:
    "A holding company runs six subsidiary tenants — three from acquisitions still on their own domains, one joint venture with a co-owner, and two wholly-owned. The group CFO wants 'one AI layer across the group': agents that answer using any subsidiary's data ('group-wide contract search, consolidated vendor spend'). Each subsidiary's IT guards its tenant fiercely — the JV contractually MUST stay separated, one acquisition is being divested next year, and 020's cross-tenant platform gap is still three quarters from GA. The integrator proposes 'just centralize everything into the parent tenant.' Design the topology instead.",
  arc: {
    start: "One CFO's vision, six sovereign tenants, a JV firewall, a pending divestiture — and a bulldozer proposal.",
    mid: "Decompose 'one AI layer' by workload: what needs group reach, what must stay local, and what the JV can never touch.",
    end: "A federated topology that serves the group queries, respects the boundaries — and survives next year's divestiture untouched.",
  },
  expected: {
    bottleneck: "The ask conflates experience with topology: 'one AI layer' is being read as 'one tenant' when the CFO's actual need decomposes into a handful of group-level workloads (consolidated search, spend analytics) plus dozens of subsidiary-local ones — and the tenant boundaries aren't IT obstinance: the JV separation is contractual, the divestiture demands clean detachability, and acquired-entity isolation is what makes M&A reversible (the boundaries are the business structure, expressed as architecture).",
    failureMode: "Centralization proceeds: eighteen months of tenant migration hell (the CRM-swap scar at 6x scale), the JV's contractual separation gets violated by an over-eager index (a co-owner's lawyers discover their contracts in the parent's search — 057's incident with a litigation budget), and next year's divestiture requires surgically extracting an entity whose data is now marbled through a consolidated tenant — the 'simplification' becomes the group's most expensive IT project and its biggest legal exposure, simultaneously.",
    nextMove: "Federate by workload, not by bulldozer: (1) decompose the CFO's vision into workload classes — group-reach queries (contract search, vendor spend: a handful, high-value), subsidiary-local agents (most of the fleet: HR, support, ops — no cross-tenant need, leave them home), and JV-excluded everything (contractually walled); (2) build group reach as federation, not consolidation — a group-level agent that queries per-tenant indexes through 040's identity intersection (the asking user's group role determines which tenants' results merge), with each subsidiary's data remaining in its tenant under its controls; where the platform's cross-tenant gap bites (020's three-quarters-out GA), the interim is per-tenant agents with a thin aggregation layer — uglier, detachable, honest; (3) encode the business structure as topology rules — the JV tenant is excluded by architecture (not policy — its connector doesn't exist), the divesting entity's integration is tagged detachable-by-design (every group-layer touchpoint inventoried for clean severance — 046's flow map as a divestiture asset); (4) sequence by the CFO's actual value — consolidated vendor spend first (finance data, cleanest permissions, highest stated value), contract search second (heavier permission surface), and the long tail never (most agents never needed group reach); (5) govern the federation — 001's gate gains a topology question: 'which tenants does this agent reach, and why?'",
    metric: "Group-workload coverage (the CFO's named use cases live) against boundary integrity (zero JV data in group indexes — audited, 044-style; divestiture detachment cost as a tracked number, not a future surprise); plus migration avoided: the federated design's cost vs the centralization quote.",
    owner: "Group IT owns the federation layer and topology rules; each subsidiary IT keeps tenant sovereignty (their fierce guarding becomes the design's enforcement, not its enemy); legal signs the JV exclusion architecture and the divestiture detachability review; the CFO gets sequenced value with the boundaries explained in business terms — reversibility.",
    falsifier: "If workload analysis shows the group-reach class is actually large — the holding company operates as one integrated business and half the fleet genuinely needs cross-subsidiary data — then federation-per-query becomes the expensive path, the honest recommendation shifts toward real tenant consolidation for the wholly-owned entities (keeping JV and divestiture exclusions), and the integrator was half-right about the destination while still wrong about including the entities that can never merge.",
  },
  modelAnswer:
    "Translate the CFO's sentence before architecting it: 'one AI layer' is an experience requirement — ask group-level questions, get group-level answers. The integrator heard a topology requirement — one tenant — and those differ by about eighteen months of migration hell and one JV lawsuit. The tenant boundaries here aren't IT territorialism: the JV wall is a contract with a co-owner, the divesting entity needs clean severance next year, and acquisition isolation is what makes M&A reversible. The boundaries ARE the business structure. Centralizing through them doesn't simplify the structure; it laminates legal risk into an index.\n\nSo decompose by workload. The CFO's actual vision is a handful of group-reach queries — consolidated vendor spend, group contract search — sitting on top of a fleet that's overwhelmingly subsidiary-local (HR agents, support agents, ops agents that never needed to see across the wall, and shouldn't — 046's classification instinct, applied to tenancy). Build the group reach as federation: a group-level agent that fans queries to per-tenant indexes, merging results through 040's intersection — the asking user's group-role determines which tenants answer, each subsidiary's data stays home under its own controls, and the audit story writes itself. Where the platform's cross-tenant support lags (020's gap, three quarters out), the interim is honest ugliness: per-tenant agents behind a thin aggregation layer — worse UX, fully detachable, and it converts into the real federation when GA lands instead of fighting it.\n\nEncode the business structure as architecture, not policy: the JV's exclusion is a connector that doesn't exist (policies get exceptions; absent connectors don't), and the divesting entity's every group-layer touchpoint is inventoried detachable-by-design — 046's flow map, repurposed as a divestiture asset that will make next year's separation a checklist instead of a crisis. Sequence by stated value: vendor spend first (finance permissions are the cleanest), contract search second (permission-heavy — 012's lessons apply at group scale), the long tail never. And convert the subsidiary IT guards from enemies to enforcement: federation makes their sovereignty the design's foundation, which is why they'll defend it (054's authorship mechanism, at holding-company scale). The falsifier stays open — if workload analysis reveals the group truly operates as one business, consolidation of the wholly-owned entities becomes honest; but even then, the JV and the divestiture never merge, which means the integrator's 'everything' was always the wrong word.",
  rubric: {
    diagnosis: "Separates the experience requirement from the topology proposal and reads tenant boundaries as business structure — JV contract, divestiture, M&A reversibility.",
    move: "Workload-decomposed federation: group-reach via identity-intersected fan-out, local fleets stay home, exclusions as architecture, detachability inventoried, value-sequenced delivery.",
    measurement: "Group-workload coverage against audited boundary integrity and tracked detachment cost; falsifier shifts toward partial consolidation if group-reach dominates.",
    synthesis: "Repurposes 046's flow map as a divestiture asset and 054's authorship as subsidiary-IT conversion — the boundaries become the design's enforcement.",
    altitude: "The CFO hears sequenced value plus 'reversibility' in business terms; legal hears exclusion-by-architecture; the integrator's bulldozer dies of costed comparison.",
    transfer: "Multi-tenant topology under M&A dynamics is the enterprise reality every platform meets — federation vs consolidation, contractual walls, and detachable-by-design are the group-architecture questions 020's platform gap exists to answer.",
  },
  adversarial:
    "The bulldozer failure: centralizing because federation is complex — the complexity doesn't vanish, it converts into migration years, a JV breach surface, and a divestiture that requires un-marbling an index under deal pressure; 'simple' topologies that ignore business structure are deferred litigation. The sovereignty-worship failure: leaving everything federated forever including six copies of every agent — if the wholly-owned entities operate as one business, permanent federation taxes every group workload for boundaries no contract requires; the falsifier cuts both ways. The policy-wall miss: enforcing the JV exclusion by access policy instead of absent architecture — policies drift, get exceptioned (024), and are audited after the breach; a connector that doesn't exist cannot leak, and for contractual walls that difference is the whole design.",
  recursiveFollowup:
    "The federation ships; vendor spend consolidates beautifully. Then the divestiture completes — and the acquiring company requests 'the AI layer too': they want the subsidiary's agents, indexes, and eval sets (017's golden sets, 057's conversation logs included) transferred as part of the asset. The detachability design made severance clean; nobody designed for the data's ONWARD transfer to a new owner with different policies. Legal asks what conveys, what gets deleted, and what the employees' conversation logs owe to whom (057 meets M&A). Draw the lines.",
  altitude: {
    exec:
      "Your six tenants aren't IT stubbornness — they're your deal structure: a JV you contractually can't merge, a divestiture that needs clean severance next year, acquisitions still detachable. So we're not merging tenants; we're federating the queries. Group contract search and consolidated spend work this quarter, each subsidiary's data stays under its own controls, the JV is excluded by wiring rather than promises — and next year's divestiture is a checklist, not a surgery.",
    engineer:
      "Group agent with per-tenant index fan-out; result merge gated by requester's group-role × tenant permissions (040's intersection, federated). JV tenant: no connector, verified by 044-style boundary audits. Divesting entity: touchpoint inventory with severance runbook. Interim for the platform's cross-tenant gap: per-tenant agents + aggregation shim, designed to convert at GA. Topology question added to the agent gate.",
    frontier:
      "Holding-company topologies are where tenancy meets corporate structure: federation expresses boundaries that contracts require, consolidation expresses operations that business reality demands, and the design skill is decomposing 'one AI layer' into which workloads earn which answer. The transferable laws — exclusion by architecture over policy, detachability as a designed property, boundaries as enforcement allies — travel to every multi-entity enterprise, and every platform's cross-tenant roadmap.",
  },
},

);
