/* Parabolic 100 — problem bank, part 14 (Agent Architecture depth, 076–080) */

P100.PROBLEMS.push(

/* ============================================================ 076 */
{
  id: "076",
  title: "The Handoff Contract",
  difficulty: "Hard",
  category: "Agent Architecture",
  primaryLens: "Architecture",
  secondaryLens: "Eval",
  archetype: "Builder",
  secondaryArchetype: "Maintainer",
  targetRoles: ["CAPE SCPM", "OpenAI FDE", "Anthropic TPM Apps Platform"],
  tags: ["multi-agent", "handoffs", "contracts", "seams"],
  prompt:
    "A customer's order-exception workflow (011's minimal architecture, grown legitimately) now runs three agents in sequence: a classifier routes the exception, a resolver drafts the fix, a communicator writes the customer email. Individually each scores 90%+ on its evals. End-to-end, the workflow succeeds 68% of the time — and the failures are maddening: the resolver 'loses' constraints the classifier identified, the communicator confidently emails resolutions the resolver never made, and when ops investigates, each agent's logs show it doing its job correctly. The team wants to add a supervisor agent to 'check the others.' Fix the actual problem.",
  arc: {
    start: "Three good agents, one bad system — and the failures living where nobody's logs look.",
    mid: "Engineer the seams: typed handoff contracts, validated at the boundary, with lineage the workflow can audit.",
    end: "End-to-end success tracking component success — and seams that fail loudly instead of drifting silently.",
  },
  expected: {
    bottleneck: "The handoffs are unspecified: each agent consumes the previous one's prose output as context, so information survives transitions only probabilistically — constraints identified upstream evaporate, hallucinated state gets injected midstream, and per-agent evals can't see any of it because each agent performs correctly given what it received (the failure is the seam, and seams have no logs).",
    failureMode: "Add the supervisor agent: a fourth probabilistic component now reviews prose with prose, the seam count goes from two to six, end-to-end drops further while every individual eval stays green (027's watermelon assembled from honest parts, in silicon) — and the team learns 'multi-agent doesn't work' when what never worked was unstructured handoffs.",
    nextMove: "Contract the seams like 026 contracted the teams: (1) define typed handoff schemas — the classifier emits structured output (exception class, constraints found, confidence, source refs), the resolver consumes and must acknowledge each constraint (resolved / relaxed-with-reason / escalate), the communicator receives only validated resolution state; (2) validate at boundaries — schema checks catch format drift, and semantic checks (constraint-acknowledgment completeness) catch the silent drops; boundary failures are loud, logged, and routed (063's taxonomy), never absorbed; (3) carry lineage — every downstream claim links to upstream state, so 'the email promised a refund the resolver never made' becomes structurally impossible (the communicator can only reference resolution records that exist); (4) eval the seams, not just the agents — end-to-end golden traces with per-boundary assertions join the suite (016's production sampling at the workflow level); the supervisor idea dies because deterministic validation at the boundary beats probabilistic review of the whole.",
    metric: "End-to-end success reconciled against component success — the 22-point gap is the seam tax, and its burn-down is the project; plus constraint-survival rate across handoffs (what the classifier found that the resolver acknowledged), the single most diagnostic seam number.",
    owner: "The workflow team owns the schemas and boundary validators; each agent's owner conforms to the contract (their eval now includes contract compliance); the eval owner adds end-to-end traces with boundary assertions; ops gets seam-failure alerts instead of mystery investigations.",
    falsifier: "If traced failures show information surviving handoffs fine but the resolver genuinely making bad calls on complete information, the seams were innocent — the component eval was measuring the wrong thing (its golden set lacks the hard cases the classifier actually routes, 017's coverage gap per-agent), and the fix is component eval realism, not handoff engineering.",
  },
  modelAnswer:
    "Diagnose the arithmetic first: three components at 90% with clean seams compound to ~73% — they're at 68%, and component evals say 90%+ each. The gap between what the math predicts and what production delivers is the seam tax, and it's invisible by construction: each agent's logs show correct behavior given its inputs, because the failure IS the inputs. Prose handoffs mean every transition is a lossy, unvalidated deserialization performed by a language model — constraints survive if the next agent happens to attend to them. That's not a workflow; it's three agents playing telephone.\n\nThe supervisor proposal reads the failure backwards: it adds a fourth probabilistic component to review prose with prose, doubling the seams to fix the seams. The actual fix is boring and total — engineer the handoffs like the interfaces they are. Typed schemas: the classifier emits structure (exception class, constraints with sources, confidence), not narrative. Acknowledgment semantics: the resolver must disposition every constraint — resolved, relaxed-with-reason, or escalate — so silent drops become schema violations, which is to say: loud. Lineage: the communicator can only reference resolution records that structurally exist; 'confidently emailing a resolution nobody made' stops being a behavior and becomes a type error. Boundary validation is deterministic code, not model judgment — the one place in an agent system where you get to use 009's reliability physics, use it.\n\nThen eval what you built: end-to-end golden traces with per-boundary assertions, because the component evals just demonstrated their blind spot — three green agents, one red system (075's lesson, intramural edition). Constraint-survival rate across handoffs becomes the workflow's vital sign. And keep 011's discipline in your pocket: if after contracting the seams the resolver still fails on complete information, THEN you have a component problem — and now, for the first time, the logs can prove it.",
  rubric: {
    diagnosis: "Locates the failure in unspecified prose handoffs — the seam tax invisible to component evals — with the compounding arithmetic done.",
    move: "Typed contracts with acknowledgment semantics, deterministic boundary validation, lineage that makes hallucinated state impossible, seam-level evals.",
    measurement: "End-to-end vs component reconciliation and constraint-survival rate; falsifier redirects to component-eval realism if seams prove innocent.",
    synthesis: "Kills the supervisor with its own logic — probabilistic review of prose adds seams — and applies 026's commitment discipline to machine boundaries.",
    altitude: "Ops hears 'seams fail loudly now' instead of mystery investigations; the team keeps its three agents and loses its telephone game.",
    transfer: "Multi-agent handoff engineering is the emerging apps-platform discipline — typed contracts and lineage are where agent orchestration is converging industry-wide.",
  },
  adversarial:
    "The supervisor seduction: it FEELS like defense in depth, and it's the opposite — a reviewer that consumes the same unstructured prose inherits the same blindness, plus its own error rate; when it 'catches' something, you won't know if the catch was right, and you've made the audit question recursive. The monolith retreat: 'collapse it to one agent' — sometimes right (008's falsifier), but here the decomposition earns its keep (different tools, different context needs); the seams were the problem, not the split. The schema-theater miss: defining the types but validating nothing — a schema without a boundary check is documentation, and documentation doesn't fire alerts; the loudness is the feature.",
  recursiveFollowup:
    "Contracts ship; end-to-end hits 84%. The remaining failures cluster in constraint dispositions marked 'relaxed-with-reason' — the resolver relaxes real constraints with plausible-sounding reasons ops disagrees with 40% of the time. The schema made the judgment visible; it didn't make it good. The team asks for 'a rule about when relaxing is allowed.' You're now designing discretion boundaries for a machine (010's autonomy ladder meets 060's red lines, at the seam level). Draw them.",
  altitude: {
    exec:
      "Each agent scores ninety percent; the workflow scores sixty-eight — the failures live in the handoffs, where information survives only if the next agent happens to notice it. We're making the handoffs contracts: structured state, mandatory acknowledgment of every constraint, and emails that can only cite resolutions that exist. No new agents — the fix is plumbing, and the plumbing is checkable.",
    engineer:
      "Handoff schemas per boundary: classifier → {class, constraints[{id, source, severity}], confidence}; resolver must emit disposition per constraint id; communicator template binds to resolution records only. Deterministic validators at each seam with loud-fail routing into the 063 taxonomy. End-to-end trace suite with per-boundary assertions; constraint-survival dashboard.",
    frontier:
      "Multi-agent reliability is seam engineering: component quality compounds only through specified, validated handoffs — typed state, acknowledgment semantics, lineage. The transferable law: probabilistic components, deterministic boundaries. Every orchestration framework converging today is converging on exactly this, and 'add a supervisor agent' is the industry's favorite way to double the problem.",
  },
},

/* ============================================================ 077 */
{
  id: "077",
  title: "The Agent You Can't Debug",
  difficulty: "Medium",
  category: "Agent Architecture",
  primaryLens: "Architecture",
  secondaryLens: "Deployment",
  archetype: "Builder",
  secondaryArchetype: "Maintainer",
  targetRoles: ["CAPE SCPM", "OpenAI Deployment Eng", "MSFT MAI Evals Eng"],
  tags: ["observability", "tracing", "debugging", "operations"],
  prompt:
    "A procurement agent (010's, now at rung two) does something odd: it approves a $4,200 purchase order for a vendor that was suspended last week. The kill switch works, the audit log shows the action — but WHY is unrecoverable: the logs capture the final decision and timestamps, not what the agent retrieved (did it see the suspension notice?), what the model reasoned (did it weigh it?), which tool calls ran in what order, or what the context actually contained at decision time. Three engineers spend two days reconstructing and produce three different theories. Finance asks 'how do we know it won't happen again?' — and the honest answer is you don't know what happened this time. Build the observability.",
  arc: {
    start: "A wrong action with a perfect audit log and zero explanation — three theories, no evidence.",
    mid: "Instrument the decision, not just the action: context, retrievals, tool calls, and reasoning as first-class trace data.",
    end: "Any decision reconstructable in minutes — and the anomaly patterns visible before finance finds them.",
  },
  expected: {
    bottleneck: "The system logs outcomes, not decisions: what the agent DID is auditable (040's identity work paid off), but what it SAW and how it CHOSE is gone — retrieval results, context assembly, tool-call sequences, and model outputs were transient, so every incident becomes archaeology with three competing theories and no strata (the observability designed for deterministic services, applied to a probabilistic one).",
    failureMode: "Patch the visible symptom (add a suspended-vendor check — worth doing, closes one hole) and skip the observability: the next anomaly is equally unexplainable, each incident costs engineer-days of speculation, finance's confidence erodes with every 'we believe it was probably…', and 010's autonomy ladder freezes permanently — nobody advances rungs on a system whose failures can't be explained (the acceptance-rate metric says yes; the unexplainability says never).",
    nextMove: "Build decision-level tracing as the agent's flight recorder: (1) per decision, capture the full causal chain — context assembly (what was retrieved, from which sources, at which versions — 013's provenance meets debugging), the exact model inputs/outputs at each step, tool calls with arguments and results in sequence, and the final action binding (traces linked to 040's identity records); (2) make traces queryable, not just stored — 'show me every decision that touched vendor X' or 'retrievals that missed the suspension list' must be minutes, not archaeology (the 4,200 question becomes a lookup: the trace shows whether the suspension notice was retrieved-and-ignored, not-retrieved, or retrieved-after-decision); (3) retention tiered by stakes — full traces for write-actions and high-value decisions (finance's territory), sampled traces for read-only volume (038's cost discipline applies to observability too); (4) anomaly surfacing on top — decision-pattern monitors (approvals touching recently-changed vendor states, confidence outliers, retrieval misses on known-critical sources) so the next oddity pages you before it pages finance.",
    metric: "Time-to-explanation for any flagged decision (two days → minutes — the number finance actually asked for), and trace completeness on write-actions (every autonomous action must be causally reconstructable, or the rung it required gets re-examined).",
    owner: "Platform engineering owns the trace pipeline; the agent team owns instrumentation points at context/tool boundaries; finance gets the explanation SLA and a per-incident trace summary they can read; you own tying trace completeness to 010's rung advancement — autonomy without explainability stops here.",
    falsifier: "If retro-instrumentation reveals the cause was mundane and structural — the suspension list syncs nightly and the PO ran at 9am against yesterday's data (013's freshness, wearing a debugging costume) — then the incident needed one freshness SLO, not a tracing platform; build the observability anyway but at read-sampled scale, and don't let one stale-data incident gold-plate the flight recorder.",
  },
  modelAnswer:
    "Name what finance actually caught: the system can prove WHAT it did and cannot explain WHY — which for an autonomous actor is the difference between an audit log and accountability. Deterministic services get away with outcome logging because the code IS the explanation: same inputs, same path. An agent's path is context-dependent and probabilistic; the decision's causes live in transient state — what was retrieved, what the context contained, what the model said at each step, which tools ran in what order — and this system threw all of it away. Three engineers, two days, three theories is the natural consequence: they're debating strata that were never deposited.\n\nBuild the flight recorder. Per decision: context assembly with provenance (sources, versions, timestamps — whether the suspension notice was in the retrieved set is THE question, and it should be a field, not a theory), model steps verbatim, tool calls in sequence with arguments and results, and the action binding into 040's identity records. Make it queryable — the debugging primitive is 'show me every decision that touched vendor X,' and if that's not minutes, the recorder exists but the investigation still doesn't. Tier retention by stakes: full traces on write-actions and dollar decisions (the rungs finance signs), sampling on read volume — 038 taught you observability has a token bill too.\n\nThen invert it: the same traces that explain incidents backward predict them forward. Decision-pattern monitors — approvals touching recently-changed vendor state, retrieval misses on critical sources, confidence outliers — turn the flight recorder into an early-warning system; the next $4,200 oddity pages the team before it pages finance.\n\nAnd answer finance's question with the only honest currency: 'we now reconstruct any decision in minutes, and here's this one' — which is also the sentence that un-freezes 010's ladder, because autonomy advances on explained failures and stalls forever on mysterious ones. The acceptance rate said the agent earned rung three; the unexplainability said it hadn't earned rung two. Explainability is the rung under all the rungs.",
  rubric: {
    diagnosis: "Distinguishes outcome auditability from decision explainability and names the transient causal chain as the missing stratum.",
    move: "Decision-level tracing with provenance, queryability as the primitive, stakes-tiered retention, and anomaly monitors on top.",
    measurement: "Time-to-explanation and write-action trace completeness; falsifier right-sizes the build if the cause was one stale sync.",
    synthesis: "Ties explainability to the autonomy ladder — rungs advance on explained failures — and inverts traces into early warning.",
    altitude: "Finance hears the SLA they actually asked for ('minutes, and here's this one') instead of probability language.",
    transfer: "Agent observability is the operational frontier everywhere — decision traces, provenance, and pattern monitors are what 'production-grade agents' means in practice.",
  },
  adversarial:
    "The patch-and-pray failure: adding the suspended-vendor check and closing the incident — one hole closed, the class open; the next anomaly is a different hole with the same archaeology. The log-everything failure: full traces on all decisions forever — the storage and token bill arrives (038), someone cost-cuts observability wholesale, and you're back to zero; tiering by stakes is what makes the recorder survivable. The privacy miss: traces capture full context, and context contains what 057 governs — retention tiers need deletion semantics too, or the flight recorder becomes the compliance finding.",
  recursiveFollowup:
    "The recorder ships. First real use: a trace shows the agent retrieved the suspension notice, the model's intermediate step explicitly noted 'vendor suspended last week,' and the final step approved anyway with reasoning that never mentioned it again. The explanation exists and it's disturbing: attention drift mid-chain, not missing data. Engineering asks 'so what's the fix — better prompts?' You're now debugging cognition, not plumbing (041's judge-validity problem, aimed at your own agent). Design the response.",
  altitude: {
    exec:
      "The audit log proved what happened; nothing could prove why — that's the gap between logging a service and being accountable for a decision-maker. We're adding the flight recorder: everything the agent saw, retrieved, and reasoned, reconstructable in minutes. Your 'how do we know it won't recur' gets a real answer: here's exactly what happened, here's the monitor now watching for the pattern, and autonomy doesn't advance without it.",
    engineer:
      "Trace spans per decision: retrieval sets with source versions, context assembly, model I/O per step, tool calls with args/results, action binding to identity records. Query index on entities (vendor, amount, source). Retention: full on write-actions, sampled on reads, deletion semantics aligned with 057. Monitors: state-change-adjacent approvals, critical-source retrieval misses, confidence outliers.",
    frontier:
      "Agent observability is decision archaeology made unnecessary: capture the causal chain, index it for questions, tier it by stakes, and mine it for warnings. The transferable law — autonomy advances at the speed of explainability — is what separates production agent fleets from demos with kill switches.",
  },
},

/* ============================================================ 078 */
{
  id: "078",
  title: "When the Agent's Brain Is Down",
  difficulty: "Medium",
  category: "Agent Architecture",
  primaryLens: "Architecture",
  secondaryLens: "Deployment",
  archetype: "Maintainer",
  secondaryArchetype: "Builder",
  targetRoles: ["CAPE SCPM", "OpenAI Deployment Eng", "Anthropic TPM Inference Perf"],
  tags: ["degraded-modes", "fallbacks", "resilience", "failure-design"],
  prompt:
    "During 071's regional capacity incident, a customer's agent fleet demonstrated that nobody ever designed for the model being unavailable: the field-service agent showed spinners for four hours (techs went back to PDFs — 013's trust, re-burned), the procurement agent's queue silently swallowed requests (found three days later), and the HR agent — pointed at a hastily-configured fallback model nobody evaluated — gave subtly worse benefits answers all afternoon (015's nightmare, at lower fidelity). The customer's postmortem asks one question: 'What is each agent supposed to DO when its model is down or degraded?' Nobody has an answer. Design the degraded-mode architecture.",
  arc: {
    start: "Three agents, three accidental failure behaviors — spinner, silent swallow, and quiet quality collapse.",
    mid: "Design failure as a state: per-agent degraded modes chosen by stakes, with honest signaling and evaluated fallbacks.",
    end: "A fleet that fails loudly, degrades honestly, and recovers cleanly — with fallback behavior as tested as primary.",
  },
  expected: {
    bottleneck: "Failure behavior was never designed, so each agent improvised its own worst option: the fleet has no per-agent answer to 'model down → do what?', no distinction between fail-closed (stop, say so) and fail-degraded (reduced service, labeled), and the one fallback that existed was an unevaluated model swap — the highest-risk option (unmeasured quality on live users) deployed as if it were the safest.",
    failureMode: "Next incident replays this one: trust burns where agents go silent (users' 013-decay compounds per outage), risk accrues where fallbacks serve unevaluated answers (the HR agent's 'subtly worse' is 015 waiting for a consequential query), and ops discovers each failure mode empirically, during the incident, forever — because 'the model is down' keeps being treated as an exception instead of a state the system was built to inhabit.",
    nextMove: "Make degraded operation a designed state per agent, chosen by stakes: (1) classify each agent's failure posture — fail-closed for high-stakes writers (procurement STOPS, visibly: queue pauses with user notification and backpressure, never silent swallowing), fail-degraded for read-heavy helpers (field-service falls back to deterministic retrieval — search over the same indexed manuals with provenance, 047's boring tier — clearly labeled 'search results, assistant unavailable'), and fallback-model ONLY where a candidate has been evaluated in advance on that agent's golden set (074/075's discipline: an unevaluated model behind a familiar interface is a lie about quality); (2) signal honestly at every layer — users see status, not spinners (071's status-page law, at agent scale); queues surface depth and pause state; downstream automation gets machine-readable degradation signals (076's contracts carry a health field); (3) rehearse the states — degraded modes enter the test suite (chaos drills: kill the model endpoint in staging, verify each agent lands in its designed posture — 045's gate extended to failure behavior); (4) recovery is staged, not assumed — queued work replays with idempotency checks, degraded-period answers get flagged for sampling (did the fallback misbehave?), and the incident review reads per-agent posture compliance.",
    metric: "Per-agent: designed-posture compliance during drills and incidents (did it fail as specified?); fleet-wide: silent-failure count (target zero — every degradation visible to its users) and fallback-quality delta on evaluated sets (known before the incident, verified after).",
    owner: "Each agent's owner declares its failure posture (a required field in 001's gate, retroactively applied); platform engineering owns the health-signal plumbing and drill harness; the eval owner pre-qualifies any fallback model per agent; ops owns the drill calendar — failure modes that aren't rehearsed don't exist.",
    falsifier: "If incident telemetry shows outages this long are once-in-years events and the fleet's queues genuinely tolerate hours of delay (procurement POs aren't time-critical; techs have PDF muscle memory anyway), then full degraded-mode engineering is over-build for the actual risk — fail-closed-with-honest-signaling everywhere is the cheap 80%, and the eval-gated fallback machinery can wait for the agents whose downtime provably costs money per minute.",
  },
  modelAnswer:
    "The postmortem question is the design spec: 'what is each agent SUPPOSED to do?' has no answer because failure was never a state — it was an absence. Three agents improvised three postures, and they happened to demonstrate the full taxonomy of wrong: the spinner (dishonest availability — users discover the outage by wasting time on it), the silent swallow (dishonest completion — the worst posture possible for a write-path: work accepted and lost), and the unevaluated fallback (dishonest quality — a different brain behind the same face, 074's behavioral contract broken by your own ops team under pressure).\n\nDesign the state, per agent, by stakes. Writers fail closed: procurement STOPS — queue visibly paused, submitters notified, backpressure upstream; a paused queue is an inconvenience, a silent one is three days of lost POs and the death of queue trust. Read-heavy helpers fail degraded: the field-service agent drops to deterministic retrieval over the same indexed manuals — 047's boring tier is precisely what you want in a fire — labeled as what it is ('assistant down; here's search with sources'). Honest degradation preserves 013's trust math: techs forgive reduced service and never forgive confident unavailability. And fallback models are a designed option, not an incident improvisation: pre-evaluated per agent on that agent's golden set, with the quality delta known and the label visible. The HR agent's afternoon is the cautionary spec — for benefits answers (015's territory), an unevaluated fallback is worse than honest downtime, because wrong-at-lower-fidelity compounds silently.\n\nThen make it real the only way failure design gets real: rehearse. Kill the model endpoint in staging quarterly; verify each agent lands in its declared posture; treat posture drift as a failing test (045's gate, extended to the failure path). Wire health signals through 076's contracts so downstream automation degrades in sympathy instead of in surprise. Recovery gets the same rigor: idempotent replay for queued work, sampled review of degraded-period outputs. The fleet's maturity metric flips from 'uptime' to 'behavior under downtime' — because the model WILL be down again, and the only question the next postmortem should have is whether each agent did what its spec said.",
  rubric: {
    diagnosis: "Names failure-as-undesigned-state and taxonomizes the three dishonest postures — availability, completion, and quality lies.",
    move: "Stakes-classified postures (fail-closed writers, labeled-degraded readers, pre-evaluated fallbacks only), honest signaling, chaos drills, staged recovery.",
    measurement: "Posture compliance under drill, zero silent failures, and pre-known fallback deltas; falsifier right-sizes to honest-fail-closed where downtime is provably cheap.",
    synthesis: "Connects the postures to their trust economics (013, 015, 074) — degraded honesty beats confident absence — and extends 045's gates to failure paths.",
    altitude: "The customer's postmortem question gets answered as a spec per agent, with a drill calendar as the proof it stays answered.",
    transfer: "Degraded-mode design is serving-adjacent reliability engineering — fallback ladders, health propagation, and rehearsed failure are how inference-dependent systems earn production trust.",
  },
  adversarial:
    "The redundancy reflex: 'multi-region, multi-provider, never down' — availability engineering is real and it doesn't answer the question; some outage always arrives, and infinite nines spent avoiding the design conversation buy an unrehearsed fleet at higher cost. The fallback-everywhere failure: pointing every agent at a cheaper backup model 'for continuity' — you've pre-deployed 074's behavioral ambush fleet-wide; unevaluated fallbacks are quality incidents on a timer. The drill skip: designing postures on paper and never killing the endpoint — failure modes that aren't rehearsed regress silently (the posture spec rots like 017's golden set), and you discover the drift during the real incident, which is the original sin with documentation.",
  recursiveFollowup:
    "Drills pass; the real outage comes. The field-service agent degrades perfectly to labeled search — and usage data shows 30% of techs PREFER degraded mode: faster, predictable, sources visible (048's latency lesson from the other direction). They're asking for a 'search-first' toggle. Your degraded mode out-competed your product for a third of users. Decide what that means — failure mode, feature, or indictment of the primary experience — and what ships.",
  altitude: {
    exec:
      "Last incident, your three agents improvised: one showed spinners for four hours, one silently ate purchase orders, one served unvetted answers behind a familiar face. Now each agent has a designed answer to 'model down': writers stop visibly, helpers degrade to labeled search, and fallback models exist only where we've measured them in advance. We kill the endpoint in staging quarterly to prove it — the next outage runs the spec, not improv.",
    engineer:
      "Posture declaration per agent in the registry (fail-closed / fail-degraded / evaluated-fallback with model + known delta). Health states propagated through handoff contracts; queue pause with notification and backpressure on write paths; degraded-mode UI labeling. Chaos harness: endpoint kill + posture assertion in CI (045). Recovery: idempotent replay, degraded-period output sampling.",
    frontier:
      "Inference-dependent systems need failure as a first-class state: postures by stakes, honesty at every layer (no spinner lies, no silent swallows, no unevaluated brains), and rehearsal as the only proof. The transferable law: design what the system does at its worst moment, or its worst moment designs it for you — in production, with your users watching.",
  },
},

/* ============================================================ 079 */
{
  id: "079",
  title: "Make Them Wait, or Make Them Check Back",
  difficulty: "Easy",
  category: "Agent Architecture",
  primaryLens: "Architecture",
  secondaryLens: "Customer",
  archetype: "Builder",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "OpenAI FDE", "OpenAI DPM (Codex)"],
  tags: ["sync-async", "task-shapes", "ux", "durable-jobs"],
  prompt:
    "A customer's deal-desk agent (048's, now fast) is getting a capability upgrade: full contract-package assembly — pull the CRM history, check pricing against policy, draft five documents, cross-validate terms. It genuinely takes 6–10 minutes of agent work. The team is fighting about architecture: half want to 'optimize until it fits in chat' (they've heard 048's streaming gospel and think latency is always the answer), half want everything async ('kick it off, email when done'). Both sides are solving the wrong layer. Sort the task shapes.",
  arc: {
    start: "A 10-minute task being argued into a 10-second interaction pattern — or out of interactivity entirely.",
    mid: "Sort by task shape: conversation stays sync, work becomes durable jobs with visible progress and interruptibility.",
    end: "Chat for the conversation, a job for the work — and users who start long tasks confidently because the contract is honest.",
  },
  expected: {
    bottleneck: "The team is treating interaction shape as one decision when the workload contains two shapes: conversational exchanges (questions, refinements, quick lookups — belongs in sync chat, 048's territory) and durable work (multi-step assembly measured in minutes — belongs in jobs), and forcing either shape into the other's architecture produces the two classic failures: the 9-minute spinner, or the email-when-done round-trip for what should have been a 4-second answer.",
    failureMode: "Sync-everything ships: users stare at progress theater for 8 minutes, browser tabs close mid-assembly (work lost — no durability), timeouts fire at infrastructure layers nobody configured for 10-minute holds, and the feature gets used once per user (055's abandonment tells); or async-everything ships: every quick question becomes kick-off-and-wait, the conversational value of 048's fast agent dies, and users route around the agent for exactly the interactions it was best at.",
    nextMove: "Split by task shape and build the seam honestly: (1) conversation stays synchronous — questions, refinements, previews, 'what would this cost' — the sub-10-second world 048 built; (2) assembly becomes a durable job — explicitly started ('this takes about 8 minutes — start it?'), running server-side with checkpointed state (tab closes, job survives), visible progress that's real (steps completed, not a spinner — 'pricing validated, drafting document 3 of 5'), and interruptible (user can answer the agent's mid-job questions, or cancel); (3) completion returns to where the user lives — notification in Teams/chat (050's surface law: meet them where they work) with the package attached, not an email to check another system; (4) the agent bridges both shapes conversationally — 'while that assembles, want me to check the renewal dates?' — because the job being async doesn't mean the RELATIONSHIP goes async; (5) set the honest expectation at kickoff — estimated duration and what happens if steps need input — the contract that makes users willing to start 10-minute work.",
    metric: "Job start-to-completion rate (durable jobs that finish vs abandoned/lost — the durability dividend) and repeat usage of the long-running capability (the trust number: users start 10-minute tasks only if the first one honored its contract); plus sync-path latency staying in 048's budget (the split protects it).",
    owner: "The platform team owns the job infrastructure (durable state, checkpoints, notification routing); the agent team owns progress honesty and the conversational bridge; you own killing both purist camps with the task-shape framing before either ships its half-wrong architecture.",
    falsifier: "If workload analysis shows the 6–10 minutes is mostly one parallelizable step (five documents drafted serially that could run concurrently) and the true floor is ~90 seconds, then this IS a latency problem after all — 048's playbook applies, the job machinery waits for genuinely long work, and the team's optimize-first camp was right about this task while wrong about the general rule.",
  },
  modelAnswer:
    "Both camps are arguing about the wrong layer: they're debating an interaction pattern when the decision is a task-shape classification. The workload in front of them contains two different physics. Conversation — asks, refinements, previews — is synchronous by nature: sub-10-second exchanges where 048's streaming work earns its keep. Work — a 6–10 minute multi-step assembly — is a job by nature: it needs durability (survive the closed tab), progress (real steps, not spinner theater), and interruptibility (the agent may need a mid-job answer). Forcing work into chat gets you the 9-minute spinner and lost state; forcing conversation into jobs gets you email-when-done for questions that deserved four seconds. The architecture is: both, seamed well.\n\nThe seam is where the craft lives. Kickoff sets an honest contract: 'about 8 minutes — start it?' (the willingness to start long tasks is entirely a function of the first task's honesty). The job runs server-side, checkpointed, with progress that means something — 'pricing validated, drafting 3 of 5' is information; a spinner is an apology. Completion lands where the user already lives (050: their chat, not another inbox). And the agent keeps the relationship synchronous even while the work isn't: 'while that assembles, want the renewal dates checked?' — the user's mental model should be a colleague who went to do the thing, not a batch system that swallowed a ticket (078's silent-swallow lesson, pre-empted).\n\nRun the falsifier before building the machinery: profile the 6–10 minutes. If it's five documents drafted serially that parallelize to 90 seconds, this was a latency problem wearing a job costume — 048's playbook, again. But when the work is genuinely long (and contract assembly with cross-validation usually is), the job architecture isn't a compromise; it's what lets the agent take on work measured in minutes and hours, which is where agent economics actually get interesting. The team optimizing everything into chat is capping the product at tasks that fit in a sigh.",
  rubric: {
    diagnosis: "Reframes the sync/async fight as task-shape classification — conversation vs durable work — with each camp's failure named.",
    move: "Sync chat preserved, durable checkpointed jobs with honest progress and interrupts, completion routed to the user's surface, conversational bridging.",
    measurement: "Job completion and repeat-usage as the trust dividends, sync latency protected; falsifier profiles the work before building job machinery.",
    synthesis: "Sees that the job being async doesn't make the relationship async — the seam design is the product — and connects durability to agent economics (longer work, bigger value).",
    altitude: "The two camps each keep what they were right about; the user gets a colleague who 'went to do the thing,' not a ticket system.",
    transfer: "Task-shape architecture is the agent-product frontier — durable background work with honest progress is how agents graduate from chat toys to workload owners.",
  },
  adversarial:
    "The purist failures are symmetric and both ship broken halves: sync-everything caps the product at sigh-length tasks and loses work to closed tabs; async-everything kills the conversational value that made the agent trusted enough to hand long work to. The progress-theater miss: shipping the job with a percentage bar that lies (smooth animation over unknown duration) — fake progress burns the exact trust that honest steps build; users detect it by the second job. The notification miss: completion lands in email while the user lives in Teams — the job finishes, nobody notices for hours, and the latency you saved returns as discovery latency (050's lesson, at the finish line).",
  recursiveFollowup:
    "Jobs ship and work. Usage reveals the next shape: sellers start assembly jobs, then message the agent mid-job — 'actually, use the Q3 pricing instead.' The job architecture checkpoints state but wasn't designed for mid-flight amendments: today it's cancel-and-restart (8 minutes lost). Amendment-in-flight is genuinely hard (which checkpoint absorbs the change? does document 2, already drafted, redraft?). Decide: build in-flight amendment, or design the kickoff conversation to front-load the choices — and defend the answer with 009's variance question.",
  altitude: {
    exec:
      "The fight resolves by naming what's what: questions stay instant — that's the fast agent you already have. Real work — the 8-minute contract package — becomes a job: survives closed laptops, shows honest progress, and delivers back into Teams when done. Sellers keep chatting with the agent while it works. One number to watch: whether people start a second long job — that's trust in the contract, and it's the whole game.",
    engineer:
      "Job runner with checkpointed state per step, idempotent restarts, and an interrupt queue for mid-job agent questions. Progress events from real step completions — no synthetic percentages. Completion notification to the user's primary surface with artifact links. Sync path untouched, protected by its own latency SLO. Profile assembly first: parallelize document drafting before assuming the 10-minute floor.",
    frontier:
      "Sync/async is task-shape architecture: conversation and durable work have different physics, and the seam — honest kickoff contracts, real progress, interruptibility, completion-where-they-live — is the product. The transferable arc: agents earn bigger workloads exactly as fast as their long-running contract proves honest, and the first lied-about progress bar caps the fleet at chat.",
  },
},

/* ============================================================ 080 */
{
  id: "080",
  title: "Build the Agent, or Configure It",
  difficulty: "Medium",
  category: "Agent Architecture",
  primaryLens: "Architecture",
  secondaryLens: "Platform",
  archetype: "Sweeper",
  secondaryArchetype: "Builder",
  targetRoles: ["CAPE SCPM", "Anthropic TPM Apps Platform", "MSFT MAI Strategy & Ops"],
  tags: ["build-vs-configure", "platform-tiers", "fleet", "maintenance"],
  prompt:
    "A customer's platform team (001's gate, working) faces a fleet-level pattern: of 30 approved agent requests this quarter, the central engineering group wants to custom-build 22 of them ('the declarative platform is too limiting'), while the business units sponsoring them would take configured agents next week over coded agents next quarter. Spot-checking the 22: a leave-request answerer, a vendor-lookup, three document Q&As — and also a genuinely complex claims-triage agent with custom tool orchestration. Engineering isn't wrong that config has ceilings (022 taught everyone that); they're wrong about where the ceilings are. Draw the line — as fleet policy, not per-agent debate.",
  arc: {
    start: "Twenty-two custom builds queued, most of which are configuration wearing an engineering costume.",
    mid: "Policy by task shape: configure by default, build on demonstrated ceiling, with the burden of proof priced in.",
    end: "A fleet where custom code is spent where it compounds — and 17 agents shipped this quarter instead of 5.",
  },
  expected: {
    bottleneck: "The build-vs-configure decision is being made by builder preference instead of task requirements: custom code's real costs are lifecycle costs (every built agent needs 077's observability, 078's postures, 056's ownership, security review, and a maintainer — forever), and engineering's 'config is limiting' generalizes one true experience (022's cliff) into a fleet-wide default that would convert a configuration backlog into a permanent maintenance estate.",
    failureMode: "The 22 builds proceed: 5 ship this quarter (engineering capacity is what it is), business units wait quarters for leave-request answerers, shadow tools bloom in the gap (014's physics) — and in 18 months the customer owns 22 bespoke codebases whose original builders have rotated (056's orphans, manufactured at scale), each carrying its own auth, logging, and failure-mode implementations that all drift differently.",
    nextMove: "Publish the fleet policy with the burden of proof structured in: (1) configure-first default — every agent request starts on the declarative tier; 'the platform can't do X' must be demonstrated (a failed config attempt or a named platform gap), not asserted (052's per-slice audit logic, applied to capability); (2) build criteria, published — custom code is earned by task shape: custom tool orchestration beyond the platform's primitives, state machines the config tier can't express, latency/cost engineering needs (048/038's territory), or integration surfaces the platform doesn't reach (047's mainframe class); the claims-triage agent passes; the leave-request answerer is config plus a knowledge source, and the burden falls on whoever claims otherwise; (3) price the build honestly at request time — a built agent's quote includes its permanent tax: observability, degraded modes, identity work, security review, and a NAMED maintainer with succession (056's attestation from birth); most 'we'd rather build it' enthusiasm dies at the maintainer line; (4) route the real ceiling cases as platform feedback — if 8 of 30 requests genuinely need the same missing primitive, that's 020's pattern brief to the platform vendor, not 8 custom builds; the gap list is the negotiating asset; (5) re-review the line quarterly — config tiers are gaining capability fast (066's autopilot direction), and a build justified last year may be a migration candidate now.",
    metric: "Fleet mix and time-to-ship: configured agents shipping in days/weeks vs built agents in months (the business units' actual complaint, quantified), and the maintenance ratio — engineering hours on existing built agents vs new capability (the number that grows silently until it eats the roadmap).",
    owner: "The platform team owns the policy and the demonstrated-ceiling test; engineering owns build-tier work worthy of it (framed as promotion: their scarce skill goes to the claims-triage class, not leave-request plumbing); business units get the fast tier by default; the platform-gap brief goes to the vendor with 020's arithmetic.",
    falsifier: "If the demonstrated-ceiling tests keep failing in config's favor — teams genuinely hit the declarative tier's walls on a majority of the 22 (auth patterns, data access, workflow shapes the platform can't express) — then the config tier is weaker than the policy assumed, the default flips for this platform generation, and the honest output is 022's coverage map plus a much sharper vendor conversation, not a policy that keeps sending teams up a road that's actually closed.",
  },
  modelAnswer:
    "Name the economics first, because the debate is being had in the wrong currency: engineering is pricing builds in construction time; the real price is lifecycle. Every custom agent is a permanent estate — it needs 077's traces, 078's failure postures, 040's identity work, security review, and a named maintainer through every reorg (056 taught this customer what orphaned code with permissions does). Twenty-two builds isn't twenty-two projects; it's twenty-two forever-obligations, staffed by a team that ships five things a quarter. Meanwhile the configured tier ships in days, inherits the platform's observability, failure handling, and identity for free, and gets better every platform release without anyone's maintenance calendar.\n\nSo the policy: configure-first, build-on-demonstrated-ceiling. 'The platform can't do X' is a test result, not an opinion — show the failed config or the named gap (052's audit discipline, aimed at capability claims). The published build criteria are task shapes, and 011's rule scales fleet-wide — complexity must be earned by requirements: custom orchestration beyond platform primitives, inexpressible state machines, hard latency/cost engineering, unreached integration surfaces. Spot-check honestly: claims-triage passes on orchestration; the leave-request answerer is a knowledge source and a config file, and building it is engineering entertainment billed as necessity.\n\nTwo moves make the policy adoptable instead of resented. Price builds truthfully at request time — the quote includes the observability, the postures, the security review, and the named maintainer with succession; watch enthusiasm meet the maintainer line. And promote, don't demote, engineering: their scarce capability is being spent on plumbing that config does free — the policy redirects it to the claims-triage class, where custom work compounds. Then harvest the real signal: if multiple requests hit the same platform ceiling, that's not N builds, it's one pattern brief (020) to the vendor — the gap list is leverage. Re-run the line quarterly; config tiers are climbing (066's autopilot is coming for more of the stack), and yesterday's justified build is tomorrow's migration candidate (064 waiting to happen). The fleet you want: seventeen configured agents shipped this quarter, five builds that deserve the name, and zero orphans-in-training.",
  rubric: {
    diagnosis: "Re-prices the decision in lifecycle currency — built agents as permanent estates — and names builder preference as the current allocator.",
    move: "Configure-first policy with demonstrated-ceiling tests, published build criteria by task shape, honest build quotes including the maintainer, gaps harvested as vendor leverage.",
    measurement: "Fleet mix, time-to-ship by tier, and the maintenance ratio; falsifier flips the default if ceiling tests keep failing config's way.",
    synthesis: "Frames the policy as promoting engineering to work that deserves it, and converts repeated ceilings into 020's pattern brief — fleet decisions feeding platform strategy.",
    altitude: "Business units hear days-not-quarters; engineering hears their skill aimed at the hard five; the vendor hears a gap list with arithmetic.",
    transfer: "Build-vs-configure at fleet scale is the apps-platform governance question — tier policies, demonstrated ceilings, and lifecycle pricing are how mature platforms allocate their scarcest resource.",
  },
  adversarial:
    "The capability-worship failure: letting 'config is limiting' win because it's sometimes true — 022's cliff was real AND it was one agent in thirty; generalizing the exception is how a quarter's backlog becomes a decade's estate. The config-fundamentalist failure: refusing the claims-triage build to keep the policy pure — the demonstrated-ceiling test exists precisely so real complexity gets real engineering; a policy that can't say 'build' loses engineering's consent and then its compliance. The quote-dodge miss: publishing criteria without the lifecycle price tag — builds keep winning arguments on construction estimates, and the maintenance ratio eats the roadmap on schedule, invisibly (038's undifferentiated bill, in engineering hours).",
  recursiveFollowup:
    "The policy works for a year — then the platform vendor ships an 'advanced orchestration' config tier that can express most of what justified your five builds, including claims-triage's workflow. Engineering's maintainers, now attached to their systems, argue the builds are 'proven and not worth migration risk.' You wrote 064's playbook for customers; now it's aimed at your own team's beloved code. Decide which builds migrate, and what the demonstrated-ceiling test says when the ceiling moves.",
  altitude: {
    exec:
      "Twenty-two custom builds means five ship this quarter and seventeen business units wait — while most of those agents are configuration wearing an engineering estimate. New policy: configure by default, build when a test proves the platform can't do it, and every build's quote includes its forever-cost — monitoring, failure design, security, and a named owner. Your engineers go where they're irreplaceable; your leave-request bot ships Tuesday.",
    engineer:
      "Ceiling test protocol: attempted config with documented failure, or named platform gap. Build criteria: custom orchestration, inexpressible state, latency/cost engineering, unreachable integrations. Build quote template includes trace instrumentation, degraded postures, identity scoping, security review, and maintainer-with-succession. Gap register feeds the vendor brief; quarterly re-review as config tiers climb.",
    frontier:
      "Fleet-scale build-vs-configure is lifecycle allocation: custom code is a permanent estate, config inherits the platform's improvements free, and the line between them is a demonstrated test that moves every release. The transferable discipline — default to the rising tier, spend engineering where requirements earn it, convert repeated ceilings into platform leverage — is how agent fleets scale without becoming museums of orphaned code.",
  },
},

);
