/* Parabolic 100 — problem bank, part 18 (096–100: the canon completes) */

P100.PROBLEMS.push(

/* ============================================================ 096 */
{
  id: "096",
  title: "The Platform Tax Debate",
  difficulty: "Medium",
  category: "Platform Feedback & Product Strategy",
  primaryLens: "Platform",
  secondaryLens: "Altitude",
  archetype: "Grower",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "MSFT MAI Strategy & Ops", "Anthropic TPM Apps Platform"],
  tags: ["internal-platform", "value-proof", "chargeback", "politics"],
  prompt:
    "Annual planning at the customer: the central AI platform team (the gate from 001, the gateway from 039/049, the eval program from 016–089, the lifecycle governance from 056) is up for budget renewal — and the business units are in revolt. The loudest BU president: 'We pay a platform tax of $6M a year and a two-week gate delay on everything, while my team could just call the APIs directly. Show me what the platform is FOR, or give me my money back.' He's not entirely wrong — the gate HAS slowed him, and his best engineers COULD wire APIs. The platform lead's defense deck is 40 slides of architecture diagrams. It's going to lose. Write the case that wins — or concede what should be conceded.",
  arc: {
    start: "A platform defending itself with architecture slides against a P&L argument it keeps losing.",
    mid: "Re-price the platform in avoided-incident and per-agent-cost terms; concede the real friction; convert the critic.",
    end: "The platform re-funded on evidence, its tax restructured to follow value — and the loudest critic running its fastest lane.",
  },
  expected: {
    bottleneck: "The platform's value is real but denominated in the wrong currency: it charges visible costs (the $6M, the two-week gate) and delivers invisible returns (incidents that didn't happen, orphans that didn't accumulate, the 40% cost reduction from 038 that BUs banked without attribution, per-agent marginal costs a direct-API team can't touch) — and 40 slides of architecture is the platform lead pricing it in a currency BU presidents don't spend (028's unfalsifiable-metric failure, as an org chart).",
    failureMode: "The revolt wins: chargeback dissolves, three BUs wire direct API integrations within a quarter — each rebuilding auth, logging, eval, and failure handling badly (080's estate, distributed), the 059/084-class incidents return (unvetted agents, stampeded systems), costs balloon invisibly across BU budgets where no one sums them — and eighteen months later the org re-founds a platform team at 2x the cost under incident pressure (014's physics: the paved road, demolished, gets rebuilt as an emergency toll road).",
    nextMove: "Rebuild the case in P&L currency, concede the true friction, and restructure the tax: (1) price the counterfactual, honestly — per-agent all-in cost on-platform vs the direct-API estate (080's lifecycle math: auth, observability, failure postures, security review × 40 agents), the avoided-incident ledger (the 059 vendor-agent catch, the 084 stampede that got contained, the 015-class incident their gate caught — with 043's attribution honesty about which saves were real), and the banked wins BUs absorbed without credit (038's 40%, delivered by platform caching and routing); (2) concede the gate's cost as real — two weeks IS too slow for low-risk agents, and the fix is 058/080's own logic pointed inward: risk-tiered lanes (config-tier agents clear in 48 hours, only 060-class risk gets the full gate), which converts the loudest complaint into the platform's next feature; (3) restructure the tax to follow value — flat allocation breeds resentment; usage-plus-tier pricing (BUs pay for what they consume, premium for gate-heavy services) makes the bill legible and the platform accountable to it (067's pricing-model lesson, internal edition); (4) convert the critic — the BU president's team becomes the design partner for the fast lane (054's authorship at budget-politics altitude): his next agent ships in 48 hours through the process he helped design, and he defends the platform at the table where he was leading the revolt; (5) put the platform on the hook going forward — published SLAs (gate latency by tier, uptime, cost-per-agent trend) so next year's renewal is a metrics review, not a faith debate.",
    metric: "Cost-per-agent (platform vs direct-API counterfactual, honestly computed) and the avoided-incident ledger as the renewal case; going forward: gate latency by risk tier and platform cost-per-agent trend — the SLAs that make next year's debate empirical.",
    owner: "The platform lead owns the re-priced case (coached off the architecture slides); the BU president gets the fast-lane design partnership (his revolt becomes his feature); finance blesses the counterfactual math (their imprimatur is what makes the avoided-cost ledger credible); you own the concession's sincerity — the tiered gate must actually ship.",
    falsifier: "If the honest counterfactual math comes back thin — the BUs' direct-API estimates are competent, the avoided incidents are mostly attributable to other controls, and the platform's real value concentrates in 20% of its services — then the revolt has a point: the platform should shrink to its load-bearing core (the gateway, the eval program, lifecycle governance) and shed the rest (the 087 portfolio review, applied to the platform itself), because defending every service equally is how the whole thing loses.",
  },
  modelAnswer:
    "The platform is about to lose a fight it should win, for the same reason 087's eval program almost did: it prices its costs in dollars and its value in architecture. A BU president doesn't spend architecture. Rebuild the case in his currency — and start by conceding what's true, because the concession is what buys the hearing: the two-week gate IS too slow for a config-tier FAQ agent, and defending it uniformly is 058's blanket-freeze error committed by the defenders.\n\nThe case has three exhibits. Cost-per-agent, counterfactual-honest: what his direct-API plan actually costs at estate scale — 080's lifecycle math (auth, observability, failure postures, security, a named maintainer, forever) times every agent, versus the platform's marginal cost where all of that is inherited. The number is lopsided and nobody has ever shown him. The avoided-incident ledger, with 043's attribution discipline: the vendor agent 059 caught before it OAuth'd into the document graph, the 084 stampede contained to one Monday, the eval gate's catches — priced at incident cost, honestly hedged for what other controls might have caught. And the banked wins: 038's 40% cost reduction landed in BU budgets with no platform attribution; claim it, with receipts. Then the restructure that makes it durable: usage-plus-tier chargeback (the $6M flat tax breeds exactly this revolt; 067's lesson runs inside companies too) and risk-tiered gate lanes — 48 hours for config-tier agents, the full gate reserved for 060-class risk. The loudest complaint becomes the roadmap.\n\nThe political move is the conversion: make the BU president's team the fast lane's design partner. His next agent ships in two days through a process with his fingerprints on it, and at the budget table he's now defending the thing he was leading the revolt against — 054's mechanism, executed at planning season. And hold the falsifier honestly: run 087's portfolio review on the platform itself first. If the value concentrates in the gateway, the evals, and lifecycle governance while the long tail is empire — shrink to the core and say so. A platform that concedes its bloat buys the credibility to defend its spine; one that defends everything equally loses everything together.",
  rubric: {
    diagnosis: "Names the currency mismatch — visible costs, invisible returns — and the uniform gate as the platform's own 058-class error.",
    move: "P&L-denominated case (counterfactual cost, attributed avoided incidents, banked wins), tiered fast lanes as the concession, usage-based chargeback, critic converted to design partner.",
    measurement: "Cost-per-agent vs counterfactual and the incident ledger now; tiered SLAs so next renewal is empirical; falsifier shrinks the platform to its load-bearing core.",
    synthesis: "Turns the bank's own machinery inward — 080's math, 043's attribution, 067's pricing, 054's authorship, 087's portfolio review — the platform governed by its own doctrine.",
    altitude: "The BU president hears his own currency and his own fingerprints; finance hears a ledger it blessed; the platform lead loses the slide deck and keeps the budget.",
    transfer: "Internal-platform value defense is a universal seat — the paved road must periodically re-prove it beats the desire paths, in the deciders' currency, with its critics co-authoring the fixes.",
  },
  adversarial:
    "The architecture-deck failure: 40 slides of gateways and gates — true, beautiful, and denominated in a currency the room doesn't spend; the revolt votes with a spreadsheet. The martyrdom failure: defending the two-week gate as non-negotiable rigor — uniform friction IS the tax's worst component, and 024's law applies inward: gates that ignore proportionality get routed around, then defunded. The conversion-skip: winning the budget vote on math but leaving the BU president unconverted — he lost a vote, not a conviction; next year's revolt starts from resentment plus preparation, and the fast lane you didn't build becomes the direct-API pilot he runs 'as an experiment' (014, at P&L scale).",
  recursiveFollowup:
    "The case wins; the fast lane ships; the president converts. Two quarters later the tiered gate produces its predictable edge: a BU self-classifies a customer-data agent as config-tier to catch the 48-hour lane, it clears without the full review, and 089's sampled oversight catches the misclassification only after deployment. The fast lane's speed is now the attack surface (058's usage-drift problem, self-inflicted). Fix the classification integrity without killing the lane the platform's renewal was won on.",
  altitude: {
    exec:
      "You're right about the two weeks — that's our failure, and the fix ships this quarter: forty-eight hours for low-risk agents, the full gate only where risk earns it. But before you take the API-direct path, see the math nobody showed you: what forty agents cost with every team rebuilding auth, monitoring, and security alone — versus inheriting it. Plus the incidents that didn't happen, priced honestly. And from now on you pay for what you use, not a flat tax — with published SLAs, so next year this is a metrics review, not a faith debate.",
    engineer:
      "Counterfactual model: per-agent lifecycle cost direct-API (080's checklist priced) vs platform-marginal. Incident ledger with attribution confidence per save. Chargeback: usage metering by BU from the gateway (039/049 already meter it), tier premiums for gate services. Fast lane: risk-tier classifier with 089-style sampled audit on self-classification. Platform SLAs published: gate latency by tier, cost-per-agent trend.",
    frontier:
      "Platform value is invisible by design — its product is incidents that don't happen and marginal costs that don't compound — so it must be re-priced periodically in the deciders' currency: counterfactual estates, attributed saves, banked wins. The transferable laws: concede the true friction before defending the spine, tier what uniformity made resented, convert the loudest critic through authorship, and run your own portfolio review before the budget committee does it for you.",
  },
},

/* ============================================================ 097 */
{
  id: "097",
  title: "Reading the Talent Tape",
  difficulty: "Medium",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Altitude",
  archetype: "Grower",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "MSFT MAI Strategy & Ops", "OpenAI DPM (Codex)"],
  tags: ["talent-signals", "jd-drift", "org-reads", "hiring-markets"],
  prompt:
    "The customer's CHRO joins the QBR with an unusual request: 'We're planning our AI org for the next two years — 40 requisitions. I've been reading the frontier labs' job boards to figure out what roles will matter, and the postings confuse me: six months ago everyone wanted prompt engineers; now those are gone and I see forward-deployed engineers, evals leads, and something called agent operations. If I staff to today's postings, am I hiring for roles that evaporate next? What does the hiring tape actually tell us — and what should MY 40 reqs be?' Read the tape for her — including its distortions.",
  arc: {
    start: "A CHRO staffing two years out from a job-board signal she suspects is noisy — correctly.",
    mid: "Read JD drift as bottleneck migration with a lag; separate durable functions from title fashions; map lab roles to enterprise needs.",
    end: "Forty reqs staffed to functions that survive title churn — with a twice-yearly tape review instead of a one-time copy.",
  },
  expected: {
    bottleneck: "The tape is a real signal wearing two distortions: job postings ARE where the industry's bottleneck migration becomes legible (roles appear where organizations hurt — the shift from prompt-engineer to evals/FDE/agent-ops postings tracks the industry moving from 'making models respond' to 'making deployments work'), but titles churn faster than functions (prompt engineering didn't die; it dissolved into every role — 037/081's context craft), and lab postings reflect LAB bottlenecks, which reach enterprises on a lag and in translated form — copying them verbatim staffs her for someone else's org chart.",
    failureMode: "Either error wastes the reqs: copy the tape literally and she hires 'agent operations engineers' into an org that hasn't deployed agents yet (roles ahead of their bottleneck idle and leave — the talent version of buying capacity before demand, 091's utilization trap in headcount); or dismiss the tape as fashion and staff to last year's org — 40 reqs of prompt engineers and chatbot PMs hired precisely as the industry's centre of gravity leaves those titles, a two-year staffing plan for a market that's already moved (017's stale golden set, as an org design).",
    nextMove: "Read the tape in three layers, then translate: (1) extract functions from titles — the durable read beneath the churn: measurement (evals leads appearing everywhere = the industry learning 016–089's lessons), deployment (FDE growth = models work, deployments don't — the field's whole thesis), operations (agent-ops = fleets now need 056/077/078's disciplines), and integration judgment (the roles this bank trains); titles will keep churning — functions compound; (2) lag-adjust for her org — lab bottlenecks arrive at enterprises 12–24 months later in translated form: labs' FDE becomes her 'AI deployment lead,' labs' evals lead becomes her measurement owner (017's named role, finally a req), labs' agent-ops becomes her fleet operations function once 080's estate exists — sequence the 40 reqs against HER deployment maturity, not the labs' (the 054 exposure-ladder logic, applied to hiring); (3) name the distortions honestly — postings over-represent bottlenecks organizations FAILED to solve internally (they post what they can't grow), under-represent what's quietly absorbed into existing roles, and fashion-cycle hard at the title layer; (4) staff the spine, rent the froth — permanent reqs for the durable functions (measurement, deployment judgment, data/platform engineering), contractors and vendors for the title-of-the-quarter needs until they prove durable (092's short-lock logic, in headcount); (5) install the cadence — a twice-yearly tape review (JD drift as a standing market indicator with the 095 watch-sheet treatment) so the org tracks the migration instead of copying one frame of it.",
    metric: "Req-to-function mapping (every posting justified by a durable function, not a title sighting) and time-to-productivity per role class (roles hired ahead of their bottleneck idle — measurable); the standing metric: her org's function coverage vs the tape's drift at each semi-annual review.",
    owner: "The CHRO owns the staffing sequence with the maturity-lag map; her talent team owns the semi-annual tape review (trained to read functions under titles); you own the translation layer — lab-role-to-enterprise-function — and the honesty about which fashionable titles to rent rather than own.",
    falsifier: "If her org's deployment maturity is genuinely ahead of the lag model — agents already at 080's fleet scale, incidents already demanding 077/089's machinery — then the tape applies nearly verbatim and the sequencing caution is the error: staff agent-ops and evals NOW, because for once the enterprise's bottleneck coincides with the labs', and waiting for the lag that already elapsed hands the talent market to competitors reading the same tape.",
  },
  modelAnswer:
    "Validate her suspicion first: the tape is real signal AND it's distorted, and reading it well means holding both. The signal: job postings are where bottleneck migration becomes visible — organizations post for what hurts. The drift she spotted is the industry's whole arc in miniature: prompt engineers appearing when the bottleneck was 'making models respond well,' dissolving when that skill became ambient (it didn't die — it moved into every role, the way 'internet skills' did), and the new cluster — evals leads, forward-deployed engineers, agent operations — announcing that the bottleneck moved to making deployments measurable, landed, and operable. That's 016 through 089 of this bank, appearing as an org chart. The distortions: titles churn faster than functions; postings over-represent what companies failed to grow internally; and lab postings describe LAB bottlenecks, which reach her on a 12–24 month lag, translated.\n\nSo read functions, not titles, and there are four durable ones under the churn: measurement (someone must own 017's golden sets and 041's judges — the evals-lead postings are the industry conceding this is a permanent role), deployment judgment (the FDE wave = models work, deployments don't; her version is deployment leads who own 018–065's motions), fleet operations (agent-ops postings = fleets now need 056's lifecycle, 077's observability, 078's postures — a function her org needs the quarter its 080 estate exists, not before), and platform/data engineering (unglamorous, never stopped being the spine). Sequence the 40 reqs against HER maturity, not the labs': measurement and deployment leads now (her bottleneck already), fleet ops as the estate scales, and the title-of-the-quarter roles rented — contractors and vendors — until a fashion proves it's a function (092's short-lock discipline, applied to people).\n\nThen make it a standing instrument instead of a one-time copy: a semi-annual tape review — JD drift tracked like 095's indicators, functions-under-titles extracted, her org's coverage mapped against the migration. The closing frame for her: the tape doesn't tell you what to hire; it tells you where the industry's pain is moving. Staff the functions that absorb pain durably, rent the titles that name it fashionably — and read the tape twice a year, because the one thing it reliably says is that it won't say the same thing next year.",
  rubric: {
    diagnosis: "Reads JD drift as bottleneck migration while naming all three distortions — title churn, failed-to-grow bias, and the lab-to-enterprise lag.",
    move: "Functions extracted from titles, reqs sequenced to her maturity, spine staffed and froth rented, semi-annual tape review installed.",
    measurement: "Req-to-function justification and time-to-productivity as the idle-hire detector; falsifier lets a mature org skip the lag and staff the tape verbatim.",
    synthesis: "Recognizes the posting drift as this bank's own curriculum appearing in the labor market — deployment judgment becoming the economy's posted bottleneck.",
    altitude: "The CHRO gets a staffing sequence and a standing instrument instead of a fashion forecast; her talent team inherits a readable method.",
    transfer: "Talent-tape reading is market calibration through the labor channel — bottleneck migration legible in hiring pages is a standing indicator for every strategy seat, lab and enterprise alike.",
  },
  adversarial:
    "The copy-paste failure: staffing her org to the labs' postings verbatim — she inherits roles ahead of their bottleneck (agent-ops with no fleet), which idle, sour, and leave; postings are someone else's pain, lag-adjusted for nobody. The fashion-dismissal failure: 'titles are noise, hire generalists' — the drift IS signal about where pain migrates, and generalist-only staffing rediscovers the bottlenecks one incident at a time (the org learns 016–089 by living it instead of hiring it). The one-frame miss: doing this analysis once for the 40 reqs and never installing the review — the tape's only reliable message is its own churn, and a two-year plan staffed to one frame of a moving picture is 017's rot with salaries attached.",
  recursiveFollowup:
    "She staffs the sequence; it works. At the next semi-annual review, the tape shows something new: the labs' postings for evals and agent-ops roles are DECLINING — replaced by postings describing those functions folded into engineering generalists 'with agent experience,' plus a new cluster around agent-fleet economics. Two readings compete: the functions matured into ambient skills (prompt engineering's arc, repeating — absorb them), or the labs automated the functions (their own 066-style autopilot, eating the roles). Her evals lead — hired on your advice — asks which one means her role is next. Read the new tape honestly, in front of her.",
  altitude: {
    exec:
      "The postings are telling you where the industry's pain moved: from making models answer well to making deployments measurable, landed, and operable. But titles churn faster than functions, and lab bottlenecks reach you a year or two later, translated. So: staff the four durable functions — measurement, deployment leadership, platform engineering now, fleet operations as your agent estate grows — rent the fashionable titles until they prove permanent, and we'll re-read the tape together every six months. It's a weather report, not a blueprint.",
    engineer:
      "Tape instrumentation for the talent team: posting-cluster tracking across the target orgs' careers pages, function-extraction rubric (what does this role own, strip the title), drift log semi-annually. Internal mapping: her deployment-maturity milestones (fleet size, incident classes seen, eval program stage) as the trigger conditions for each req wave.",
    frontier:
      "Hiring pages are the supercycle's labor-market ticker: roles appear where organizations hurt, dissolve where skills become ambient, and lag between labs and enterprises by a translatable interval. The transferable craft — extract functions from title churn, sequence against your own bottleneck maturity, rent fashion and own function, re-read on a cadence — turns the tape from anxiety into an indicator.",
  },
},

/* ============================================================ 098 */
{
  id: "098",
  title: "The Launch-Day Read",
  difficulty: "Medium",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Eval",
  archetype: "Sweeper",
  secondaryArchetype: "Grower",
  targetRoles: ["CAPE SCPM", "MSFT MAI Evals Eng", "OpenAI DPM (Codex)"],
  tags: ["model-launches", "capability-reads", "hype-discipline", "dated-claims"],
  prompt:
    "A frontier lab ships a major release at 10am: a livestream, spectacular demos (an agent completing a 40-minute multi-app workflow autonomously), benchmark charts with vertical-looking deltas, and a blog post announcing 'a new era of agentic AI.' By 2pm your phone is a queue: the customer's CEO ('do we need to change strategy?'), your own leadership ('what does this mean for our roadmap?'), a champion CTO ('my board asks if our current stack is obsolete'), and your team ('should we pause the 039 routing work?'). You have watched one livestream and read one blog post. Everyone wants the read NOW. Produce the read that's still right in 90 days.",
  arc: {
    start: "Four altitudes demanding instant certainty off a livestream and a benchmark chart.",
    mid: "Decompose the launch — capability, product, narrative — and issue a dated read with markers instead of a verdict.",
    end: "A same-day answer that commits to evidence on a schedule — and is still quotable when the dust settles.",
  },
  expected: {
    bottleneck: "The launch bundles three different things moving at different speeds — capability (what the model actually does better, knowable only through hands-on evals), product (what ships, at what price, latency, and reliability — often trailing the demo by quarters), and narrative (the 'new era' framing, designed for exactly the phone calls you're receiving) — and every caller wants a verdict before the only honest inputs (your own evals on your own workloads) can exist; the skill is issuing a read that's useful TODAY without pretending to knowledge that arrives in weeks.",
    failureMode: "Either instant verdict fails on schedule: 'this changes everything' triggers strategy churn, paused roadmaps (the 039 work stops — exactly wrong, since routing is what ABSORBS new models), and panic procurement — then the demo-to-product gap surfaces (the 40-minute workflow was heavily scaffolded, the API ships in 'coming months,' 053's produced-demo lesson at lab scale) and your credibility ate the difference; or 'it's mostly hype' — and 90 days later the capability is real on your own evals, competitors who moved absorbed it first, and the dismissal reads as the vendor-defensiveness it half was (075's reflexive gate-defense, at market altitude).",
    nextMove: "Issue the structured read, same day, four altitudes: (1) decompose out loud — 'three things launched: a capability claim (verifiable in our evals within two weeks), a product (shipping date, price, and reliability still unannounced — the demo-to-API gap is where launches routinely deflate), and a narrative (already working, as this phone queue proves)'; (2) commit to the evidence schedule — the launch enters YOUR harness the day access lands: 016's golden sets, 041's judges, the 075-style customer-workload samples, and 038's cost-per-task math at the announced pricing (a capability that costs 5x per task is a different strategic object than the keynote implies); publish the read-update date in the same breath as the read; (3) give each altitude its calibrated slice — CEO: 'strategy holds; strategies that require re-writing on every launch weren't strategies (069's invariants logic) — our architecture is built to absorb better models, which is what 039's routing IS'; champion CTO: board language distinguishing demo from deployable, plus the dated re-read; leadership: the two-week eval sprint's scope; team: the routing work SPEEDS UP — it's the absorption mechanism; (4) log the Gnomon claims — 'the demoed autonomy will reach API parity within N months: confidence X%,' 'our eval bar on workload classes A/B: beaten or not by date Y' — resolvable, on the record; (5) watch the trailing indicators that outlast keynotes — API pricing when announced, rate limits at GA (023's tell: constrained capacity means the capability is expensive to serve), independent eval replications, and the quiet revisions to the demo's fine print.",
    metric: "The two-week eval verdict on YOUR workloads (the only capability truth that matters locally) and the demo-to-product gap tracked at 30/60/90 days (announced vs shipped vs priced); the standing metric: your launch-read hit rate across releases — the Gnomon ledger makes you the person whose 2pm read is trusted BECAUSE it's graded.",
    owner: "You own the same-day structured read and its dated updates; the eval program owns the two-week sprint (access day one, verdict day fourteen); the 039 routing work owns absorption (its pause would be the panic's first casualty and the strategy's worst one); leadership gets the claims register — your reads, resolvable, on the record.",
    falsifier: "If the two-week evals shock you — the capability clears your hardest workload bars at announced pricing, the demo-to-API gap is unusually small, and 038's math holds — then this launch IS the discontinuity the narrative claimed, the read updates loudly and early ('I was calibrated-skeptical; the evidence says more'), and the routing layer's job becomes routing TO it fast — being visibly wrong-then-corrected on schedule is the credibility system working, not failing.",
  },
  modelAnswer:
    "The 2pm skill is refusing the verdict while still giving an answer. Decompose the launch into its three components, out loud, because the callers are conflating them: a capability claim — real, possibly large, verifiable only through your own evals, which start the day access lands and report in two weeks. A product — unannounced price, unannounced latency, 'coming months' availability, and a demo whose 40-minute autonomy ran on scaffolding you can't see (053's produced-demo discipline applies to labs too; the demo-to-API gap is where launches routinely deflate, and its size is unknowable today). And a narrative — 'new era' — which is already succeeding, as this phone queue demonstrates, and which is information about marketing, not capability.\n\nThen give each altitude its slice, same day. The CEO: 'Strategy holds — a strategy that needs rewriting every keynote wasn't one (069's invariants, applied to ourselves). Our architecture is built to absorb better models; if this one is real, it slots in. Eval verdict in two weeks, on our workloads, with our numbers.' The champion CTO gets board language: demo versus deployable, the dated re-read, and 'obsolete' reframed — stacks built on routing (039) don't obsolete, they upgrade. The team: the routing work accelerates, because it's the absorption mechanism — pausing it to wait for a new model is stopping construction of the port because a bigger ship was announced. And leadership gets the register: dated, resolvable claims — 'demoed autonomy reaches API parity within N months, confidence X'; 'clears our workload-A eval bar by date Y or doesn't' — logged where they'll be graded (the Gnomon ledger is what makes your NEXT 2pm read worth taking).\n\nThen watch what outlasts the keynote: pricing at announcement (038's cost-per-task math converts 'amazing' into 'amazing at what unit cost'), rate limits at GA (023's tell — throttled capacity means expensive serving), independent replications, fine-print revisions. And hold the falsifier with genuine openness: if the two-week evals shock you — bars cleared, gap small, pricing sane — say so loudly and early. The read that upgrades itself on evidence, on schedule, is the only kind worth being known for; 'calibrated' never meant 'skeptical' — it means the confidence moves when the evidence does, in both directions, on dates you named in advance.",
  rubric: {
    diagnosis: "Decomposes capability/product/narrative moving at different speeds, and names the demo-to-API gap as the launch's standing unknown.",
    move: "Same-day structured read per altitude, two-week eval sprint committed with dates, routing work accelerated as the absorption mechanism, claims logged resolvably.",
    measurement: "Own-workload eval verdict and the 30/60/90 demo-to-product gap; the meta-metric is the graded hit rate that makes future reads trusted.",
    synthesis: "Sees the routing layer as what makes launches non-events strategically — and being wrong-then-corrected on schedule as the credibility system working.",
    altitude: "Four callers, four calibrated slices, one evidence schedule — nobody gets a verdict, everybody gets an answer.",
    transfer: "Launch-day reads are the recurring calibration exam of the supercycle — decomposition, dated claims, and own-eval verdicts are the discipline labs and enterprises both need at every release.",
  },
  adversarial:
    "The panic-verdict failure: 'this changes everything' at 2pm — strategy churn, paused absorption work, and a credibility bill when the API ships trailing the demo; you've traded ninety days of standing for four hours of seeming decisive. The dismissal failure: 'mostly hype' — half vendor-defensiveness, and if the capability lands on your evals you're the person who called the discontinuity noise; both instant verdicts are the same error with different flavors: certainty purchased before evidence exists. The private-hedge miss: making the calibrated read but not LOGGING the dated claims — unrecorded predictions get remembered as whatever's convenient (099's incoming lesson), and the ledger is the difference between being calibrated and being agreeable.",
  recursiveFollowup:
    "Day 14: your evals return a split verdict — the new model crushes your document-workflow bar (migrate-worthy) but the demoed agentic autonomy fails your 088-style process evals badly (unreliable tool sequencing, exactly what the scaffolded demo hid). Same day, the customer's CEO forwards a competitor's press release: they've announced a full migration to the new model, 'first in our industry.' He asks: 'They moved in two weeks. Why are we slower?' Defend the split verdict against the speed narrative — with 043's attribution discipline ready for what the competitor's 'migration' probably is.",
  altitude: {
    exec:
      "Three things launched today: a capability claim we'll verify on our own workloads within two weeks, a product with no price or ship date yet — demos and APIs routinely differ by quarters — and a narrative, which is why your phone rang. Strategy holds: we built the routing layer precisely so better models slot in when they prove out. You'll have my updated read with our own numbers on the fourteenth — and my claims are logged and dated, so you can grade me.",
    engineer:
      "Eval sprint on access: golden sets and judges (016/041), customer-workload samples (075's protocol), process evals on the agentic claims (088 — demos hide scaffolding), cost-per-task at announced pricing (038). Track: API rate limits at GA, pricing revisions, independent replications. Routing work continues — new model enters as a candidate tier behind the eval gate (039), same as every model.",
    frontier:
      "Launch reads are calibration under adrenaline: decompose capability from product from narrative, commit to own-eval verdicts on named dates, log claims where they'll be graded, and let the routing architecture make every launch an absorption event instead of a strategy crisis. The transferable law: the read that updates itself on schedule beats the verdict that was fast — every ninety days, forever.",
  },
},

/* ============================================================ 099 */
{
  id: "099",
  title: "The Forecast Post-Mortem",
  difficulty: "Medium",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Eval",
  archetype: "Maintainer",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "MSFT MAI Strategy & Ops", "Anthropic TPM Safeguards & Evals"],
  tags: ["calibration", "post-mortem", "resolution", "gnomon"],
  prompt:
    "Resolution day on your own ledger: eighteen months ago, at the peak of the agent-framework hype, you told the customer's exec team — on the record, with a date — 'Multi-agent orchestration frameworks will consolidate; the standalone orchestration-platform category will effectively fold into the model providers' stacks within 18 months; don't build on the independents.' The date arrived. The read was wrong in an interesting way: the category didn't fold — two independents got acquired, but the largest one tripled revenue, and the customer's competitor built on it successfully. Your advice steered the customer away from a tool that would have worked. The exec sponsor hasn't mentioned it. Your Gnomon ledger has. Run the post-mortem — publicly enough to matter.",
  arc: {
    start: "A dated claim, resolved wrong, that nobody is forcing you to revisit — except your own ledger.",
    mid: "Decompose the miss: which premises failed, which held, what the cost was — and what the forecasting process should learn.",
    end: "The miss published to its audience, the process patched, and a credibility account that compounds because it reports losses.",
  },
  expected: {
    bottleneck: "The miss is unexamined and its lessons are structural, not incidental: the forecast bundled premises (consolidation pressure was real — two acquisitions happened) with a timing call and a category-death conclusion that didn't follow, the advice attached to it had asymmetric costs nobody priced (steering away from a workable tool cost the customer optionality), and the strongest pull is to let it slide — the sponsor forgot, the ledger didn't, and unexamined misses compound into exactly the uncalibrated confidence this whole bank exists to train out (027's watermelon, run on your own forecasting record).",
    failureMode: "The quiet burial: the miss goes unmentioned, the next confident read gets delivered with the same unexamined process — and either the sponsor's team remembers (they usually do: 'you told us not to build on X' surfaces at the worst QBR, with 043's attribution now running against you) or worse, they don't, and your calibration debt grows invisibly until a bigger miss lands on a bigger decision, at which point the ledger's silence reads as a pattern of hidden losses (042's moved goalposts, self-authored).",
    nextMove: "Run it like an incident, publish it like a practice: (1) decompose the claim into its premises and grade each — consolidation pressure: RIGHT (two acquisitions); model providers absorbing orchestration: PARTIALLY RIGHT (their stacks grew, but as one option among several); category death in 18 months: WRONG (the leader tripled — network effects and switching costs outran platform absorption); the timing: overconfident by construction (18-month category-death calls need extraordinary evidence — 053's razor applied to your own demo); (2) price the advice's cost honestly — what the customer lost (time-to-capability on workflows the competitor shipped, priced with 043's attribution honesty: some of the gap is the tool, some isn't) and what the advice PROTECTED (the two acquired platforms' customers ate 064-scale migrations — the read wasn't costless-wrong); (3) extract the process lessons — the forecast conflated directional pressure with terminal outcome (consolidation ≠ death), ignored the survivor scenario (base rates: category leaders survive consolidations that kill the middle), and issued binary advice ('don't build') where portfolio advice fit ('build with 094's exit drills'); (4) publish to the audience the original claim had — the sponsor gets the one-pager: claim, verdict, cost, lesson, and the patched process (099's own format); unprompted disclosure of a forgotten miss is the highest-yield credibility purchase available (032's truth economics, applied to yourself); (5) patch the ledger's process — category-death claims now require survivor-scenario analysis, advice attached to forecasts carries hedged structure by default (092's contracts, for recommendations), and the resolution review is calendared, not conscience-triggered.",
    metric: "The post-mortem's own honesty: premises graded individually (not the claim rounded to 'basically right'), costs priced with attribution discipline, and the process patch specific enough to change the NEXT forecast; the standing metric: ledger resolution rate and the calibration curve it feeds — including this red point, plotted.",
    owner: "You own the decomposition, the disclosure, and the patch; the sponsor receives the one-pager (their respect is the return on the disclosure); the ledger gets the resolved entry with the full post-mortem linked — the precedent (042's anchors) for every future miss.",
    falsifier: "If the honest decomposition shows the advice was right despite the forecast being wrong — the customer's specific workloads would have hit the leader platform's enterprise gaps (their 022-style coverage was genuinely thin then), and the competitor's success rode workloads the customer doesn't have — then the post-mortem's finding is subtler and MORE valuable: right advice from wrong reasoning is luck wearing rigor, the process failure is identical, and publishing THAT distinction is the strongest calibration signal a practice can send.",
  },
  modelAnswer:
    "The ledger called; answer it like an incident, because that's what an unexamined miss is — 027's watermelon running on your own forecasting record, green until audited. Decompose before narrating: the claim bundled four things, and they resolved differently. Consolidation pressure: right — two independents got acquired, exactly the mechanism you named. Model providers absorbing orchestration: half-right — their stacks grew into real options, but as competitors in the category, not as its graveyard. Category death in eighteen months: wrong — the leader tripled, because network effects and switching costs outran platform absorption (the survivor scenario your forecast never priced; base rates say consolidation kills the middle and often feeds the leader). And the advice — 'don't build on the independents' — was binary where portfolio fit: 'build with exit drills' (094's discipline existed for exactly this) would have captured the upside and hedged the risk you correctly saw.\n\nPrice it honestly, both directions: the customer lost time-to-capability on workflows their competitor shipped (attributed with 043's discipline — some of that gap is the tool, some is the competitor's execution), and the advice also protected them from the two acquired platforms' fates — their customers ate 064-scale migrations. Wrong-with-partial-cover is the honest verdict; round it neither up nor down.\n\nThen the move that matters: publish to the claim's original audience, unprompted. The sponsor forgot; that's precisely why the disclosure compounds — a one-pager: claim, verdict, cost, lessons, patch. Every incentive says bury it; the practice says the buried miss is a loan against the next big read, at compounding interest. And patch the process, specifically: category-death claims now require survivor-scenario analysis; forecast-attached advice defaults to hedged structure (092's logic, for recommendations); resolution reviews are calendared. The last line of the one-pager is the whole discipline: this practice reports its losses on schedule — which is the only reason its wins should move your decisions.",
  rubric: {
    diagnosis: "Decomposes the bundled claim and grades premises separately — right mechanism, wrong terminal call, unpriced survivor scenario, binary advice where portfolio fit.",
    move: "Incident-grade post-mortem, both-direction cost pricing, unprompted publication to the original audience, and specific process patches.",
    measurement: "The post-mortem's own honesty standards and the calibration curve gaining its red point; falsifier distinguishes right-advice-wrong-reasoning as the subtler, more valuable finding.",
    synthesis: "Turns the bank's machinery on its author — 027's audit, 043's attribution, 094's hedging, 092's structures — the practice eating its own cooking.",
    altitude: "The sponsor receives a disclosure they didn't ask for and remembers it at every future read — credibility bought at its cheapest price.",
    transfer: "Forecast post-mortems are the Gnomon discipline's keystone: resolution without examination is scorekeeping; examination without publication is private virtue; the practice compounds only when misses are decomposed, priced, and shown.",
  },
  adversarial:
    "The quiet-burial failure: the sponsor forgot, the quarter is busy, the next read beckons — and the calibration debt compounds silently until a bigger miss meets a longer memory; buried losses are loans, and the interest rate is your credibility. The rounding failure: 'directionally right — consolidation happened' — grading the bundle instead of the premises is how forecasters stay confidently miscalibrated; two acquisitions don't redeem a category-death call the leader tripled through. The flagellation failure: over-correcting into 'I was completely wrong, ignore my reads' — the mechanism WAS right, the protection WAS real, and self-punishment is as uncalibrated as self-forgiveness; the post-mortem's product is a patched process, not a performance of humility.",
  recursiveFollowup:
    "The one-pager lands; the sponsor respects it — then uses it: 'Since we're being honest about misses — your team's read on our agent-framework choice is due in Q3. Given this post-mortem, why should the board weight your recommendation over the consultancy's, whose track record we've never seen?' The disclosure just became a competitive question: calibrated-with-visible-misses versus confident-with-hidden-ones. Make the case for graded forecasting as a procurement criterion — without sounding like you're spinning your own miss.",
  altitude: {
    exec:
      "Eighteen months ago I told you the orchestration category would fold and to avoid the independents. Resolution: the pressure I named was real — two got acquired — but the leader tripled, and my 'don't build' should have been 'build with exits.' Here's what it cost you, what it protected you from, and what my process now does differently. I'm showing you this unprompted because my reads are only worth taking if you can see the ledger — losses included.",
    engineer:
      "Post-mortem structure: claim decomposed to gradeable premises, each resolved against evidence; cost attribution both directions (043's honesty); process patches as concrete rules (survivor-scenario analysis required, hedged-advice defaults, calendared resolutions). Ledger entry links the full artifact — the precedent format for every future resolution.",
    frontier:
      "Calibration is a practice, not a trait: dated claims, scheduled resolutions, premise-level grading, both-direction cost pricing, and published misses. The transferable law — the forecast record compounds only when its losses are visible — is what separates Gnomon from punditry, and it's the same discipline evals impose on models, finally imposed on the forecaster.",
  },
},

/* ============================================================ 100 */
{
  id: "100",
  title: "Where the Bottleneck Moves Next",
  difficulty: "Hard",
  category: "Market & Capital Calibration",
  primaryLens: "Market",
  secondaryLens: "Altitude",
  archetype: "Grower",
  secondaryArchetype: "Sweeper",
  targetRoles: ["CAPE SCPM", "MSFT MAI Strategy & Ops", "Anthropic TPM Cloud Inference", "OpenAI DPM (Codex)"],
  tags: ["bottleneck-migration", "synthesis", "capstone", "dated-thesis"],
  prompt:
    "The capstone sits across two rooms in one week. Room one: the customer's board, closing their annual strategy review, asks the only question that aggregates all the others: 'We've absorbed the models, built the platform, trained the people. Where does the constraint move next — and where should next year's dollar go?' Room two: a frontier-lab interview panel, final round, asks the same question wearing different clothes: 'Where do you think this industry's binding constraint is in 24 months?' You have the whole map now — silicon, power, serving, models, evals, deployment, trust, talent (091–099's tape). One thesis must serve both rooms: specific enough to allocate money, humble enough to carry falsifiers, and yours. Make the call.",
  arc: {
    start: "Every prior problem was a local read; both rooms now demand the global one — dated, allocated, owned.",
    mid: "Trace the constraint's migration through the stack; commit to where it lands next; attach the falsifiers that make it a position.",
    end: "One thesis, two altitudes, dated markers on the calendar — the bottleneck named before it names itself.",
  },
  expected: {
    bottleneck: "The question demands synthesis under commitment: the constraint has migrated visibly (compute scarcity → serving economics → model capability → deployment/integration → measurement and trust) and every layer's partisans claim it lands with them next — the discipline is tracing WHY it moves (each solved layer exposes the next binding one), committing to a specific landing zone with reasoning, and attaching dated falsifiers, because a bottleneck read without falsifiers is punditry and without allocation is trivia (the bank's first pattern, run at civilization scale, graded like its ninety-ninth).",
    failureMode: "The hedge or the hobby-horse: 'it's all of them, invest broadly' — safe, unfalsifiable, allocates nothing, and both rooms correctly read it as absence of judgment; or the confident single-cause read that rides the asker's favorite layer (compute to the infra crowd, talent to the CHRO, models to the lab panel) — flattering, unexamined, and structurally identical to every launch-day panic the last nine problems trained against (098's verdict-before-evidence, at thesis scale).",
    nextMove: "Build the thesis from the migration's mechanism, not from headlines: (1) trace the solved layers — raw model capability is compounding on lab capex (not the customer's constraint to solve), serving economics industrialized (038/091/095: cost curves falling on schedule where competition holds), platform and integration matured into known patterns (the 080/085 estate is buildable with discipline); (2) name where it binds now and next — the evidence across 016–089 points one direction: the constraint is migrating from CAPABILITY to VERIFICATION-AND-TRUST — the gap between what models can do and what organizations can safely, measurably, accountably LET them do (evals that keep pace with capability [073/088], oversight that means something [089], calibrated confidence in autonomous work [077/083], and the human judgment to govern it [097's talent tape saying the same thing in job postings]); the binding constraint in 24 months is not making agents capable — it's making organizations able to absorb agent capability at the rate it arrives; (3) allocate to the thesis — next year's dollar goes to the absorption stack: measurement infrastructure (the eval estate as a first-class asset), trust machinery (observability, oversight quality, red lines with teeth), and judgment capital (the people and playbooks that govern autonomy — this bank's own wager, named); (4) attach the falsifiers, dated — 'if agent-autonomy incidents DON'T become the industry's limiting news cycle within 18 months, if enterprises' deployment velocity keeps pace with model releases without absorption investment, if 097's tape shows evals/oversight roles declining rather than compounding — the thesis is wrong and capability (or its cost) was still the constraint'; (5) shape it per room — the board gets the allocation with the markers calendared into QBRs; the panel gets the same thesis plus its honest tension (the lab's job is moving the capability frontier; the industry's constraint is absorbing it — and the candidate who can hold both is the one they're hiring for).",
    metric: "The thesis's own Gnomon entry: dated falsifiers on the calendar (incident salience, absorption-gap indicators, the talent tape's drift, the customer's own deployment-velocity-vs-model-release ratio) — reviewed on schedule, graded in public, 099's discipline applied to the biggest claim on the ledger.",
    owner: "You own the call and its grading — both rooms are explicitly buying YOUR judgment, not a survey; the board operationalizes through next year's allocation with the marker sheet; the panel grades the thesis's structure (decomposition, commitment, falsifiers) as much as its content — which is the meta-lesson of the whole bank.",
    falsifier: "If the markers fire against you — capability jumps re-open the gap faster than absorption closes it (a 098-launch that genuinely discontinuates), or serving costs spike (095's chokepoints consolidating) and re-bind the constraint below — then the thesis re-underwrites in public: the migration mechanism was right, the landing zone was early or wrong, and the post-mortem (099's format) ships to both rooms' successors — because the capstone's real claim was never 'I know where it lands'; it was 'I run the discipline that finds out first.'",
  },
  modelAnswer:
    "Answer with the mechanism first, because it's what makes the call defensible in both rooms: bottlenecks migrate by being solved — each unbound layer exposes the next binding one. Compute scarcity built the clouds; serving economics industrialized (the 038/091/095 arc: costs falling on competitive schedule); model capability is compounding on lab capex — real, spectacular, and no longer the enterprise's constraint to solve. Platform and integration have matured into buildable patterns — the 080/085 estate is discipline now, not mystery. Trace the last hundred problems and the residue is consistent: every hard case that remained hard was a verification-and-trust case — evals racing capability (073/088), oversight that means something (089), autonomy you can audit (077/083), organizations able to say yes safely at the speed the capability arrives.\n\nSo the call, owned: within 24 months, the binding constraint is absorption — the gap between what models can do and what organizations can measurably, accountably let them do. Not capability; the metabolization of capability. The board's dollar goes to the absorption stack: measurement infrastructure as a first-class asset (the eval estate, 086's lineage, 088's process evals), trust machinery (observability, oversight with measured catch rates, red lines with teeth), and judgment capital — the people and playbooks that govern autonomy, which is 097's tape reading the same thesis in job postings, and, said plainly, this practice's own wager on itself. The panel gets the identical thesis with its honest tension named: the lab's mission is moving the capability frontier; the industry's constraint is absorbing it — and holding both without flinching is precisely the judgment the seat requires.\n\nThen what makes it a position instead of a take: falsifiers, dated. If agent-autonomy incidents don't become the limiting news cycle within eighteen months; if enterprise deployment velocity tracks model releases WITHOUT absorption investment; if the talent tape shows evals and oversight roles dissolving rather than compounding; if 095's chokepoints consolidate and re-bind the constraint below — the thesis re-underwrites, in public, in 099's format. Because the capstone claim — the one both rooms are actually buying — was never 'I know where the bottleneck lands.' It's 'I run the discipline that names its landing zone, prices the bet, watches the markers, and grades itself first.' That discipline is the answer to the hundredth problem, and to the ninety-nine before it.",
  rubric: {
    diagnosis: "Derives the call from the migration mechanism — solved layers exposing the next bind — rather than from any layer's partisan headline.",
    move: "Commits to the absorption thesis with a real allocation, shapes it to both altitudes, and names the lab-room tension honestly.",
    measurement: "Dated falsifiers calendared and self-graded — the thesis as the ledger's biggest Gnomon entry, 099's discipline at full scale.",
    synthesis: "The capstone synthesis: reads the whole bank's residue as evidence, prices its own wager (judgment capital), and closes the loop with pattern #1 at industry scale.",
    altitude: "One thesis, two rooms — the board gets allocation with markers, the panel gets structure plus tension; neither gets a hedge.",
    transfer: "The global bottleneck read IS the transfer: every seat this bank targets — CAPE, MAI, FDE, TPM — is a bet on where the constraint moves, and the discipline of calling it with falsifiers is the job description underneath all of them.",
  },
  adversarial:
    "The hedge failure: 'all layers matter, diversify' — unfalsifiable, unallocatable, and both rooms read it correctly as judgment's absence; the board can diversify without you, and the panel is hiring for exactly the commitment you dodged. The partisan failure: reading the room's favorite layer back to it — compute to infra people, models to the lab — flattering, and structurally identical to the launch-day panic 098 trained against; a thesis that changes per audience isn't a thesis. The falsifier-theater miss: naming markers without calendaring their review — 095's law at capstone scale: indicators without pre-stated triggers are ambient anxiety, and a self-grading discipline that never schedules the grade is 027's watermelon, planted in your own ledger. And the humility inversion: so many falsifiers the call disappears — the discipline is commitment WITH exits, not exits instead of commitment.",
  recursiveFollowup:
    "Both rooms buy it. Eighteen months later the markers return a split verdict: absorption investment compounded exactly as called (evals, oversight, and governance roles boomed — 097's tape confirms), AND a capability discontinuity landed (a 098-launch that cleared every hard eval bar at sane cost), re-opening the gap faster than absorption closed it. The constraint didn't migrate OR stay — it forked: organizations now bind on absorption AND capability simultaneously, at different layers of the same stack. The board asks for next year's allocation; the thesis needs its first major re-underwrite. Run it — with 099's format, in front of the successors of everyone who bought the original call.",
  altitude: {
    exec:
      "The constraint moves by being solved: compute built out, serving industrialized, models compounding on the labs' capex — none of those are where your next dollar binds. What's binding is absorption: the gap between what agents can do and what your organization can safely, measurably let them do. So the allocation: measurement as an asset, trust machinery with teeth, and the judgment layer — people and playbooks that govern autonomy. Four dated markers on the QBR calendar will tell us if I'm wrong — and if I am, you'll hear it from me first, with the post-mortem attached.",
    engineer:
      "Instrument the thesis: deployment-velocity vs model-release ratio (the absorption gap, measured on our own estate), incident-salience tracking, the talent tape's evals/oversight drift (097's rubric), serving-cost trend as the re-bind detector (095's sheet). Review triggers pre-stated; re-underwrite protocol is 099's format. The thesis is an entry in the same ledger as everything else — biggest claim, same grading.",
    frontier:
      "The industry's whole story is bottleneck migration — compute to serving to capability to absorption — and the craft is calling the next landing zone with commitment, allocation, and dated falsifiers. The transferable law, and the bank's closing argument: judgment is the discipline of naming the constraint before it names itself, betting on the call, and grading the bet in public. That's the hundredth problem, and the first one, and the job.",
  },
},

);
